package com.car.mapper;

import com.car.pojo.Ac_refrigerator;
import com.car.pojo.Ac_refrigeratorExample;
import java.util.List;

public interface Ac_refrigeratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_refrigerator
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_refrigerator
     *
     * @mbg.generated
     */
    int insert(Ac_refrigerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_refrigerator
     *
     * @mbg.generated
     */
    int insertSelective(Ac_refrigerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_refrigerator
     *
     * @mbg.generated
     */
    List<Ac_refrigerator> selectByExample(Ac_refrigeratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_refrigerator
     *
     * @mbg.generated
     */
    Ac_refrigerator selectByPrimaryKey(String num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_refrigerator
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Ac_refrigerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_refrigerator
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ac_refrigerator record);
}