package com.car.mapper;

import com.car.pojo.Chassis_steering;
import com.car.pojo.Chassis_steeringExample;
import java.util.List;

public interface Chassis_steeringMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis_steering
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis_steering
     *
     * @mbg.generated
     */
    int insert(Chassis_steering record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis_steering
     *
     * @mbg.generated
     */
    int insertSelective(Chassis_steering record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis_steering
     *
     * @mbg.generated
     */
    List<Chassis_steering> selectByExample(Chassis_steeringExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis_steering
     *
     * @mbg.generated
     */
    Chassis_steering selectByPrimaryKey(String num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis_steering
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Chassis_steering record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chassis_steering
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Chassis_steering record);
}