package com.car.mapper;

import com.car.pojo.External_configuration;
import com.car.pojo.External_configurationExample;
import java.util.List;

public interface External_configurationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    int insert(External_configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    int insertSelective(External_configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    List<External_configuration> selectByExample(External_configurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    External_configuration selectByPrimaryKey(String num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(External_configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(External_configuration record);
}