package com.car.mapper;

import com.car.pojo.Glass_rearviewmirror;
import com.car.pojo.Glass_rearviewmirrorExample;
import java.util.List;

public interface Glass_rearviewmirrorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_rearviewmirror
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_rearviewmirror
     *
     * @mbg.generated
     */
    int insert(Glass_rearviewmirror record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_rearviewmirror
     *
     * @mbg.generated
     */
    int insertSelective(Glass_rearviewmirror record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_rearviewmirror
     *
     * @mbg.generated
     */
    List<Glass_rearviewmirror> selectByExample(Glass_rearviewmirrorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_rearviewmirror
     *
     * @mbg.generated
     */
    Glass_rearviewmirror selectByPrimaryKey(String num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_rearviewmirror
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Glass_rearviewmirror record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glass_rearviewmirror
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Glass_rearviewmirror record);
}