package com.car.mapper;

import com.car.pojo.High_tech_configuration;
import com.car.pojo.High_tech_configurationExample;
import java.util.List;

public interface High_tech_configurationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    int insert(High_tech_configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    int insertSelective(High_tech_configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    List<High_tech_configuration> selectByExample(High_tech_configurationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    High_tech_configuration selectByPrimaryKey(String num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(High_tech_configuration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(High_tech_configuration record);
}