package com.car.mapper;

import com.car.pojo.Safety_equipment;
import com.car.pojo.Safety_equipmentExample;

import java.util.List;

public interface Safety_equipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    int insert(Safety_equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    int insertSelective(Safety_equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    List<Safety_equipment> selectByExample(Safety_equipmentExample example);
    Safety_equipment selectByPrimaryKey(String num);
}