package com.car.mapper;

import com.car.pojo.Transmission;
import com.car.pojo.TransmissionExample;
import java.util.List;

public interface TransmissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transmission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transmission
     *
     * @mbg.generated
     */
    int insert(Transmission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transmission
     *
     * @mbg.generated
     */
    int insertSelective(Transmission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transmission
     *
     * @mbg.generated
     */
    List<Transmission> selectByExample(TransmissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transmission
     *
     * @mbg.generated
     */
    Transmission selectByPrimaryKey(String num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transmission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Transmission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transmission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Transmission record);
}