package com.car.mapper;

import com.car.pojo.Wheel_brake;
import com.car.pojo.Wheel_brakeExample;
import java.util.List;

public interface Wheel_brakeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wheel_brake
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wheel_brake
     *
     * @mbg.generated
     */
    int insert(Wheel_brake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wheel_brake
     *
     * @mbg.generated
     */
    int insertSelective(Wheel_brake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wheel_brake
     *
     * @mbg.generated
     */
    List<Wheel_brake> selectByExample(Wheel_brakeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wheel_brake
     *
     * @mbg.generated
     */
    Wheel_brake selectByPrimaryKey(String num);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wheel_brake
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Wheel_brake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wheel_brake
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Wheel_brake record);
}