package com.car.pojo;

import java.util.ArrayList;
import java.util.List;

public class Basic_parameterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basic_parameter
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basic_parameter
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table basic_parameter
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_parameter
     *
     * @mbg.generated
     */
    public Basic_parameterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_parameter
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_parameter
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_parameter
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_parameter
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_parameter
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_parameter
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_parameter
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_parameter
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_parameter
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_parameter
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table basic_parameter
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNumIsNull() {
            addCriterion("Num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("Num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("Num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("Num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("Num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("Num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("Num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("Num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("Num like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("Num not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("Num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("Num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("Num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("Num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andModelnameIsNull() {
            addCriterion("ModelName is null");
            return (Criteria) this;
        }

        public Criteria andModelnameIsNotNull() {
            addCriterion("ModelName is not null");
            return (Criteria) this;
        }

        public Criteria andModelnameEqualTo(String value) {
            addCriterion("ModelName =", value, "modelname");
            return (Criteria) this;
        }

        public Criteria andModelnameNotEqualTo(String value) {
            addCriterion("ModelName <>", value, "modelname");
            return (Criteria) this;
        }

        public Criteria andModelnameGreaterThan(String value) {
            addCriterion("ModelName >", value, "modelname");
            return (Criteria) this;
        }

        public Criteria andModelnameGreaterThanOrEqualTo(String value) {
            addCriterion("ModelName >=", value, "modelname");
            return (Criteria) this;
        }

        public Criteria andModelnameLessThan(String value) {
            addCriterion("ModelName <", value, "modelname");
            return (Criteria) this;
        }

        public Criteria andModelnameLessThanOrEqualTo(String value) {
            addCriterion("ModelName <=", value, "modelname");
            return (Criteria) this;
        }

        public Criteria andModelnameLike(String value) {
            addCriterion("ModelName like", value, "modelname");
            return (Criteria) this;
        }

        public Criteria andModelnameNotLike(String value) {
            addCriterion("ModelName not like", value, "modelname");
            return (Criteria) this;
        }

        public Criteria andModelnameIn(List<String> values) {
            addCriterion("ModelName in", values, "modelname");
            return (Criteria) this;
        }

        public Criteria andModelnameNotIn(List<String> values) {
            addCriterion("ModelName not in", values, "modelname");
            return (Criteria) this;
        }

        public Criteria andModelnameBetween(String value1, String value2) {
            addCriterion("ModelName between", value1, value2, "modelname");
            return (Criteria) this;
        }

        public Criteria andModelnameNotBetween(String value1, String value2) {
            addCriterion("ModelName not between", value1, value2, "modelname");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("Price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("Price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(String value) {
            addCriterion("Price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(String value) {
            addCriterion("Price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(String value) {
            addCriterion("Price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(String value) {
            addCriterion("Price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(String value) {
            addCriterion("Price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(String value) {
            addCriterion("Price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLike(String value) {
            addCriterion("Price like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotLike(String value) {
            addCriterion("Price not like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<String> values) {
            addCriterion("Price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<String> values) {
            addCriterion("Price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(String value1, String value2) {
            addCriterion("Price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(String value1, String value2) {
            addCriterion("Price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andManufacturerIsNull() {
            addCriterion("Manufacturer is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerIsNotNull() {
            addCriterion("Manufacturer is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerEqualTo(String value) {
            addCriterion("Manufacturer =", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotEqualTo(String value) {
            addCriterion("Manufacturer <>", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerGreaterThan(String value) {
            addCriterion("Manufacturer >", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerGreaterThanOrEqualTo(String value) {
            addCriterion("Manufacturer >=", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLessThan(String value) {
            addCriterion("Manufacturer <", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLessThanOrEqualTo(String value) {
            addCriterion("Manufacturer <=", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLike(String value) {
            addCriterion("Manufacturer like", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotLike(String value) {
            addCriterion("Manufacturer not like", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerIn(List<String> values) {
            addCriterion("Manufacturer in", values, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotIn(List<String> values) {
            addCriterion("Manufacturer not in", values, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerBetween(String value1, String value2) {
            addCriterion("Manufacturer between", value1, value2, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotBetween(String value1, String value2) {
            addCriterion("Manufacturer not between", value1, value2, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(String value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(String value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(String value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(String value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLike(String value) {
            addCriterion("level like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotLike(String value) {
            addCriterion("level not like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<String> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<String> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(String value1, String value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andEngineIsNull() {
            addCriterion("Engine is null");
            return (Criteria) this;
        }

        public Criteria andEngineIsNotNull() {
            addCriterion("Engine is not null");
            return (Criteria) this;
        }

        public Criteria andEngineEqualTo(String value) {
            addCriterion("Engine =", value, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineNotEqualTo(String value) {
            addCriterion("Engine <>", value, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineGreaterThan(String value) {
            addCriterion("Engine >", value, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineGreaterThanOrEqualTo(String value) {
            addCriterion("Engine >=", value, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineLessThan(String value) {
            addCriterion("Engine <", value, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineLessThanOrEqualTo(String value) {
            addCriterion("Engine <=", value, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineLike(String value) {
            addCriterion("Engine like", value, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineNotLike(String value) {
            addCriterion("Engine not like", value, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineIn(List<String> values) {
            addCriterion("Engine in", values, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineNotIn(List<String> values) {
            addCriterion("Engine not in", values, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineBetween(String value1, String value2) {
            addCriterion("Engine between", value1, value2, "engine");
            return (Criteria) this;
        }

        public Criteria andEngineNotBetween(String value1, String value2) {
            addCriterion("Engine not between", value1, value2, "engine");
            return (Criteria) this;
        }

        public Criteria andTransmissionIsNull() {
            addCriterion("Transmission is null");
            return (Criteria) this;
        }

        public Criteria andTransmissionIsNotNull() {
            addCriterion("Transmission is not null");
            return (Criteria) this;
        }

        public Criteria andTransmissionEqualTo(String value) {
            addCriterion("Transmission =", value, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionNotEqualTo(String value) {
            addCriterion("Transmission <>", value, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionGreaterThan(String value) {
            addCriterion("Transmission >", value, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionGreaterThanOrEqualTo(String value) {
            addCriterion("Transmission >=", value, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionLessThan(String value) {
            addCriterion("Transmission <", value, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionLessThanOrEqualTo(String value) {
            addCriterion("Transmission <=", value, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionLike(String value) {
            addCriterion("Transmission like", value, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionNotLike(String value) {
            addCriterion("Transmission not like", value, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionIn(List<String> values) {
            addCriterion("Transmission in", values, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionNotIn(List<String> values) {
            addCriterion("Transmission not in", values, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionBetween(String value1, String value2) {
            addCriterion("Transmission between", value1, value2, "transmission");
            return (Criteria) this;
        }

        public Criteria andTransmissionNotBetween(String value1, String value2) {
            addCriterion("Transmission not between", value1, value2, "transmission");
            return (Criteria) this;
        }

        public Criteria andLengthwidthheightIsNull() {
            addCriterion("LengthWidthHeight is null");
            return (Criteria) this;
        }

        public Criteria andLengthwidthheightIsNotNull() {
            addCriterion("LengthWidthHeight is not null");
            return (Criteria) this;
        }

        public Criteria andLengthwidthheightEqualTo(String value) {
            addCriterion("LengthWidthHeight =", value, "lengthwidthheight");
            return (Criteria) this;
        }

        public Criteria andLengthwidthheightNotEqualTo(String value) {
            addCriterion("LengthWidthHeight <>", value, "lengthwidthheight");
            return (Criteria) this;
        }

        public Criteria andLengthwidthheightGreaterThan(String value) {
            addCriterion("LengthWidthHeight >", value, "lengthwidthheight");
            return (Criteria) this;
        }

        public Criteria andLengthwidthheightGreaterThanOrEqualTo(String value) {
            addCriterion("LengthWidthHeight >=", value, "lengthwidthheight");
            return (Criteria) this;
        }

        public Criteria andLengthwidthheightLessThan(String value) {
            addCriterion("LengthWidthHeight <", value, "lengthwidthheight");
            return (Criteria) this;
        }

        public Criteria andLengthwidthheightLessThanOrEqualTo(String value) {
            addCriterion("LengthWidthHeight <=", value, "lengthwidthheight");
            return (Criteria) this;
        }

        public Criteria andLengthwidthheightLike(String value) {
            addCriterion("LengthWidthHeight like", value, "lengthwidthheight");
            return (Criteria) this;
        }

        public Criteria andLengthwidthheightNotLike(String value) {
            addCriterion("LengthWidthHeight not like", value, "lengthwidthheight");
            return (Criteria) this;
        }

        public Criteria andLengthwidthheightIn(List<String> values) {
            addCriterion("LengthWidthHeight in", values, "lengthwidthheight");
            return (Criteria) this;
        }

        public Criteria andLengthwidthheightNotIn(List<String> values) {
            addCriterion("LengthWidthHeight not in", values, "lengthwidthheight");
            return (Criteria) this;
        }

        public Criteria andLengthwidthheightBetween(String value1, String value2) {
            addCriterion("LengthWidthHeight between", value1, value2, "lengthwidthheight");
            return (Criteria) this;
        }

        public Criteria andLengthwidthheightNotBetween(String value1, String value2) {
            addCriterion("LengthWidthHeight not between", value1, value2, "lengthwidthheight");
            return (Criteria) this;
        }

        public Criteria andBodystructureIsNull() {
            addCriterion("BodyStructure is null");
            return (Criteria) this;
        }

        public Criteria andBodystructureIsNotNull() {
            addCriterion("BodyStructure is not null");
            return (Criteria) this;
        }

        public Criteria andBodystructureEqualTo(String value) {
            addCriterion("BodyStructure =", value, "bodystructure");
            return (Criteria) this;
        }

        public Criteria andBodystructureNotEqualTo(String value) {
            addCriterion("BodyStructure <>", value, "bodystructure");
            return (Criteria) this;
        }

        public Criteria andBodystructureGreaterThan(String value) {
            addCriterion("BodyStructure >", value, "bodystructure");
            return (Criteria) this;
        }

        public Criteria andBodystructureGreaterThanOrEqualTo(String value) {
            addCriterion("BodyStructure >=", value, "bodystructure");
            return (Criteria) this;
        }

        public Criteria andBodystructureLessThan(String value) {
            addCriterion("BodyStructure <", value, "bodystructure");
            return (Criteria) this;
        }

        public Criteria andBodystructureLessThanOrEqualTo(String value) {
            addCriterion("BodyStructure <=", value, "bodystructure");
            return (Criteria) this;
        }

        public Criteria andBodystructureLike(String value) {
            addCriterion("BodyStructure like", value, "bodystructure");
            return (Criteria) this;
        }

        public Criteria andBodystructureNotLike(String value) {
            addCriterion("BodyStructure not like", value, "bodystructure");
            return (Criteria) this;
        }

        public Criteria andBodystructureIn(List<String> values) {
            addCriterion("BodyStructure in", values, "bodystructure");
            return (Criteria) this;
        }

        public Criteria andBodystructureNotIn(List<String> values) {
            addCriterion("BodyStructure not in", values, "bodystructure");
            return (Criteria) this;
        }

        public Criteria andBodystructureBetween(String value1, String value2) {
            addCriterion("BodyStructure between", value1, value2, "bodystructure");
            return (Criteria) this;
        }

        public Criteria andBodystructureNotBetween(String value1, String value2) {
            addCriterion("BodyStructure not between", value1, value2, "bodystructure");
            return (Criteria) this;
        }

        public Criteria andTopspeedIsNull() {
            addCriterion("TopSpeed is null");
            return (Criteria) this;
        }

        public Criteria andTopspeedIsNotNull() {
            addCriterion("TopSpeed is not null");
            return (Criteria) this;
        }

        public Criteria andTopspeedEqualTo(String value) {
            addCriterion("TopSpeed =", value, "topspeed");
            return (Criteria) this;
        }

        public Criteria andTopspeedNotEqualTo(String value) {
            addCriterion("TopSpeed <>", value, "topspeed");
            return (Criteria) this;
        }

        public Criteria andTopspeedGreaterThan(String value) {
            addCriterion("TopSpeed >", value, "topspeed");
            return (Criteria) this;
        }

        public Criteria andTopspeedGreaterThanOrEqualTo(String value) {
            addCriterion("TopSpeed >=", value, "topspeed");
            return (Criteria) this;
        }

        public Criteria andTopspeedLessThan(String value) {
            addCriterion("TopSpeed <", value, "topspeed");
            return (Criteria) this;
        }

        public Criteria andTopspeedLessThanOrEqualTo(String value) {
            addCriterion("TopSpeed <=", value, "topspeed");
            return (Criteria) this;
        }

        public Criteria andTopspeedLike(String value) {
            addCriterion("TopSpeed like", value, "topspeed");
            return (Criteria) this;
        }

        public Criteria andTopspeedNotLike(String value) {
            addCriterion("TopSpeed not like", value, "topspeed");
            return (Criteria) this;
        }

        public Criteria andTopspeedIn(List<String> values) {
            addCriterion("TopSpeed in", values, "topspeed");
            return (Criteria) this;
        }

        public Criteria andTopspeedNotIn(List<String> values) {
            addCriterion("TopSpeed not in", values, "topspeed");
            return (Criteria) this;
        }

        public Criteria andTopspeedBetween(String value1, String value2) {
            addCriterion("TopSpeed between", value1, value2, "topspeed");
            return (Criteria) this;
        }

        public Criteria andTopspeedNotBetween(String value1, String value2) {
            addCriterion("TopSpeed not between", value1, value2, "topspeed");
            return (Criteria) this;
        }

        public Criteria andOfficial0100accelerationIsNull() {
            addCriterion("Official0-100Acceleration is null");
            return (Criteria) this;
        }

        public Criteria andOfficial0100accelerationIsNotNull() {
            addCriterion("Official0-100Acceleration is not null");
            return (Criteria) this;
        }

        public Criteria andOfficial0100accelerationEqualTo(String value) {
            addCriterion("Official0-100Acceleration =", value, "official0100acceleration");
            return (Criteria) this;
        }

        public Criteria andOfficial0100accelerationNotEqualTo(String value) {
            addCriterion("Official0-100Acceleration <>", value, "official0100acceleration");
            return (Criteria) this;
        }

        public Criteria andOfficial0100accelerationGreaterThan(String value) {
            addCriterion("Official0-100Acceleration >", value, "official0100acceleration");
            return (Criteria) this;
        }

        public Criteria andOfficial0100accelerationGreaterThanOrEqualTo(String value) {
            addCriterion("Official0-100Acceleration >=", value, "official0100acceleration");
            return (Criteria) this;
        }

        public Criteria andOfficial0100accelerationLessThan(String value) {
            addCriterion("Official0-100Acceleration <", value, "official0100acceleration");
            return (Criteria) this;
        }

        public Criteria andOfficial0100accelerationLessThanOrEqualTo(String value) {
            addCriterion("Official0-100Acceleration <=", value, "official0100acceleration");
            return (Criteria) this;
        }

        public Criteria andOfficial0100accelerationLike(String value) {
            addCriterion("Official0-100Acceleration like", value, "official0100acceleration");
            return (Criteria) this;
        }

        public Criteria andOfficial0100accelerationNotLike(String value) {
            addCriterion("Official0-100Acceleration not like", value, "official0100acceleration");
            return (Criteria) this;
        }

        public Criteria andOfficial0100accelerationIn(List<String> values) {
            addCriterion("Official0-100Acceleration in", values, "official0100acceleration");
            return (Criteria) this;
        }

        public Criteria andOfficial0100accelerationNotIn(List<String> values) {
            addCriterion("Official0-100Acceleration not in", values, "official0100acceleration");
            return (Criteria) this;
        }

        public Criteria andOfficial0100accelerationBetween(String value1, String value2) {
            addCriterion("Official0-100Acceleration between", value1, value2, "official0100acceleration");
            return (Criteria) this;
        }

        public Criteria andOfficial0100accelerationNotBetween(String value1, String value2) {
            addCriterion("Official0-100Acceleration not between", value1, value2, "official0100acceleration");
            return (Criteria) this;
        }

        public Criteria andMeasured0100accelerationIsNull() {
            addCriterion("Measured0-100Acceleration is null");
            return (Criteria) this;
        }

        public Criteria andMeasured0100accelerationIsNotNull() {
            addCriterion("Measured0-100Acceleration is not null");
            return (Criteria) this;
        }

        public Criteria andMeasured0100accelerationEqualTo(String value) {
            addCriterion("Measured0-100Acceleration =", value, "measured0100acceleration");
            return (Criteria) this;
        }

        public Criteria andMeasured0100accelerationNotEqualTo(String value) {
            addCriterion("Measured0-100Acceleration <>", value, "measured0100acceleration");
            return (Criteria) this;
        }

        public Criteria andMeasured0100accelerationGreaterThan(String value) {
            addCriterion("Measured0-100Acceleration >", value, "measured0100acceleration");
            return (Criteria) this;
        }

        public Criteria andMeasured0100accelerationGreaterThanOrEqualTo(String value) {
            addCriterion("Measured0-100Acceleration >=", value, "measured0100acceleration");
            return (Criteria) this;
        }

        public Criteria andMeasured0100accelerationLessThan(String value) {
            addCriterion("Measured0-100Acceleration <", value, "measured0100acceleration");
            return (Criteria) this;
        }

        public Criteria andMeasured0100accelerationLessThanOrEqualTo(String value) {
            addCriterion("Measured0-100Acceleration <=", value, "measured0100acceleration");
            return (Criteria) this;
        }

        public Criteria andMeasured0100accelerationLike(String value) {
            addCriterion("Measured0-100Acceleration like", value, "measured0100acceleration");
            return (Criteria) this;
        }

        public Criteria andMeasured0100accelerationNotLike(String value) {
            addCriterion("Measured0-100Acceleration not like", value, "measured0100acceleration");
            return (Criteria) this;
        }

        public Criteria andMeasured0100accelerationIn(List<String> values) {
            addCriterion("Measured0-100Acceleration in", values, "measured0100acceleration");
            return (Criteria) this;
        }

        public Criteria andMeasured0100accelerationNotIn(List<String> values) {
            addCriterion("Measured0-100Acceleration not in", values, "measured0100acceleration");
            return (Criteria) this;
        }

        public Criteria andMeasured0100accelerationBetween(String value1, String value2) {
            addCriterion("Measured0-100Acceleration between", value1, value2, "measured0100acceleration");
            return (Criteria) this;
        }

        public Criteria andMeasured0100accelerationNotBetween(String value1, String value2) {
            addCriterion("Measured0-100Acceleration not between", value1, value2, "measured0100acceleration");
            return (Criteria) this;
        }

        public Criteria andMeasuredbraking1000IsNull() {
            addCriterion("Measuredbraking100-0 is null");
            return (Criteria) this;
        }

        public Criteria andMeasuredbraking1000IsNotNull() {
            addCriterion("Measuredbraking100-0 is not null");
            return (Criteria) this;
        }

        public Criteria andMeasuredbraking1000EqualTo(String value) {
            addCriterion("Measuredbraking100-0 =", value, "measuredbraking1000");
            return (Criteria) this;
        }

        public Criteria andMeasuredbraking1000NotEqualTo(String value) {
            addCriterion("Measuredbraking100-0 <>", value, "measuredbraking1000");
            return (Criteria) this;
        }

        public Criteria andMeasuredbraking1000GreaterThan(String value) {
            addCriterion("Measuredbraking100-0 >", value, "measuredbraking1000");
            return (Criteria) this;
        }

        public Criteria andMeasuredbraking1000GreaterThanOrEqualTo(String value) {
            addCriterion("Measuredbraking100-0 >=", value, "measuredbraking1000");
            return (Criteria) this;
        }

        public Criteria andMeasuredbraking1000LessThan(String value) {
            addCriterion("Measuredbraking100-0 <", value, "measuredbraking1000");
            return (Criteria) this;
        }

        public Criteria andMeasuredbraking1000LessThanOrEqualTo(String value) {
            addCriterion("Measuredbraking100-0 <=", value, "measuredbraking1000");
            return (Criteria) this;
        }

        public Criteria andMeasuredbraking1000Like(String value) {
            addCriterion("Measuredbraking100-0 like", value, "measuredbraking1000");
            return (Criteria) this;
        }

        public Criteria andMeasuredbraking1000NotLike(String value) {
            addCriterion("Measuredbraking100-0 not like", value, "measuredbraking1000");
            return (Criteria) this;
        }

        public Criteria andMeasuredbraking1000In(List<String> values) {
            addCriterion("Measuredbraking100-0 in", values, "measuredbraking1000");
            return (Criteria) this;
        }

        public Criteria andMeasuredbraking1000NotIn(List<String> values) {
            addCriterion("Measuredbraking100-0 not in", values, "measuredbraking1000");
            return (Criteria) this;
        }

        public Criteria andMeasuredbraking1000Between(String value1, String value2) {
            addCriterion("Measuredbraking100-0 between", value1, value2, "measuredbraking1000");
            return (Criteria) this;
        }

        public Criteria andMeasuredbraking1000NotBetween(String value1, String value2) {
            addCriterion("Measuredbraking100-0 not between", value1, value2, "measuredbraking1000");
            return (Criteria) this;
        }

        public Criteria andMeasuredfuelconsumptionIsNull() {
            addCriterion("MeasuredFuelConsumption is null");
            return (Criteria) this;
        }

        public Criteria andMeasuredfuelconsumptionIsNotNull() {
            addCriterion("MeasuredFuelConsumption is not null");
            return (Criteria) this;
        }

        public Criteria andMeasuredfuelconsumptionEqualTo(String value) {
            addCriterion("MeasuredFuelConsumption =", value, "measuredfuelconsumption");
            return (Criteria) this;
        }

        public Criteria andMeasuredfuelconsumptionNotEqualTo(String value) {
            addCriterion("MeasuredFuelConsumption <>", value, "measuredfuelconsumption");
            return (Criteria) this;
        }

        public Criteria andMeasuredfuelconsumptionGreaterThan(String value) {
            addCriterion("MeasuredFuelConsumption >", value, "measuredfuelconsumption");
            return (Criteria) this;
        }

        public Criteria andMeasuredfuelconsumptionGreaterThanOrEqualTo(String value) {
            addCriterion("MeasuredFuelConsumption >=", value, "measuredfuelconsumption");
            return (Criteria) this;
        }

        public Criteria andMeasuredfuelconsumptionLessThan(String value) {
            addCriterion("MeasuredFuelConsumption <", value, "measuredfuelconsumption");
            return (Criteria) this;
        }

        public Criteria andMeasuredfuelconsumptionLessThanOrEqualTo(String value) {
            addCriterion("MeasuredFuelConsumption <=", value, "measuredfuelconsumption");
            return (Criteria) this;
        }

        public Criteria andMeasuredfuelconsumptionLike(String value) {
            addCriterion("MeasuredFuelConsumption like", value, "measuredfuelconsumption");
            return (Criteria) this;
        }

        public Criteria andMeasuredfuelconsumptionNotLike(String value) {
            addCriterion("MeasuredFuelConsumption not like", value, "measuredfuelconsumption");
            return (Criteria) this;
        }

        public Criteria andMeasuredfuelconsumptionIn(List<String> values) {
            addCriterion("MeasuredFuelConsumption in", values, "measuredfuelconsumption");
            return (Criteria) this;
        }

        public Criteria andMeasuredfuelconsumptionNotIn(List<String> values) {
            addCriterion("MeasuredFuelConsumption not in", values, "measuredfuelconsumption");
            return (Criteria) this;
        }

        public Criteria andMeasuredfuelconsumptionBetween(String value1, String value2) {
            addCriterion("MeasuredFuelConsumption between", value1, value2, "measuredfuelconsumption");
            return (Criteria) this;
        }

        public Criteria andMeasuredfuelconsumptionNotBetween(String value1, String value2) {
            addCriterion("MeasuredFuelConsumption not between", value1, value2, "measuredfuelconsumption");
            return (Criteria) this;
        }

        public Criteria andMinistryofindustryIsNull() {
            addCriterion("MinistryOfIndustry is null");
            return (Criteria) this;
        }

        public Criteria andMinistryofindustryIsNotNull() {
            addCriterion("MinistryOfIndustry is not null");
            return (Criteria) this;
        }

        public Criteria andMinistryofindustryEqualTo(String value) {
            addCriterion("MinistryOfIndustry =", value, "ministryofindustry");
            return (Criteria) this;
        }

        public Criteria andMinistryofindustryNotEqualTo(String value) {
            addCriterion("MinistryOfIndustry <>", value, "ministryofindustry");
            return (Criteria) this;
        }

        public Criteria andMinistryofindustryGreaterThan(String value) {
            addCriterion("MinistryOfIndustry >", value, "ministryofindustry");
            return (Criteria) this;
        }

        public Criteria andMinistryofindustryGreaterThanOrEqualTo(String value) {
            addCriterion("MinistryOfIndustry >=", value, "ministryofindustry");
            return (Criteria) this;
        }

        public Criteria andMinistryofindustryLessThan(String value) {
            addCriterion("MinistryOfIndustry <", value, "ministryofindustry");
            return (Criteria) this;
        }

        public Criteria andMinistryofindustryLessThanOrEqualTo(String value) {
            addCriterion("MinistryOfIndustry <=", value, "ministryofindustry");
            return (Criteria) this;
        }

        public Criteria andMinistryofindustryLike(String value) {
            addCriterion("MinistryOfIndustry like", value, "ministryofindustry");
            return (Criteria) this;
        }

        public Criteria andMinistryofindustryNotLike(String value) {
            addCriterion("MinistryOfIndustry not like", value, "ministryofindustry");
            return (Criteria) this;
        }

        public Criteria andMinistryofindustryIn(List<String> values) {
            addCriterion("MinistryOfIndustry in", values, "ministryofindustry");
            return (Criteria) this;
        }

        public Criteria andMinistryofindustryNotIn(List<String> values) {
            addCriterion("MinistryOfIndustry not in", values, "ministryofindustry");
            return (Criteria) this;
        }

        public Criteria andMinistryofindustryBetween(String value1, String value2) {
            addCriterion("MinistryOfIndustry between", value1, value2, "ministryofindustry");
            return (Criteria) this;
        }

        public Criteria andMinistryofindustryNotBetween(String value1, String value2) {
            addCriterion("MinistryOfIndustry not between", value1, value2, "ministryofindustry");
            return (Criteria) this;
        }

        public Criteria andMeasuredgroundclearanceIsNull() {
            addCriterion("MeasuredGroundClearance is null");
            return (Criteria) this;
        }

        public Criteria andMeasuredgroundclearanceIsNotNull() {
            addCriterion("MeasuredGroundClearance is not null");
            return (Criteria) this;
        }

        public Criteria andMeasuredgroundclearanceEqualTo(String value) {
            addCriterion("MeasuredGroundClearance =", value, "measuredgroundclearance");
            return (Criteria) this;
        }

        public Criteria andMeasuredgroundclearanceNotEqualTo(String value) {
            addCriterion("MeasuredGroundClearance <>", value, "measuredgroundclearance");
            return (Criteria) this;
        }

        public Criteria andMeasuredgroundclearanceGreaterThan(String value) {
            addCriterion("MeasuredGroundClearance >", value, "measuredgroundclearance");
            return (Criteria) this;
        }

        public Criteria andMeasuredgroundclearanceGreaterThanOrEqualTo(String value) {
            addCriterion("MeasuredGroundClearance >=", value, "measuredgroundclearance");
            return (Criteria) this;
        }

        public Criteria andMeasuredgroundclearanceLessThan(String value) {
            addCriterion("MeasuredGroundClearance <", value, "measuredgroundclearance");
            return (Criteria) this;
        }

        public Criteria andMeasuredgroundclearanceLessThanOrEqualTo(String value) {
            addCriterion("MeasuredGroundClearance <=", value, "measuredgroundclearance");
            return (Criteria) this;
        }

        public Criteria andMeasuredgroundclearanceLike(String value) {
            addCriterion("MeasuredGroundClearance like", value, "measuredgroundclearance");
            return (Criteria) this;
        }

        public Criteria andMeasuredgroundclearanceNotLike(String value) {
            addCriterion("MeasuredGroundClearance not like", value, "measuredgroundclearance");
            return (Criteria) this;
        }

        public Criteria andMeasuredgroundclearanceIn(List<String> values) {
            addCriterion("MeasuredGroundClearance in", values, "measuredgroundclearance");
            return (Criteria) this;
        }

        public Criteria andMeasuredgroundclearanceNotIn(List<String> values) {
            addCriterion("MeasuredGroundClearance not in", values, "measuredgroundclearance");
            return (Criteria) this;
        }

        public Criteria andMeasuredgroundclearanceBetween(String value1, String value2) {
            addCriterion("MeasuredGroundClearance between", value1, value2, "measuredgroundclearance");
            return (Criteria) this;
        }

        public Criteria andMeasuredgroundclearanceNotBetween(String value1, String value2) {
            addCriterion("MeasuredGroundClearance not between", value1, value2, "measuredgroundclearance");
            return (Criteria) this;
        }

        public Criteria andThevehiclewarrantyIsNull() {
            addCriterion("TheVehicleWarranty is null");
            return (Criteria) this;
        }

        public Criteria andThevehiclewarrantyIsNotNull() {
            addCriterion("TheVehicleWarranty is not null");
            return (Criteria) this;
        }

        public Criteria andThevehiclewarrantyEqualTo(String value) {
            addCriterion("TheVehicleWarranty =", value, "thevehiclewarranty");
            return (Criteria) this;
        }

        public Criteria andThevehiclewarrantyNotEqualTo(String value) {
            addCriterion("TheVehicleWarranty <>", value, "thevehiclewarranty");
            return (Criteria) this;
        }

        public Criteria andThevehiclewarrantyGreaterThan(String value) {
            addCriterion("TheVehicleWarranty >", value, "thevehiclewarranty");
            return (Criteria) this;
        }

        public Criteria andThevehiclewarrantyGreaterThanOrEqualTo(String value) {
            addCriterion("TheVehicleWarranty >=", value, "thevehiclewarranty");
            return (Criteria) this;
        }

        public Criteria andThevehiclewarrantyLessThan(String value) {
            addCriterion("TheVehicleWarranty <", value, "thevehiclewarranty");
            return (Criteria) this;
        }

        public Criteria andThevehiclewarrantyLessThanOrEqualTo(String value) {
            addCriterion("TheVehicleWarranty <=", value, "thevehiclewarranty");
            return (Criteria) this;
        }

        public Criteria andThevehiclewarrantyLike(String value) {
            addCriterion("TheVehicleWarranty like", value, "thevehiclewarranty");
            return (Criteria) this;
        }

        public Criteria andThevehiclewarrantyNotLike(String value) {
            addCriterion("TheVehicleWarranty not like", value, "thevehiclewarranty");
            return (Criteria) this;
        }

        public Criteria andThevehiclewarrantyIn(List<String> values) {
            addCriterion("TheVehicleWarranty in", values, "thevehiclewarranty");
            return (Criteria) this;
        }

        public Criteria andThevehiclewarrantyNotIn(List<String> values) {
            addCriterion("TheVehicleWarranty not in", values, "thevehiclewarranty");
            return (Criteria) this;
        }

        public Criteria andThevehiclewarrantyBetween(String value1, String value2) {
            addCriterion("TheVehicleWarranty between", value1, value2, "thevehiclewarranty");
            return (Criteria) this;
        }

        public Criteria andThevehiclewarrantyNotBetween(String value1, String value2) {
            addCriterion("TheVehicleWarranty not between", value1, value2, "thevehiclewarranty");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table basic_parameter
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table basic_parameter
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}