package com.car.pojo;

import java.util.ArrayList;
import java.util.List;

public class Control_configurationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table control_configuration
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table control_configuration
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table control_configuration
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_configuration
     *
     * @mbg.generated
     */
    public Control_configurationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_configuration
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_configuration
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_configuration
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_configuration
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_configuration
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_configuration
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_configuration
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_configuration
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_configuration
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_configuration
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table control_configuration
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNumIsNull() {
            addCriterion("Num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("Num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("Num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("Num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("Num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("Num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("Num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("Num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("Num like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("Num not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("Num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("Num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("Num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("Num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andAbsIsNull() {
            addCriterion("ABS is null");
            return (Criteria) this;
        }

        public Criteria andAbsIsNotNull() {
            addCriterion("ABS is not null");
            return (Criteria) this;
        }

        public Criteria andAbsEqualTo(String value) {
            addCriterion("ABS =", value, "abs");
            return (Criteria) this;
        }

        public Criteria andAbsNotEqualTo(String value) {
            addCriterion("ABS <>", value, "abs");
            return (Criteria) this;
        }

        public Criteria andAbsGreaterThan(String value) {
            addCriterion("ABS >", value, "abs");
            return (Criteria) this;
        }

        public Criteria andAbsGreaterThanOrEqualTo(String value) {
            addCriterion("ABS >=", value, "abs");
            return (Criteria) this;
        }

        public Criteria andAbsLessThan(String value) {
            addCriterion("ABS <", value, "abs");
            return (Criteria) this;
        }

        public Criteria andAbsLessThanOrEqualTo(String value) {
            addCriterion("ABS <=", value, "abs");
            return (Criteria) this;
        }

        public Criteria andAbsLike(String value) {
            addCriterion("ABS like", value, "abs");
            return (Criteria) this;
        }

        public Criteria andAbsNotLike(String value) {
            addCriterion("ABS not like", value, "abs");
            return (Criteria) this;
        }

        public Criteria andAbsIn(List<String> values) {
            addCriterion("ABS in", values, "abs");
            return (Criteria) this;
        }

        public Criteria andAbsNotIn(List<String> values) {
            addCriterion("ABS not in", values, "abs");
            return (Criteria) this;
        }

        public Criteria andAbsBetween(String value1, String value2) {
            addCriterion("ABS between", value1, value2, "abs");
            return (Criteria) this;
        }

        public Criteria andAbsNotBetween(String value1, String value2) {
            addCriterion("ABS not between", value1, value2, "abs");
            return (Criteria) this;
        }

        public Criteria andEbdCbcIsNull() {
            addCriterion("EBD_CBC is null");
            return (Criteria) this;
        }

        public Criteria andEbdCbcIsNotNull() {
            addCriterion("EBD_CBC is not null");
            return (Criteria) this;
        }

        public Criteria andEbdCbcEqualTo(String value) {
            addCriterion("EBD_CBC =", value, "ebdCbc");
            return (Criteria) this;
        }

        public Criteria andEbdCbcNotEqualTo(String value) {
            addCriterion("EBD_CBC <>", value, "ebdCbc");
            return (Criteria) this;
        }

        public Criteria andEbdCbcGreaterThan(String value) {
            addCriterion("EBD_CBC >", value, "ebdCbc");
            return (Criteria) this;
        }

        public Criteria andEbdCbcGreaterThanOrEqualTo(String value) {
            addCriterion("EBD_CBC >=", value, "ebdCbc");
            return (Criteria) this;
        }

        public Criteria andEbdCbcLessThan(String value) {
            addCriterion("EBD_CBC <", value, "ebdCbc");
            return (Criteria) this;
        }

        public Criteria andEbdCbcLessThanOrEqualTo(String value) {
            addCriterion("EBD_CBC <=", value, "ebdCbc");
            return (Criteria) this;
        }

        public Criteria andEbdCbcLike(String value) {
            addCriterion("EBD_CBC like", value, "ebdCbc");
            return (Criteria) this;
        }

        public Criteria andEbdCbcNotLike(String value) {
            addCriterion("EBD_CBC not like", value, "ebdCbc");
            return (Criteria) this;
        }

        public Criteria andEbdCbcIn(List<String> values) {
            addCriterion("EBD_CBC in", values, "ebdCbc");
            return (Criteria) this;
        }

        public Criteria andEbdCbcNotIn(List<String> values) {
            addCriterion("EBD_CBC not in", values, "ebdCbc");
            return (Criteria) this;
        }

        public Criteria andEbdCbcBetween(String value1, String value2) {
            addCriterion("EBD_CBC between", value1, value2, "ebdCbc");
            return (Criteria) this;
        }

        public Criteria andEbdCbcNotBetween(String value1, String value2) {
            addCriterion("EBD_CBC not between", value1, value2, "ebdCbc");
            return (Criteria) this;
        }

        public Criteria andEbaBasBaIsNull() {
            addCriterion("EBA_BAS_BA is null");
            return (Criteria) this;
        }

        public Criteria andEbaBasBaIsNotNull() {
            addCriterion("EBA_BAS_BA is not null");
            return (Criteria) this;
        }

        public Criteria andEbaBasBaEqualTo(String value) {
            addCriterion("EBA_BAS_BA =", value, "ebaBasBa");
            return (Criteria) this;
        }

        public Criteria andEbaBasBaNotEqualTo(String value) {
            addCriterion("EBA_BAS_BA <>", value, "ebaBasBa");
            return (Criteria) this;
        }

        public Criteria andEbaBasBaGreaterThan(String value) {
            addCriterion("EBA_BAS_BA >", value, "ebaBasBa");
            return (Criteria) this;
        }

        public Criteria andEbaBasBaGreaterThanOrEqualTo(String value) {
            addCriterion("EBA_BAS_BA >=", value, "ebaBasBa");
            return (Criteria) this;
        }

        public Criteria andEbaBasBaLessThan(String value) {
            addCriterion("EBA_BAS_BA <", value, "ebaBasBa");
            return (Criteria) this;
        }

        public Criteria andEbaBasBaLessThanOrEqualTo(String value) {
            addCriterion("EBA_BAS_BA <=", value, "ebaBasBa");
            return (Criteria) this;
        }

        public Criteria andEbaBasBaLike(String value) {
            addCriterion("EBA_BAS_BA like", value, "ebaBasBa");
            return (Criteria) this;
        }

        public Criteria andEbaBasBaNotLike(String value) {
            addCriterion("EBA_BAS_BA not like", value, "ebaBasBa");
            return (Criteria) this;
        }

        public Criteria andEbaBasBaIn(List<String> values) {
            addCriterion("EBA_BAS_BA in", values, "ebaBasBa");
            return (Criteria) this;
        }

        public Criteria andEbaBasBaNotIn(List<String> values) {
            addCriterion("EBA_BAS_BA not in", values, "ebaBasBa");
            return (Criteria) this;
        }

        public Criteria andEbaBasBaBetween(String value1, String value2) {
            addCriterion("EBA_BAS_BA between", value1, value2, "ebaBasBa");
            return (Criteria) this;
        }

        public Criteria andEbaBasBaNotBetween(String value1, String value2) {
            addCriterion("EBA_BAS_BA not between", value1, value2, "ebaBasBa");
            return (Criteria) this;
        }

        public Criteria andAsrTcsTrcIsNull() {
            addCriterion("ASR_TCS_TRC is null");
            return (Criteria) this;
        }

        public Criteria andAsrTcsTrcIsNotNull() {
            addCriterion("ASR_TCS_TRC is not null");
            return (Criteria) this;
        }

        public Criteria andAsrTcsTrcEqualTo(String value) {
            addCriterion("ASR_TCS_TRC =", value, "asrTcsTrc");
            return (Criteria) this;
        }

        public Criteria andAsrTcsTrcNotEqualTo(String value) {
            addCriterion("ASR_TCS_TRC <>", value, "asrTcsTrc");
            return (Criteria) this;
        }

        public Criteria andAsrTcsTrcGreaterThan(String value) {
            addCriterion("ASR_TCS_TRC >", value, "asrTcsTrc");
            return (Criteria) this;
        }

        public Criteria andAsrTcsTrcGreaterThanOrEqualTo(String value) {
            addCriterion("ASR_TCS_TRC >=", value, "asrTcsTrc");
            return (Criteria) this;
        }

        public Criteria andAsrTcsTrcLessThan(String value) {
            addCriterion("ASR_TCS_TRC <", value, "asrTcsTrc");
            return (Criteria) this;
        }

        public Criteria andAsrTcsTrcLessThanOrEqualTo(String value) {
            addCriterion("ASR_TCS_TRC <=", value, "asrTcsTrc");
            return (Criteria) this;
        }

        public Criteria andAsrTcsTrcLike(String value) {
            addCriterion("ASR_TCS_TRC like", value, "asrTcsTrc");
            return (Criteria) this;
        }

        public Criteria andAsrTcsTrcNotLike(String value) {
            addCriterion("ASR_TCS_TRC not like", value, "asrTcsTrc");
            return (Criteria) this;
        }

        public Criteria andAsrTcsTrcIn(List<String> values) {
            addCriterion("ASR_TCS_TRC in", values, "asrTcsTrc");
            return (Criteria) this;
        }

        public Criteria andAsrTcsTrcNotIn(List<String> values) {
            addCriterion("ASR_TCS_TRC not in", values, "asrTcsTrc");
            return (Criteria) this;
        }

        public Criteria andAsrTcsTrcBetween(String value1, String value2) {
            addCriterion("ASR_TCS_TRC between", value1, value2, "asrTcsTrc");
            return (Criteria) this;
        }

        public Criteria andAsrTcsTrcNotBetween(String value1, String value2) {
            addCriterion("ASR_TCS_TRC not between", value1, value2, "asrTcsTrc");
            return (Criteria) this;
        }

        public Criteria andHillauxiliaryIsNull() {
            addCriterion("HillAuxiliary is null");
            return (Criteria) this;
        }

        public Criteria andHillauxiliaryIsNotNull() {
            addCriterion("HillAuxiliary is not null");
            return (Criteria) this;
        }

        public Criteria andHillauxiliaryEqualTo(String value) {
            addCriterion("HillAuxiliary =", value, "hillauxiliary");
            return (Criteria) this;
        }

        public Criteria andHillauxiliaryNotEqualTo(String value) {
            addCriterion("HillAuxiliary <>", value, "hillauxiliary");
            return (Criteria) this;
        }

        public Criteria andHillauxiliaryGreaterThan(String value) {
            addCriterion("HillAuxiliary >", value, "hillauxiliary");
            return (Criteria) this;
        }

        public Criteria andHillauxiliaryGreaterThanOrEqualTo(String value) {
            addCriterion("HillAuxiliary >=", value, "hillauxiliary");
            return (Criteria) this;
        }

        public Criteria andHillauxiliaryLessThan(String value) {
            addCriterion("HillAuxiliary <", value, "hillauxiliary");
            return (Criteria) this;
        }

        public Criteria andHillauxiliaryLessThanOrEqualTo(String value) {
            addCriterion("HillAuxiliary <=", value, "hillauxiliary");
            return (Criteria) this;
        }

        public Criteria andHillauxiliaryLike(String value) {
            addCriterion("HillAuxiliary like", value, "hillauxiliary");
            return (Criteria) this;
        }

        public Criteria andHillauxiliaryNotLike(String value) {
            addCriterion("HillAuxiliary not like", value, "hillauxiliary");
            return (Criteria) this;
        }

        public Criteria andHillauxiliaryIn(List<String> values) {
            addCriterion("HillAuxiliary in", values, "hillauxiliary");
            return (Criteria) this;
        }

        public Criteria andHillauxiliaryNotIn(List<String> values) {
            addCriterion("HillAuxiliary not in", values, "hillauxiliary");
            return (Criteria) this;
        }

        public Criteria andHillauxiliaryBetween(String value1, String value2) {
            addCriterion("HillAuxiliary between", value1, value2, "hillauxiliary");
            return (Criteria) this;
        }

        public Criteria andHillauxiliaryNotBetween(String value1, String value2) {
            addCriterion("HillAuxiliary not between", value1, value2, "hillauxiliary");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingIsNull() {
            addCriterion("AutomaticParking is null");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingIsNotNull() {
            addCriterion("AutomaticParking is not null");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingEqualTo(String value) {
            addCriterion("AutomaticParking =", value, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingNotEqualTo(String value) {
            addCriterion("AutomaticParking <>", value, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingGreaterThan(String value) {
            addCriterion("AutomaticParking >", value, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingGreaterThanOrEqualTo(String value) {
            addCriterion("AutomaticParking >=", value, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingLessThan(String value) {
            addCriterion("AutomaticParking <", value, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingLessThanOrEqualTo(String value) {
            addCriterion("AutomaticParking <=", value, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingLike(String value) {
            addCriterion("AutomaticParking like", value, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingNotLike(String value) {
            addCriterion("AutomaticParking not like", value, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingIn(List<String> values) {
            addCriterion("AutomaticParking in", values, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingNotIn(List<String> values) {
            addCriterion("AutomaticParking not in", values, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingBetween(String value1, String value2) {
            addCriterion("AutomaticParking between", value1, value2, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingNotBetween(String value1, String value2) {
            addCriterion("AutomaticParking not between", value1, value2, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andHdcIsNull() {
            addCriterion("HDC is null");
            return (Criteria) this;
        }

        public Criteria andHdcIsNotNull() {
            addCriterion("HDC is not null");
            return (Criteria) this;
        }

        public Criteria andHdcEqualTo(String value) {
            addCriterion("HDC =", value, "hdc");
            return (Criteria) this;
        }

        public Criteria andHdcNotEqualTo(String value) {
            addCriterion("HDC <>", value, "hdc");
            return (Criteria) this;
        }

        public Criteria andHdcGreaterThan(String value) {
            addCriterion("HDC >", value, "hdc");
            return (Criteria) this;
        }

        public Criteria andHdcGreaterThanOrEqualTo(String value) {
            addCriterion("HDC >=", value, "hdc");
            return (Criteria) this;
        }

        public Criteria andHdcLessThan(String value) {
            addCriterion("HDC <", value, "hdc");
            return (Criteria) this;
        }

        public Criteria andHdcLessThanOrEqualTo(String value) {
            addCriterion("HDC <=", value, "hdc");
            return (Criteria) this;
        }

        public Criteria andHdcLike(String value) {
            addCriterion("HDC like", value, "hdc");
            return (Criteria) this;
        }

        public Criteria andHdcNotLike(String value) {
            addCriterion("HDC not like", value, "hdc");
            return (Criteria) this;
        }

        public Criteria andHdcIn(List<String> values) {
            addCriterion("HDC in", values, "hdc");
            return (Criteria) this;
        }

        public Criteria andHdcNotIn(List<String> values) {
            addCriterion("HDC not in", values, "hdc");
            return (Criteria) this;
        }

        public Criteria andHdcBetween(String value1, String value2) {
            addCriterion("HDC between", value1, value2, "hdc");
            return (Criteria) this;
        }

        public Criteria andHdcNotBetween(String value1, String value2) {
            addCriterion("HDC not between", value1, value2, "hdc");
            return (Criteria) this;
        }

        public Criteria andVariablesuspensionIsNull() {
            addCriterion("VariableSuspension is null");
            return (Criteria) this;
        }

        public Criteria andVariablesuspensionIsNotNull() {
            addCriterion("VariableSuspension is not null");
            return (Criteria) this;
        }

        public Criteria andVariablesuspensionEqualTo(String value) {
            addCriterion("VariableSuspension =", value, "variablesuspension");
            return (Criteria) this;
        }

        public Criteria andVariablesuspensionNotEqualTo(String value) {
            addCriterion("VariableSuspension <>", value, "variablesuspension");
            return (Criteria) this;
        }

        public Criteria andVariablesuspensionGreaterThan(String value) {
            addCriterion("VariableSuspension >", value, "variablesuspension");
            return (Criteria) this;
        }

        public Criteria andVariablesuspensionGreaterThanOrEqualTo(String value) {
            addCriterion("VariableSuspension >=", value, "variablesuspension");
            return (Criteria) this;
        }

        public Criteria andVariablesuspensionLessThan(String value) {
            addCriterion("VariableSuspension <", value, "variablesuspension");
            return (Criteria) this;
        }

        public Criteria andVariablesuspensionLessThanOrEqualTo(String value) {
            addCriterion("VariableSuspension <=", value, "variablesuspension");
            return (Criteria) this;
        }

        public Criteria andVariablesuspensionLike(String value) {
            addCriterion("VariableSuspension like", value, "variablesuspension");
            return (Criteria) this;
        }

        public Criteria andVariablesuspensionNotLike(String value) {
            addCriterion("VariableSuspension not like", value, "variablesuspension");
            return (Criteria) this;
        }

        public Criteria andVariablesuspensionIn(List<String> values) {
            addCriterion("VariableSuspension in", values, "variablesuspension");
            return (Criteria) this;
        }

        public Criteria andVariablesuspensionNotIn(List<String> values) {
            addCriterion("VariableSuspension not in", values, "variablesuspension");
            return (Criteria) this;
        }

        public Criteria andVariablesuspensionBetween(String value1, String value2) {
            addCriterion("VariableSuspension between", value1, value2, "variablesuspension");
            return (Criteria) this;
        }

        public Criteria andVariablesuspensionNotBetween(String value1, String value2) {
            addCriterion("VariableSuspension not between", value1, value2, "variablesuspension");
            return (Criteria) this;
        }

        public Criteria andAirsuspensionIsNull() {
            addCriterion("AirSuspension is null");
            return (Criteria) this;
        }

        public Criteria andAirsuspensionIsNotNull() {
            addCriterion("AirSuspension is not null");
            return (Criteria) this;
        }

        public Criteria andAirsuspensionEqualTo(String value) {
            addCriterion("AirSuspension =", value, "airsuspension");
            return (Criteria) this;
        }

        public Criteria andAirsuspensionNotEqualTo(String value) {
            addCriterion("AirSuspension <>", value, "airsuspension");
            return (Criteria) this;
        }

        public Criteria andAirsuspensionGreaterThan(String value) {
            addCriterion("AirSuspension >", value, "airsuspension");
            return (Criteria) this;
        }

        public Criteria andAirsuspensionGreaterThanOrEqualTo(String value) {
            addCriterion("AirSuspension >=", value, "airsuspension");
            return (Criteria) this;
        }

        public Criteria andAirsuspensionLessThan(String value) {
            addCriterion("AirSuspension <", value, "airsuspension");
            return (Criteria) this;
        }

        public Criteria andAirsuspensionLessThanOrEqualTo(String value) {
            addCriterion("AirSuspension <=", value, "airsuspension");
            return (Criteria) this;
        }

        public Criteria andAirsuspensionLike(String value) {
            addCriterion("AirSuspension like", value, "airsuspension");
            return (Criteria) this;
        }

        public Criteria andAirsuspensionNotLike(String value) {
            addCriterion("AirSuspension not like", value, "airsuspension");
            return (Criteria) this;
        }

        public Criteria andAirsuspensionIn(List<String> values) {
            addCriterion("AirSuspension in", values, "airsuspension");
            return (Criteria) this;
        }

        public Criteria andAirsuspensionNotIn(List<String> values) {
            addCriterion("AirSuspension not in", values, "airsuspension");
            return (Criteria) this;
        }

        public Criteria andAirsuspensionBetween(String value1, String value2) {
            addCriterion("AirSuspension between", value1, value2, "airsuspension");
            return (Criteria) this;
        }

        public Criteria andAirsuspensionNotBetween(String value1, String value2) {
            addCriterion("AirSuspension not between", value1, value2, "airsuspension");
            return (Criteria) this;
        }

        public Criteria andVariablesteeringratioIsNull() {
            addCriterion("VariableSteeringRatio is null");
            return (Criteria) this;
        }

        public Criteria andVariablesteeringratioIsNotNull() {
            addCriterion("VariableSteeringRatio is not null");
            return (Criteria) this;
        }

        public Criteria andVariablesteeringratioEqualTo(String value) {
            addCriterion("VariableSteeringRatio =", value, "variablesteeringratio");
            return (Criteria) this;
        }

        public Criteria andVariablesteeringratioNotEqualTo(String value) {
            addCriterion("VariableSteeringRatio <>", value, "variablesteeringratio");
            return (Criteria) this;
        }

        public Criteria andVariablesteeringratioGreaterThan(String value) {
            addCriterion("VariableSteeringRatio >", value, "variablesteeringratio");
            return (Criteria) this;
        }

        public Criteria andVariablesteeringratioGreaterThanOrEqualTo(String value) {
            addCriterion("VariableSteeringRatio >=", value, "variablesteeringratio");
            return (Criteria) this;
        }

        public Criteria andVariablesteeringratioLessThan(String value) {
            addCriterion("VariableSteeringRatio <", value, "variablesteeringratio");
            return (Criteria) this;
        }

        public Criteria andVariablesteeringratioLessThanOrEqualTo(String value) {
            addCriterion("VariableSteeringRatio <=", value, "variablesteeringratio");
            return (Criteria) this;
        }

        public Criteria andVariablesteeringratioLike(String value) {
            addCriterion("VariableSteeringRatio like", value, "variablesteeringratio");
            return (Criteria) this;
        }

        public Criteria andVariablesteeringratioNotLike(String value) {
            addCriterion("VariableSteeringRatio not like", value, "variablesteeringratio");
            return (Criteria) this;
        }

        public Criteria andVariablesteeringratioIn(List<String> values) {
            addCriterion("VariableSteeringRatio in", values, "variablesteeringratio");
            return (Criteria) this;
        }

        public Criteria andVariablesteeringratioNotIn(List<String> values) {
            addCriterion("VariableSteeringRatio not in", values, "variablesteeringratio");
            return (Criteria) this;
        }

        public Criteria andVariablesteeringratioBetween(String value1, String value2) {
            addCriterion("VariableSteeringRatio between", value1, value2, "variablesteeringratio");
            return (Criteria) this;
        }

        public Criteria andVariablesteeringratioNotBetween(String value1, String value2) {
            addCriterion("VariableSteeringRatio not between", value1, value2, "variablesteeringratio");
            return (Criteria) this;
        }

        public Criteria andFrontaxlelimitedslipdifferentialDifferentiallockIsNull() {
            addCriterion("FrontAxleLimitedSlipDifferential_differentialLock is null");
            return (Criteria) this;
        }

        public Criteria andFrontaxlelimitedslipdifferentialDifferentiallockIsNotNull() {
            addCriterion("FrontAxleLimitedSlipDifferential_differentialLock is not null");
            return (Criteria) this;
        }

        public Criteria andFrontaxlelimitedslipdifferentialDifferentiallockEqualTo(String value) {
            addCriterion("FrontAxleLimitedSlipDifferential_differentialLock =", value, "frontaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andFrontaxlelimitedslipdifferentialDifferentiallockNotEqualTo(String value) {
            addCriterion("FrontAxleLimitedSlipDifferential_differentialLock <>", value, "frontaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andFrontaxlelimitedslipdifferentialDifferentiallockGreaterThan(String value) {
            addCriterion("FrontAxleLimitedSlipDifferential_differentialLock >", value, "frontaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andFrontaxlelimitedslipdifferentialDifferentiallockGreaterThanOrEqualTo(String value) {
            addCriterion("FrontAxleLimitedSlipDifferential_differentialLock >=", value, "frontaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andFrontaxlelimitedslipdifferentialDifferentiallockLessThan(String value) {
            addCriterion("FrontAxleLimitedSlipDifferential_differentialLock <", value, "frontaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andFrontaxlelimitedslipdifferentialDifferentiallockLessThanOrEqualTo(String value) {
            addCriterion("FrontAxleLimitedSlipDifferential_differentialLock <=", value, "frontaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andFrontaxlelimitedslipdifferentialDifferentiallockLike(String value) {
            addCriterion("FrontAxleLimitedSlipDifferential_differentialLock like", value, "frontaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andFrontaxlelimitedslipdifferentialDifferentiallockNotLike(String value) {
            addCriterion("FrontAxleLimitedSlipDifferential_differentialLock not like", value, "frontaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andFrontaxlelimitedslipdifferentialDifferentiallockIn(List<String> values) {
            addCriterion("FrontAxleLimitedSlipDifferential_differentialLock in", values, "frontaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andFrontaxlelimitedslipdifferentialDifferentiallockNotIn(List<String> values) {
            addCriterion("FrontAxleLimitedSlipDifferential_differentialLock not in", values, "frontaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andFrontaxlelimitedslipdifferentialDifferentiallockBetween(String value1, String value2) {
            addCriterion("FrontAxleLimitedSlipDifferential_differentialLock between", value1, value2, "frontaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andFrontaxlelimitedslipdifferentialDifferentiallockNotBetween(String value1, String value2) {
            addCriterion("FrontAxleLimitedSlipDifferential_differentialLock not between", value1, value2, "frontaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andCentraldifferentiallockingfunctionIsNull() {
            addCriterion("CentralDifferentialLockingFunction is null");
            return (Criteria) this;
        }

        public Criteria andCentraldifferentiallockingfunctionIsNotNull() {
            addCriterion("CentralDifferentialLockingFunction is not null");
            return (Criteria) this;
        }

        public Criteria andCentraldifferentiallockingfunctionEqualTo(String value) {
            addCriterion("CentralDifferentialLockingFunction =", value, "centraldifferentiallockingfunction");
            return (Criteria) this;
        }

        public Criteria andCentraldifferentiallockingfunctionNotEqualTo(String value) {
            addCriterion("CentralDifferentialLockingFunction <>", value, "centraldifferentiallockingfunction");
            return (Criteria) this;
        }

        public Criteria andCentraldifferentiallockingfunctionGreaterThan(String value) {
            addCriterion("CentralDifferentialLockingFunction >", value, "centraldifferentiallockingfunction");
            return (Criteria) this;
        }

        public Criteria andCentraldifferentiallockingfunctionGreaterThanOrEqualTo(String value) {
            addCriterion("CentralDifferentialLockingFunction >=", value, "centraldifferentiallockingfunction");
            return (Criteria) this;
        }

        public Criteria andCentraldifferentiallockingfunctionLessThan(String value) {
            addCriterion("CentralDifferentialLockingFunction <", value, "centraldifferentiallockingfunction");
            return (Criteria) this;
        }

        public Criteria andCentraldifferentiallockingfunctionLessThanOrEqualTo(String value) {
            addCriterion("CentralDifferentialLockingFunction <=", value, "centraldifferentiallockingfunction");
            return (Criteria) this;
        }

        public Criteria andCentraldifferentiallockingfunctionLike(String value) {
            addCriterion("CentralDifferentialLockingFunction like", value, "centraldifferentiallockingfunction");
            return (Criteria) this;
        }

        public Criteria andCentraldifferentiallockingfunctionNotLike(String value) {
            addCriterion("CentralDifferentialLockingFunction not like", value, "centraldifferentiallockingfunction");
            return (Criteria) this;
        }

        public Criteria andCentraldifferentiallockingfunctionIn(List<String> values) {
            addCriterion("CentralDifferentialLockingFunction in", values, "centraldifferentiallockingfunction");
            return (Criteria) this;
        }

        public Criteria andCentraldifferentiallockingfunctionNotIn(List<String> values) {
            addCriterion("CentralDifferentialLockingFunction not in", values, "centraldifferentiallockingfunction");
            return (Criteria) this;
        }

        public Criteria andCentraldifferentiallockingfunctionBetween(String value1, String value2) {
            addCriterion("CentralDifferentialLockingFunction between", value1, value2, "centraldifferentiallockingfunction");
            return (Criteria) this;
        }

        public Criteria andCentraldifferentiallockingfunctionNotBetween(String value1, String value2) {
            addCriterion("CentralDifferentialLockingFunction not between", value1, value2, "centraldifferentiallockingfunction");
            return (Criteria) this;
        }

        public Criteria andRearaxlelimitedslipdifferentialDifferentiallockIsNull() {
            addCriterion("RearAxleLimitedSlipDifferential_differentialLock is null");
            return (Criteria) this;
        }

        public Criteria andRearaxlelimitedslipdifferentialDifferentiallockIsNotNull() {
            addCriterion("RearAxleLimitedSlipDifferential_differentialLock is not null");
            return (Criteria) this;
        }

        public Criteria andRearaxlelimitedslipdifferentialDifferentiallockEqualTo(String value) {
            addCriterion("RearAxleLimitedSlipDifferential_differentialLock =", value, "rearaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andRearaxlelimitedslipdifferentialDifferentiallockNotEqualTo(String value) {
            addCriterion("RearAxleLimitedSlipDifferential_differentialLock <>", value, "rearaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andRearaxlelimitedslipdifferentialDifferentiallockGreaterThan(String value) {
            addCriterion("RearAxleLimitedSlipDifferential_differentialLock >", value, "rearaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andRearaxlelimitedslipdifferentialDifferentiallockGreaterThanOrEqualTo(String value) {
            addCriterion("RearAxleLimitedSlipDifferential_differentialLock >=", value, "rearaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andRearaxlelimitedslipdifferentialDifferentiallockLessThan(String value) {
            addCriterion("RearAxleLimitedSlipDifferential_differentialLock <", value, "rearaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andRearaxlelimitedslipdifferentialDifferentiallockLessThanOrEqualTo(String value) {
            addCriterion("RearAxleLimitedSlipDifferential_differentialLock <=", value, "rearaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andRearaxlelimitedslipdifferentialDifferentiallockLike(String value) {
            addCriterion("RearAxleLimitedSlipDifferential_differentialLock like", value, "rearaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andRearaxlelimitedslipdifferentialDifferentiallockNotLike(String value) {
            addCriterion("RearAxleLimitedSlipDifferential_differentialLock not like", value, "rearaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andRearaxlelimitedslipdifferentialDifferentiallockIn(List<String> values) {
            addCriterion("RearAxleLimitedSlipDifferential_differentialLock in", values, "rearaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andRearaxlelimitedslipdifferentialDifferentiallockNotIn(List<String> values) {
            addCriterion("RearAxleLimitedSlipDifferential_differentialLock not in", values, "rearaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andRearaxlelimitedslipdifferentialDifferentiallockBetween(String value1, String value2) {
            addCriterion("RearAxleLimitedSlipDifferential_differentialLock between", value1, value2, "rearaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }

        public Criteria andRearaxlelimitedslipdifferentialDifferentiallockNotBetween(String value1, String value2) {
            addCriterion("RearAxleLimitedSlipDifferential_differentialLock not between", value1, value2, "rearaxlelimitedslipdifferentialDifferentiallock");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table control_configuration
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table control_configuration
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}