package com.car.pojo;

import java.util.ArrayList;
import java.util.List;

public class External_configurationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    public External_configurationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNumIsNull() {
            addCriterion("Num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("Num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("Num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("Num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("Num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("Num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("Num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("Num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("Num like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("Num not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("Num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("Num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("Num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("Num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andPowersunroofIsNull() {
            addCriterion("PowerSunroof is null");
            return (Criteria) this;
        }

        public Criteria andPowersunroofIsNotNull() {
            addCriterion("PowerSunroof is not null");
            return (Criteria) this;
        }

        public Criteria andPowersunroofEqualTo(String value) {
            addCriterion("PowerSunroof =", value, "powersunroof");
            return (Criteria) this;
        }

        public Criteria andPowersunroofNotEqualTo(String value) {
            addCriterion("PowerSunroof <>", value, "powersunroof");
            return (Criteria) this;
        }

        public Criteria andPowersunroofGreaterThan(String value) {
            addCriterion("PowerSunroof >", value, "powersunroof");
            return (Criteria) this;
        }

        public Criteria andPowersunroofGreaterThanOrEqualTo(String value) {
            addCriterion("PowerSunroof >=", value, "powersunroof");
            return (Criteria) this;
        }

        public Criteria andPowersunroofLessThan(String value) {
            addCriterion("PowerSunroof <", value, "powersunroof");
            return (Criteria) this;
        }

        public Criteria andPowersunroofLessThanOrEqualTo(String value) {
            addCriterion("PowerSunroof <=", value, "powersunroof");
            return (Criteria) this;
        }

        public Criteria andPowersunroofLike(String value) {
            addCriterion("PowerSunroof like", value, "powersunroof");
            return (Criteria) this;
        }

        public Criteria andPowersunroofNotLike(String value) {
            addCriterion("PowerSunroof not like", value, "powersunroof");
            return (Criteria) this;
        }

        public Criteria andPowersunroofIn(List<String> values) {
            addCriterion("PowerSunroof in", values, "powersunroof");
            return (Criteria) this;
        }

        public Criteria andPowersunroofNotIn(List<String> values) {
            addCriterion("PowerSunroof not in", values, "powersunroof");
            return (Criteria) this;
        }

        public Criteria andPowersunroofBetween(String value1, String value2) {
            addCriterion("PowerSunroof between", value1, value2, "powersunroof");
            return (Criteria) this;
        }

        public Criteria andPowersunroofNotBetween(String value1, String value2) {
            addCriterion("PowerSunroof not between", value1, value2, "powersunroof");
            return (Criteria) this;
        }

        public Criteria andPanoramicsunroofIsNull() {
            addCriterion("PanoramicSunroof is null");
            return (Criteria) this;
        }

        public Criteria andPanoramicsunroofIsNotNull() {
            addCriterion("PanoramicSunroof is not null");
            return (Criteria) this;
        }

        public Criteria andPanoramicsunroofEqualTo(String value) {
            addCriterion("PanoramicSunroof =", value, "panoramicsunroof");
            return (Criteria) this;
        }

        public Criteria andPanoramicsunroofNotEqualTo(String value) {
            addCriterion("PanoramicSunroof <>", value, "panoramicsunroof");
            return (Criteria) this;
        }

        public Criteria andPanoramicsunroofGreaterThan(String value) {
            addCriterion("PanoramicSunroof >", value, "panoramicsunroof");
            return (Criteria) this;
        }

        public Criteria andPanoramicsunroofGreaterThanOrEqualTo(String value) {
            addCriterion("PanoramicSunroof >=", value, "panoramicsunroof");
            return (Criteria) this;
        }

        public Criteria andPanoramicsunroofLessThan(String value) {
            addCriterion("PanoramicSunroof <", value, "panoramicsunroof");
            return (Criteria) this;
        }

        public Criteria andPanoramicsunroofLessThanOrEqualTo(String value) {
            addCriterion("PanoramicSunroof <=", value, "panoramicsunroof");
            return (Criteria) this;
        }

        public Criteria andPanoramicsunroofLike(String value) {
            addCriterion("PanoramicSunroof like", value, "panoramicsunroof");
            return (Criteria) this;
        }

        public Criteria andPanoramicsunroofNotLike(String value) {
            addCriterion("PanoramicSunroof not like", value, "panoramicsunroof");
            return (Criteria) this;
        }

        public Criteria andPanoramicsunroofIn(List<String> values) {
            addCriterion("PanoramicSunroof in", values, "panoramicsunroof");
            return (Criteria) this;
        }

        public Criteria andPanoramicsunroofNotIn(List<String> values) {
            addCriterion("PanoramicSunroof not in", values, "panoramicsunroof");
            return (Criteria) this;
        }

        public Criteria andPanoramicsunroofBetween(String value1, String value2) {
            addCriterion("PanoramicSunroof between", value1, value2, "panoramicsunroof");
            return (Criteria) this;
        }

        public Criteria andPanoramicsunroofNotBetween(String value1, String value2) {
            addCriterion("PanoramicSunroof not between", value1, value2, "panoramicsunroof");
            return (Criteria) this;
        }

        public Criteria andSportsappearancesuiteIsNull() {
            addCriterion("SportsAppearanceSuite is null");
            return (Criteria) this;
        }

        public Criteria andSportsappearancesuiteIsNotNull() {
            addCriterion("SportsAppearanceSuite is not null");
            return (Criteria) this;
        }

        public Criteria andSportsappearancesuiteEqualTo(String value) {
            addCriterion("SportsAppearanceSuite =", value, "sportsappearancesuite");
            return (Criteria) this;
        }

        public Criteria andSportsappearancesuiteNotEqualTo(String value) {
            addCriterion("SportsAppearanceSuite <>", value, "sportsappearancesuite");
            return (Criteria) this;
        }

        public Criteria andSportsappearancesuiteGreaterThan(String value) {
            addCriterion("SportsAppearanceSuite >", value, "sportsappearancesuite");
            return (Criteria) this;
        }

        public Criteria andSportsappearancesuiteGreaterThanOrEqualTo(String value) {
            addCriterion("SportsAppearanceSuite >=", value, "sportsappearancesuite");
            return (Criteria) this;
        }

        public Criteria andSportsappearancesuiteLessThan(String value) {
            addCriterion("SportsAppearanceSuite <", value, "sportsappearancesuite");
            return (Criteria) this;
        }

        public Criteria andSportsappearancesuiteLessThanOrEqualTo(String value) {
            addCriterion("SportsAppearanceSuite <=", value, "sportsappearancesuite");
            return (Criteria) this;
        }

        public Criteria andSportsappearancesuiteLike(String value) {
            addCriterion("SportsAppearanceSuite like", value, "sportsappearancesuite");
            return (Criteria) this;
        }

        public Criteria andSportsappearancesuiteNotLike(String value) {
            addCriterion("SportsAppearanceSuite not like", value, "sportsappearancesuite");
            return (Criteria) this;
        }

        public Criteria andSportsappearancesuiteIn(List<String> values) {
            addCriterion("SportsAppearanceSuite in", values, "sportsappearancesuite");
            return (Criteria) this;
        }

        public Criteria andSportsappearancesuiteNotIn(List<String> values) {
            addCriterion("SportsAppearanceSuite not in", values, "sportsappearancesuite");
            return (Criteria) this;
        }

        public Criteria andSportsappearancesuiteBetween(String value1, String value2) {
            addCriterion("SportsAppearanceSuite between", value1, value2, "sportsappearancesuite");
            return (Criteria) this;
        }

        public Criteria andSportsappearancesuiteNotBetween(String value1, String value2) {
            addCriterion("SportsAppearanceSuite not between", value1, value2, "sportsappearancesuite");
            return (Criteria) this;
        }

        public Criteria andAluminiumalloyrimIsNull() {
            addCriterion("AluminiumAlloyRim is null");
            return (Criteria) this;
        }

        public Criteria andAluminiumalloyrimIsNotNull() {
            addCriterion("AluminiumAlloyRim is not null");
            return (Criteria) this;
        }

        public Criteria andAluminiumalloyrimEqualTo(String value) {
            addCriterion("AluminiumAlloyRim =", value, "aluminiumalloyrim");
            return (Criteria) this;
        }

        public Criteria andAluminiumalloyrimNotEqualTo(String value) {
            addCriterion("AluminiumAlloyRim <>", value, "aluminiumalloyrim");
            return (Criteria) this;
        }

        public Criteria andAluminiumalloyrimGreaterThan(String value) {
            addCriterion("AluminiumAlloyRim >", value, "aluminiumalloyrim");
            return (Criteria) this;
        }

        public Criteria andAluminiumalloyrimGreaterThanOrEqualTo(String value) {
            addCriterion("AluminiumAlloyRim >=", value, "aluminiumalloyrim");
            return (Criteria) this;
        }

        public Criteria andAluminiumalloyrimLessThan(String value) {
            addCriterion("AluminiumAlloyRim <", value, "aluminiumalloyrim");
            return (Criteria) this;
        }

        public Criteria andAluminiumalloyrimLessThanOrEqualTo(String value) {
            addCriterion("AluminiumAlloyRim <=", value, "aluminiumalloyrim");
            return (Criteria) this;
        }

        public Criteria andAluminiumalloyrimLike(String value) {
            addCriterion("AluminiumAlloyRim like", value, "aluminiumalloyrim");
            return (Criteria) this;
        }

        public Criteria andAluminiumalloyrimNotLike(String value) {
            addCriterion("AluminiumAlloyRim not like", value, "aluminiumalloyrim");
            return (Criteria) this;
        }

        public Criteria andAluminiumalloyrimIn(List<String> values) {
            addCriterion("AluminiumAlloyRim in", values, "aluminiumalloyrim");
            return (Criteria) this;
        }

        public Criteria andAluminiumalloyrimNotIn(List<String> values) {
            addCriterion("AluminiumAlloyRim not in", values, "aluminiumalloyrim");
            return (Criteria) this;
        }

        public Criteria andAluminiumalloyrimBetween(String value1, String value2) {
            addCriterion("AluminiumAlloyRim between", value1, value2, "aluminiumalloyrim");
            return (Criteria) this;
        }

        public Criteria andAluminiumalloyrimNotBetween(String value1, String value2) {
            addCriterion("AluminiumAlloyRim not between", value1, value2, "aluminiumalloyrim");
            return (Criteria) this;
        }

        public Criteria andElectricsuctiondoorIsNull() {
            addCriterion("ElectricSuctionDoor is null");
            return (Criteria) this;
        }

        public Criteria andElectricsuctiondoorIsNotNull() {
            addCriterion("ElectricSuctionDoor is not null");
            return (Criteria) this;
        }

        public Criteria andElectricsuctiondoorEqualTo(String value) {
            addCriterion("ElectricSuctionDoor =", value, "electricsuctiondoor");
            return (Criteria) this;
        }

        public Criteria andElectricsuctiondoorNotEqualTo(String value) {
            addCriterion("ElectricSuctionDoor <>", value, "electricsuctiondoor");
            return (Criteria) this;
        }

        public Criteria andElectricsuctiondoorGreaterThan(String value) {
            addCriterion("ElectricSuctionDoor >", value, "electricsuctiondoor");
            return (Criteria) this;
        }

        public Criteria andElectricsuctiondoorGreaterThanOrEqualTo(String value) {
            addCriterion("ElectricSuctionDoor >=", value, "electricsuctiondoor");
            return (Criteria) this;
        }

        public Criteria andElectricsuctiondoorLessThan(String value) {
            addCriterion("ElectricSuctionDoor <", value, "electricsuctiondoor");
            return (Criteria) this;
        }

        public Criteria andElectricsuctiondoorLessThanOrEqualTo(String value) {
            addCriterion("ElectricSuctionDoor <=", value, "electricsuctiondoor");
            return (Criteria) this;
        }

        public Criteria andElectricsuctiondoorLike(String value) {
            addCriterion("ElectricSuctionDoor like", value, "electricsuctiondoor");
            return (Criteria) this;
        }

        public Criteria andElectricsuctiondoorNotLike(String value) {
            addCriterion("ElectricSuctionDoor not like", value, "electricsuctiondoor");
            return (Criteria) this;
        }

        public Criteria andElectricsuctiondoorIn(List<String> values) {
            addCriterion("ElectricSuctionDoor in", values, "electricsuctiondoor");
            return (Criteria) this;
        }

        public Criteria andElectricsuctiondoorNotIn(List<String> values) {
            addCriterion("ElectricSuctionDoor not in", values, "electricsuctiondoor");
            return (Criteria) this;
        }

        public Criteria andElectricsuctiondoorBetween(String value1, String value2) {
            addCriterion("ElectricSuctionDoor between", value1, value2, "electricsuctiondoor");
            return (Criteria) this;
        }

        public Criteria andElectricsuctiondoorNotBetween(String value1, String value2) {
            addCriterion("ElectricSuctionDoor not between", value1, value2, "electricsuctiondoor");
            return (Criteria) this;
        }

        public Criteria andSlidingdoorIsNull() {
            addCriterion("SlidingDoor is null");
            return (Criteria) this;
        }

        public Criteria andSlidingdoorIsNotNull() {
            addCriterion("SlidingDoor is not null");
            return (Criteria) this;
        }

        public Criteria andSlidingdoorEqualTo(String value) {
            addCriterion("SlidingDoor =", value, "slidingdoor");
            return (Criteria) this;
        }

        public Criteria andSlidingdoorNotEqualTo(String value) {
            addCriterion("SlidingDoor <>", value, "slidingdoor");
            return (Criteria) this;
        }

        public Criteria andSlidingdoorGreaterThan(String value) {
            addCriterion("SlidingDoor >", value, "slidingdoor");
            return (Criteria) this;
        }

        public Criteria andSlidingdoorGreaterThanOrEqualTo(String value) {
            addCriterion("SlidingDoor >=", value, "slidingdoor");
            return (Criteria) this;
        }

        public Criteria andSlidingdoorLessThan(String value) {
            addCriterion("SlidingDoor <", value, "slidingdoor");
            return (Criteria) this;
        }

        public Criteria andSlidingdoorLessThanOrEqualTo(String value) {
            addCriterion("SlidingDoor <=", value, "slidingdoor");
            return (Criteria) this;
        }

        public Criteria andSlidingdoorLike(String value) {
            addCriterion("SlidingDoor like", value, "slidingdoor");
            return (Criteria) this;
        }

        public Criteria andSlidingdoorNotLike(String value) {
            addCriterion("SlidingDoor not like", value, "slidingdoor");
            return (Criteria) this;
        }

        public Criteria andSlidingdoorIn(List<String> values) {
            addCriterion("SlidingDoor in", values, "slidingdoor");
            return (Criteria) this;
        }

        public Criteria andSlidingdoorNotIn(List<String> values) {
            addCriterion("SlidingDoor not in", values, "slidingdoor");
            return (Criteria) this;
        }

        public Criteria andSlidingdoorBetween(String value1, String value2) {
            addCriterion("SlidingDoor between", value1, value2, "slidingdoor");
            return (Criteria) this;
        }

        public Criteria andSlidingdoorNotBetween(String value1, String value2) {
            addCriterion("SlidingDoor not between", value1, value2, "slidingdoor");
            return (Criteria) this;
        }

        public Criteria andElectrictrunkIsNull() {
            addCriterion("ElectricTrunk is null");
            return (Criteria) this;
        }

        public Criteria andElectrictrunkIsNotNull() {
            addCriterion("ElectricTrunk is not null");
            return (Criteria) this;
        }

        public Criteria andElectrictrunkEqualTo(String value) {
            addCriterion("ElectricTrunk =", value, "electrictrunk");
            return (Criteria) this;
        }

        public Criteria andElectrictrunkNotEqualTo(String value) {
            addCriterion("ElectricTrunk <>", value, "electrictrunk");
            return (Criteria) this;
        }

        public Criteria andElectrictrunkGreaterThan(String value) {
            addCriterion("ElectricTrunk >", value, "electrictrunk");
            return (Criteria) this;
        }

        public Criteria andElectrictrunkGreaterThanOrEqualTo(String value) {
            addCriterion("ElectricTrunk >=", value, "electrictrunk");
            return (Criteria) this;
        }

        public Criteria andElectrictrunkLessThan(String value) {
            addCriterion("ElectricTrunk <", value, "electrictrunk");
            return (Criteria) this;
        }

        public Criteria andElectrictrunkLessThanOrEqualTo(String value) {
            addCriterion("ElectricTrunk <=", value, "electrictrunk");
            return (Criteria) this;
        }

        public Criteria andElectrictrunkLike(String value) {
            addCriterion("ElectricTrunk like", value, "electrictrunk");
            return (Criteria) this;
        }

        public Criteria andElectrictrunkNotLike(String value) {
            addCriterion("ElectricTrunk not like", value, "electrictrunk");
            return (Criteria) this;
        }

        public Criteria andElectrictrunkIn(List<String> values) {
            addCriterion("ElectricTrunk in", values, "electrictrunk");
            return (Criteria) this;
        }

        public Criteria andElectrictrunkNotIn(List<String> values) {
            addCriterion("ElectricTrunk not in", values, "electrictrunk");
            return (Criteria) this;
        }

        public Criteria andElectrictrunkBetween(String value1, String value2) {
            addCriterion("ElectricTrunk between", value1, value2, "electrictrunk");
            return (Criteria) this;
        }

        public Criteria andElectrictrunkNotBetween(String value1, String value2) {
            addCriterion("ElectricTrunk not between", value1, value2, "electrictrunk");
            return (Criteria) this;
        }

        public Criteria andInductiontrunkIsNull() {
            addCriterion("InductionTrunk is null");
            return (Criteria) this;
        }

        public Criteria andInductiontrunkIsNotNull() {
            addCriterion("InductionTrunk is not null");
            return (Criteria) this;
        }

        public Criteria andInductiontrunkEqualTo(String value) {
            addCriterion("InductionTrunk =", value, "inductiontrunk");
            return (Criteria) this;
        }

        public Criteria andInductiontrunkNotEqualTo(String value) {
            addCriterion("InductionTrunk <>", value, "inductiontrunk");
            return (Criteria) this;
        }

        public Criteria andInductiontrunkGreaterThan(String value) {
            addCriterion("InductionTrunk >", value, "inductiontrunk");
            return (Criteria) this;
        }

        public Criteria andInductiontrunkGreaterThanOrEqualTo(String value) {
            addCriterion("InductionTrunk >=", value, "inductiontrunk");
            return (Criteria) this;
        }

        public Criteria andInductiontrunkLessThan(String value) {
            addCriterion("InductionTrunk <", value, "inductiontrunk");
            return (Criteria) this;
        }

        public Criteria andInductiontrunkLessThanOrEqualTo(String value) {
            addCriterion("InductionTrunk <=", value, "inductiontrunk");
            return (Criteria) this;
        }

        public Criteria andInductiontrunkLike(String value) {
            addCriterion("InductionTrunk like", value, "inductiontrunk");
            return (Criteria) this;
        }

        public Criteria andInductiontrunkNotLike(String value) {
            addCriterion("InductionTrunk not like", value, "inductiontrunk");
            return (Criteria) this;
        }

        public Criteria andInductiontrunkIn(List<String> values) {
            addCriterion("InductionTrunk in", values, "inductiontrunk");
            return (Criteria) this;
        }

        public Criteria andInductiontrunkNotIn(List<String> values) {
            addCriterion("InductionTrunk not in", values, "inductiontrunk");
            return (Criteria) this;
        }

        public Criteria andInductiontrunkBetween(String value1, String value2) {
            addCriterion("InductionTrunk between", value1, value2, "inductiontrunk");
            return (Criteria) this;
        }

        public Criteria andInductiontrunkNotBetween(String value1, String value2) {
            addCriterion("InductionTrunk not between", value1, value2, "inductiontrunk");
            return (Criteria) this;
        }

        public Criteria andRoofrackIsNull() {
            addCriterion("RoofRack is null");
            return (Criteria) this;
        }

        public Criteria andRoofrackIsNotNull() {
            addCriterion("RoofRack is not null");
            return (Criteria) this;
        }

        public Criteria andRoofrackEqualTo(String value) {
            addCriterion("RoofRack =", value, "roofrack");
            return (Criteria) this;
        }

        public Criteria andRoofrackNotEqualTo(String value) {
            addCriterion("RoofRack <>", value, "roofrack");
            return (Criteria) this;
        }

        public Criteria andRoofrackGreaterThan(String value) {
            addCriterion("RoofRack >", value, "roofrack");
            return (Criteria) this;
        }

        public Criteria andRoofrackGreaterThanOrEqualTo(String value) {
            addCriterion("RoofRack >=", value, "roofrack");
            return (Criteria) this;
        }

        public Criteria andRoofrackLessThan(String value) {
            addCriterion("RoofRack <", value, "roofrack");
            return (Criteria) this;
        }

        public Criteria andRoofrackLessThanOrEqualTo(String value) {
            addCriterion("RoofRack <=", value, "roofrack");
            return (Criteria) this;
        }

        public Criteria andRoofrackLike(String value) {
            addCriterion("RoofRack like", value, "roofrack");
            return (Criteria) this;
        }

        public Criteria andRoofrackNotLike(String value) {
            addCriterion("RoofRack not like", value, "roofrack");
            return (Criteria) this;
        }

        public Criteria andRoofrackIn(List<String> values) {
            addCriterion("RoofRack in", values, "roofrack");
            return (Criteria) this;
        }

        public Criteria andRoofrackNotIn(List<String> values) {
            addCriterion("RoofRack not in", values, "roofrack");
            return (Criteria) this;
        }

        public Criteria andRoofrackBetween(String value1, String value2) {
            addCriterion("RoofRack between", value1, value2, "roofrack");
            return (Criteria) this;
        }

        public Criteria andRoofrackNotBetween(String value1, String value2) {
            addCriterion("RoofRack not between", value1, value2, "roofrack");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table external_configuration
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table external_configuration
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}