package com.car.pojo;

import java.util.ArrayList;
import java.util.List;

public class High_tech_configurationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    public High_tech_configurationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNumIsNull() {
            addCriterion("Num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("Num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("Num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("Num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("Num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("Num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("Num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("Num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("Num like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("Num not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("Num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("Num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("Num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("Num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingIsNull() {
            addCriterion("AutomaticParking is null");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingIsNotNull() {
            addCriterion("AutomaticParking is not null");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingEqualTo(String value) {
            addCriterion("AutomaticParking =", value, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingNotEqualTo(String value) {
            addCriterion("AutomaticParking <>", value, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingGreaterThan(String value) {
            addCriterion("AutomaticParking >", value, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingGreaterThanOrEqualTo(String value) {
            addCriterion("AutomaticParking >=", value, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingLessThan(String value) {
            addCriterion("AutomaticParking <", value, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingLessThanOrEqualTo(String value) {
            addCriterion("AutomaticParking <=", value, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingLike(String value) {
            addCriterion("AutomaticParking like", value, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingNotLike(String value) {
            addCriterion("AutomaticParking not like", value, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingIn(List<String> values) {
            addCriterion("AutomaticParking in", values, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingNotIn(List<String> values) {
            addCriterion("AutomaticParking not in", values, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingBetween(String value1, String value2) {
            addCriterion("AutomaticParking between", value1, value2, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andAutomaticparkingNotBetween(String value1, String value2) {
            addCriterion("AutomaticParking not between", value1, value2, "automaticparking");
            return (Criteria) this;
        }

        public Criteria andGsgIsNull() {
            addCriterion("GSG is null");
            return (Criteria) this;
        }

        public Criteria andGsgIsNotNull() {
            addCriterion("GSG is not null");
            return (Criteria) this;
        }

        public Criteria andGsgEqualTo(String value) {
            addCriterion("GSG =", value, "gsg");
            return (Criteria) this;
        }

        public Criteria andGsgNotEqualTo(String value) {
            addCriterion("GSG <>", value, "gsg");
            return (Criteria) this;
        }

        public Criteria andGsgGreaterThan(String value) {
            addCriterion("GSG >", value, "gsg");
            return (Criteria) this;
        }

        public Criteria andGsgGreaterThanOrEqualTo(String value) {
            addCriterion("GSG >=", value, "gsg");
            return (Criteria) this;
        }

        public Criteria andGsgLessThan(String value) {
            addCriterion("GSG <", value, "gsg");
            return (Criteria) this;
        }

        public Criteria andGsgLessThanOrEqualTo(String value) {
            addCriterion("GSG <=", value, "gsg");
            return (Criteria) this;
        }

        public Criteria andGsgLike(String value) {
            addCriterion("GSG like", value, "gsg");
            return (Criteria) this;
        }

        public Criteria andGsgNotLike(String value) {
            addCriterion("GSG not like", value, "gsg");
            return (Criteria) this;
        }

        public Criteria andGsgIn(List<String> values) {
            addCriterion("GSG in", values, "gsg");
            return (Criteria) this;
        }

        public Criteria andGsgNotIn(List<String> values) {
            addCriterion("GSG not in", values, "gsg");
            return (Criteria) this;
        }

        public Criteria andGsgBetween(String value1, String value2) {
            addCriterion("GSG between", value1, value2, "gsg");
            return (Criteria) this;
        }

        public Criteria andGsgNotBetween(String value1, String value2) {
            addCriterion("GSG not between", value1, value2, "gsg");
            return (Criteria) this;
        }

        public Criteria andDoublingtheauxiliaryIsNull() {
            addCriterion("DoublingTheAuxiliary is null");
            return (Criteria) this;
        }

        public Criteria andDoublingtheauxiliaryIsNotNull() {
            addCriterion("DoublingTheAuxiliary is not null");
            return (Criteria) this;
        }

        public Criteria andDoublingtheauxiliaryEqualTo(String value) {
            addCriterion("DoublingTheAuxiliary =", value, "doublingtheauxiliary");
            return (Criteria) this;
        }

        public Criteria andDoublingtheauxiliaryNotEqualTo(String value) {
            addCriterion("DoublingTheAuxiliary <>", value, "doublingtheauxiliary");
            return (Criteria) this;
        }

        public Criteria andDoublingtheauxiliaryGreaterThan(String value) {
            addCriterion("DoublingTheAuxiliary >", value, "doublingtheauxiliary");
            return (Criteria) this;
        }

        public Criteria andDoublingtheauxiliaryGreaterThanOrEqualTo(String value) {
            addCriterion("DoublingTheAuxiliary >=", value, "doublingtheauxiliary");
            return (Criteria) this;
        }

        public Criteria andDoublingtheauxiliaryLessThan(String value) {
            addCriterion("DoublingTheAuxiliary <", value, "doublingtheauxiliary");
            return (Criteria) this;
        }

        public Criteria andDoublingtheauxiliaryLessThanOrEqualTo(String value) {
            addCriterion("DoublingTheAuxiliary <=", value, "doublingtheauxiliary");
            return (Criteria) this;
        }

        public Criteria andDoublingtheauxiliaryLike(String value) {
            addCriterion("DoublingTheAuxiliary like", value, "doublingtheauxiliary");
            return (Criteria) this;
        }

        public Criteria andDoublingtheauxiliaryNotLike(String value) {
            addCriterion("DoublingTheAuxiliary not like", value, "doublingtheauxiliary");
            return (Criteria) this;
        }

        public Criteria andDoublingtheauxiliaryIn(List<String> values) {
            addCriterion("DoublingTheAuxiliary in", values, "doublingtheauxiliary");
            return (Criteria) this;
        }

        public Criteria andDoublingtheauxiliaryNotIn(List<String> values) {
            addCriterion("DoublingTheAuxiliary not in", values, "doublingtheauxiliary");
            return (Criteria) this;
        }

        public Criteria andDoublingtheauxiliaryBetween(String value1, String value2) {
            addCriterion("DoublingTheAuxiliary between", value1, value2, "doublingtheauxiliary");
            return (Criteria) this;
        }

        public Criteria andDoublingtheauxiliaryNotBetween(String value1, String value2) {
            addCriterion("DoublingTheAuxiliary not between", value1, value2, "doublingtheauxiliary");
            return (Criteria) this;
        }

        public Criteria andLdwsIsNull() {
            addCriterion("LDWS is null");
            return (Criteria) this;
        }

        public Criteria andLdwsIsNotNull() {
            addCriterion("LDWS is not null");
            return (Criteria) this;
        }

        public Criteria andLdwsEqualTo(String value) {
            addCriterion("LDWS =", value, "ldws");
            return (Criteria) this;
        }

        public Criteria andLdwsNotEqualTo(String value) {
            addCriterion("LDWS <>", value, "ldws");
            return (Criteria) this;
        }

        public Criteria andLdwsGreaterThan(String value) {
            addCriterion("LDWS >", value, "ldws");
            return (Criteria) this;
        }

        public Criteria andLdwsGreaterThanOrEqualTo(String value) {
            addCriterion("LDWS >=", value, "ldws");
            return (Criteria) this;
        }

        public Criteria andLdwsLessThan(String value) {
            addCriterion("LDWS <", value, "ldws");
            return (Criteria) this;
        }

        public Criteria andLdwsLessThanOrEqualTo(String value) {
            addCriterion("LDWS <=", value, "ldws");
            return (Criteria) this;
        }

        public Criteria andLdwsLike(String value) {
            addCriterion("LDWS like", value, "ldws");
            return (Criteria) this;
        }

        public Criteria andLdwsNotLike(String value) {
            addCriterion("LDWS not like", value, "ldws");
            return (Criteria) this;
        }

        public Criteria andLdwsIn(List<String> values) {
            addCriterion("LDWS in", values, "ldws");
            return (Criteria) this;
        }

        public Criteria andLdwsNotIn(List<String> values) {
            addCriterion("LDWS not in", values, "ldws");
            return (Criteria) this;
        }

        public Criteria andLdwsBetween(String value1, String value2) {
            addCriterion("LDWS between", value1, value2, "ldws");
            return (Criteria) this;
        }

        public Criteria andLdwsNotBetween(String value1, String value2) {
            addCriterion("LDWS not between", value1, value2, "ldws");
            return (Criteria) this;
        }

        public Criteria andActivebrakeActivesafetysystemIsNull() {
            addCriterion("ActiveBrake_ActiveSafetySystem is null");
            return (Criteria) this;
        }

        public Criteria andActivebrakeActivesafetysystemIsNotNull() {
            addCriterion("ActiveBrake_ActiveSafetySystem is not null");
            return (Criteria) this;
        }

        public Criteria andActivebrakeActivesafetysystemEqualTo(String value) {
            addCriterion("ActiveBrake_ActiveSafetySystem =", value, "activebrakeActivesafetysystem");
            return (Criteria) this;
        }

        public Criteria andActivebrakeActivesafetysystemNotEqualTo(String value) {
            addCriterion("ActiveBrake_ActiveSafetySystem <>", value, "activebrakeActivesafetysystem");
            return (Criteria) this;
        }

        public Criteria andActivebrakeActivesafetysystemGreaterThan(String value) {
            addCriterion("ActiveBrake_ActiveSafetySystem >", value, "activebrakeActivesafetysystem");
            return (Criteria) this;
        }

        public Criteria andActivebrakeActivesafetysystemGreaterThanOrEqualTo(String value) {
            addCriterion("ActiveBrake_ActiveSafetySystem >=", value, "activebrakeActivesafetysystem");
            return (Criteria) this;
        }

        public Criteria andActivebrakeActivesafetysystemLessThan(String value) {
            addCriterion("ActiveBrake_ActiveSafetySystem <", value, "activebrakeActivesafetysystem");
            return (Criteria) this;
        }

        public Criteria andActivebrakeActivesafetysystemLessThanOrEqualTo(String value) {
            addCriterion("ActiveBrake_ActiveSafetySystem <=", value, "activebrakeActivesafetysystem");
            return (Criteria) this;
        }

        public Criteria andActivebrakeActivesafetysystemLike(String value) {
            addCriterion("ActiveBrake_ActiveSafetySystem like", value, "activebrakeActivesafetysystem");
            return (Criteria) this;
        }

        public Criteria andActivebrakeActivesafetysystemNotLike(String value) {
            addCriterion("ActiveBrake_ActiveSafetySystem not like", value, "activebrakeActivesafetysystem");
            return (Criteria) this;
        }

        public Criteria andActivebrakeActivesafetysystemIn(List<String> values) {
            addCriterion("ActiveBrake_ActiveSafetySystem in", values, "activebrakeActivesafetysystem");
            return (Criteria) this;
        }

        public Criteria andActivebrakeActivesafetysystemNotIn(List<String> values) {
            addCriterion("ActiveBrake_ActiveSafetySystem not in", values, "activebrakeActivesafetysystem");
            return (Criteria) this;
        }

        public Criteria andActivebrakeActivesafetysystemBetween(String value1, String value2) {
            addCriterion("ActiveBrake_ActiveSafetySystem between", value1, value2, "activebrakeActivesafetysystem");
            return (Criteria) this;
        }

        public Criteria andActivebrakeActivesafetysystemNotBetween(String value1, String value2) {
            addCriterion("ActiveBrake_ActiveSafetySystem not between", value1, value2, "activebrakeActivesafetysystem");
            return (Criteria) this;
        }

        public Criteria andIntegralactivesteeringIsNull() {
            addCriterion("IntegralActiveSteering is null");
            return (Criteria) this;
        }

        public Criteria andIntegralactivesteeringIsNotNull() {
            addCriterion("IntegralActiveSteering is not null");
            return (Criteria) this;
        }

        public Criteria andIntegralactivesteeringEqualTo(String value) {
            addCriterion("IntegralActiveSteering =", value, "integralactivesteering");
            return (Criteria) this;
        }

        public Criteria andIntegralactivesteeringNotEqualTo(String value) {
            addCriterion("IntegralActiveSteering <>", value, "integralactivesteering");
            return (Criteria) this;
        }

        public Criteria andIntegralactivesteeringGreaterThan(String value) {
            addCriterion("IntegralActiveSteering >", value, "integralactivesteering");
            return (Criteria) this;
        }

        public Criteria andIntegralactivesteeringGreaterThanOrEqualTo(String value) {
            addCriterion("IntegralActiveSteering >=", value, "integralactivesteering");
            return (Criteria) this;
        }

        public Criteria andIntegralactivesteeringLessThan(String value) {
            addCriterion("IntegralActiveSteering <", value, "integralactivesteering");
            return (Criteria) this;
        }

        public Criteria andIntegralactivesteeringLessThanOrEqualTo(String value) {
            addCriterion("IntegralActiveSteering <=", value, "integralactivesteering");
            return (Criteria) this;
        }

        public Criteria andIntegralactivesteeringLike(String value) {
            addCriterion("IntegralActiveSteering like", value, "integralactivesteering");
            return (Criteria) this;
        }

        public Criteria andIntegralactivesteeringNotLike(String value) {
            addCriterion("IntegralActiveSteering not like", value, "integralactivesteering");
            return (Criteria) this;
        }

        public Criteria andIntegralactivesteeringIn(List<String> values) {
            addCriterion("IntegralActiveSteering in", values, "integralactivesteering");
            return (Criteria) this;
        }

        public Criteria andIntegralactivesteeringNotIn(List<String> values) {
            addCriterion("IntegralActiveSteering not in", values, "integralactivesteering");
            return (Criteria) this;
        }

        public Criteria andIntegralactivesteeringBetween(String value1, String value2) {
            addCriterion("IntegralActiveSteering between", value1, value2, "integralactivesteering");
            return (Criteria) this;
        }

        public Criteria andIntegralactivesteeringNotBetween(String value1, String value2) {
            addCriterion("IntegralActiveSteering not between", value1, value2, "integralactivesteering");
            return (Criteria) this;
        }

        public Criteria andNightcisionsystemIsNull() {
            addCriterion("NightCisionSystem is null");
            return (Criteria) this;
        }

        public Criteria andNightcisionsystemIsNotNull() {
            addCriterion("NightCisionSystem is not null");
            return (Criteria) this;
        }

        public Criteria andNightcisionsystemEqualTo(String value) {
            addCriterion("NightCisionSystem =", value, "nightcisionsystem");
            return (Criteria) this;
        }

        public Criteria andNightcisionsystemNotEqualTo(String value) {
            addCriterion("NightCisionSystem <>", value, "nightcisionsystem");
            return (Criteria) this;
        }

        public Criteria andNightcisionsystemGreaterThan(String value) {
            addCriterion("NightCisionSystem >", value, "nightcisionsystem");
            return (Criteria) this;
        }

        public Criteria andNightcisionsystemGreaterThanOrEqualTo(String value) {
            addCriterion("NightCisionSystem >=", value, "nightcisionsystem");
            return (Criteria) this;
        }

        public Criteria andNightcisionsystemLessThan(String value) {
            addCriterion("NightCisionSystem <", value, "nightcisionsystem");
            return (Criteria) this;
        }

        public Criteria andNightcisionsystemLessThanOrEqualTo(String value) {
            addCriterion("NightCisionSystem <=", value, "nightcisionsystem");
            return (Criteria) this;
        }

        public Criteria andNightcisionsystemLike(String value) {
            addCriterion("NightCisionSystem like", value, "nightcisionsystem");
            return (Criteria) this;
        }

        public Criteria andNightcisionsystemNotLike(String value) {
            addCriterion("NightCisionSystem not like", value, "nightcisionsystem");
            return (Criteria) this;
        }

        public Criteria andNightcisionsystemIn(List<String> values) {
            addCriterion("NightCisionSystem in", values, "nightcisionsystem");
            return (Criteria) this;
        }

        public Criteria andNightcisionsystemNotIn(List<String> values) {
            addCriterion("NightCisionSystem not in", values, "nightcisionsystem");
            return (Criteria) this;
        }

        public Criteria andNightcisionsystemBetween(String value1, String value2) {
            addCriterion("NightCisionSystem between", value1, value2, "nightcisionsystem");
            return (Criteria) this;
        }

        public Criteria andNightcisionsystemNotBetween(String value1, String value2) {
            addCriterion("NightCisionSystem not between", value1, value2, "nightcisionsystem");
            return (Criteria) this;
        }

        public Criteria andCentralcontrollcdsplitscreendisplayIsNull() {
            addCriterion("CentralControlLCDSplitScreenDisplay is null");
            return (Criteria) this;
        }

        public Criteria andCentralcontrollcdsplitscreendisplayIsNotNull() {
            addCriterion("CentralControlLCDSplitScreenDisplay is not null");
            return (Criteria) this;
        }

        public Criteria andCentralcontrollcdsplitscreendisplayEqualTo(String value) {
            addCriterion("CentralControlLCDSplitScreenDisplay =", value, "centralcontrollcdsplitscreendisplay");
            return (Criteria) this;
        }

        public Criteria andCentralcontrollcdsplitscreendisplayNotEqualTo(String value) {
            addCriterion("CentralControlLCDSplitScreenDisplay <>", value, "centralcontrollcdsplitscreendisplay");
            return (Criteria) this;
        }

        public Criteria andCentralcontrollcdsplitscreendisplayGreaterThan(String value) {
            addCriterion("CentralControlLCDSplitScreenDisplay >", value, "centralcontrollcdsplitscreendisplay");
            return (Criteria) this;
        }

        public Criteria andCentralcontrollcdsplitscreendisplayGreaterThanOrEqualTo(String value) {
            addCriterion("CentralControlLCDSplitScreenDisplay >=", value, "centralcontrollcdsplitscreendisplay");
            return (Criteria) this;
        }

        public Criteria andCentralcontrollcdsplitscreendisplayLessThan(String value) {
            addCriterion("CentralControlLCDSplitScreenDisplay <", value, "centralcontrollcdsplitscreendisplay");
            return (Criteria) this;
        }

        public Criteria andCentralcontrollcdsplitscreendisplayLessThanOrEqualTo(String value) {
            addCriterion("CentralControlLCDSplitScreenDisplay <=", value, "centralcontrollcdsplitscreendisplay");
            return (Criteria) this;
        }

        public Criteria andCentralcontrollcdsplitscreendisplayLike(String value) {
            addCriterion("CentralControlLCDSplitScreenDisplay like", value, "centralcontrollcdsplitscreendisplay");
            return (Criteria) this;
        }

        public Criteria andCentralcontrollcdsplitscreendisplayNotLike(String value) {
            addCriterion("CentralControlLCDSplitScreenDisplay not like", value, "centralcontrollcdsplitscreendisplay");
            return (Criteria) this;
        }

        public Criteria andCentralcontrollcdsplitscreendisplayIn(List<String> values) {
            addCriterion("CentralControlLCDSplitScreenDisplay in", values, "centralcontrollcdsplitscreendisplay");
            return (Criteria) this;
        }

        public Criteria andCentralcontrollcdsplitscreendisplayNotIn(List<String> values) {
            addCriterion("CentralControlLCDSplitScreenDisplay not in", values, "centralcontrollcdsplitscreendisplay");
            return (Criteria) this;
        }

        public Criteria andCentralcontrollcdsplitscreendisplayBetween(String value1, String value2) {
            addCriterion("CentralControlLCDSplitScreenDisplay between", value1, value2, "centralcontrollcdsplitscreendisplay");
            return (Criteria) this;
        }

        public Criteria andCentralcontrollcdsplitscreendisplayNotBetween(String value1, String value2) {
            addCriterion("CentralControlLCDSplitScreenDisplay not between", value1, value2, "centralcontrollcdsplitscreendisplay");
            return (Criteria) this;
        }

        public Criteria andSelfAdaptivecruisecontrolIsNull() {
            addCriterion("Self_adaptiveCruiseControl is null");
            return (Criteria) this;
        }

        public Criteria andSelfAdaptivecruisecontrolIsNotNull() {
            addCriterion("Self_adaptiveCruiseControl is not null");
            return (Criteria) this;
        }

        public Criteria andSelfAdaptivecruisecontrolEqualTo(String value) {
            addCriterion("Self_adaptiveCruiseControl =", value, "selfAdaptivecruisecontrol");
            return (Criteria) this;
        }

        public Criteria andSelfAdaptivecruisecontrolNotEqualTo(String value) {
            addCriterion("Self_adaptiveCruiseControl <>", value, "selfAdaptivecruisecontrol");
            return (Criteria) this;
        }

        public Criteria andSelfAdaptivecruisecontrolGreaterThan(String value) {
            addCriterion("Self_adaptiveCruiseControl >", value, "selfAdaptivecruisecontrol");
            return (Criteria) this;
        }

        public Criteria andSelfAdaptivecruisecontrolGreaterThanOrEqualTo(String value) {
            addCriterion("Self_adaptiveCruiseControl >=", value, "selfAdaptivecruisecontrol");
            return (Criteria) this;
        }

        public Criteria andSelfAdaptivecruisecontrolLessThan(String value) {
            addCriterion("Self_adaptiveCruiseControl <", value, "selfAdaptivecruisecontrol");
            return (Criteria) this;
        }

        public Criteria andSelfAdaptivecruisecontrolLessThanOrEqualTo(String value) {
            addCriterion("Self_adaptiveCruiseControl <=", value, "selfAdaptivecruisecontrol");
            return (Criteria) this;
        }

        public Criteria andSelfAdaptivecruisecontrolLike(String value) {
            addCriterion("Self_adaptiveCruiseControl like", value, "selfAdaptivecruisecontrol");
            return (Criteria) this;
        }

        public Criteria andSelfAdaptivecruisecontrolNotLike(String value) {
            addCriterion("Self_adaptiveCruiseControl not like", value, "selfAdaptivecruisecontrol");
            return (Criteria) this;
        }

        public Criteria andSelfAdaptivecruisecontrolIn(List<String> values) {
            addCriterion("Self_adaptiveCruiseControl in", values, "selfAdaptivecruisecontrol");
            return (Criteria) this;
        }

        public Criteria andSelfAdaptivecruisecontrolNotIn(List<String> values) {
            addCriterion("Self_adaptiveCruiseControl not in", values, "selfAdaptivecruisecontrol");
            return (Criteria) this;
        }

        public Criteria andSelfAdaptivecruisecontrolBetween(String value1, String value2) {
            addCriterion("Self_adaptiveCruiseControl between", value1, value2, "selfAdaptivecruisecontrol");
            return (Criteria) this;
        }

        public Criteria andSelfAdaptivecruisecontrolNotBetween(String value1, String value2) {
            addCriterion("Self_adaptiveCruiseControl not between", value1, value2, "selfAdaptivecruisecontrol");
            return (Criteria) this;
        }

        public Criteria andPanoramiccameraIsNull() {
            addCriterion("PanoramicCamera is null");
            return (Criteria) this;
        }

        public Criteria andPanoramiccameraIsNotNull() {
            addCriterion("PanoramicCamera is not null");
            return (Criteria) this;
        }

        public Criteria andPanoramiccameraEqualTo(String value) {
            addCriterion("PanoramicCamera =", value, "panoramiccamera");
            return (Criteria) this;
        }

        public Criteria andPanoramiccameraNotEqualTo(String value) {
            addCriterion("PanoramicCamera <>", value, "panoramiccamera");
            return (Criteria) this;
        }

        public Criteria andPanoramiccameraGreaterThan(String value) {
            addCriterion("PanoramicCamera >", value, "panoramiccamera");
            return (Criteria) this;
        }

        public Criteria andPanoramiccameraGreaterThanOrEqualTo(String value) {
            addCriterion("PanoramicCamera >=", value, "panoramiccamera");
            return (Criteria) this;
        }

        public Criteria andPanoramiccameraLessThan(String value) {
            addCriterion("PanoramicCamera <", value, "panoramiccamera");
            return (Criteria) this;
        }

        public Criteria andPanoramiccameraLessThanOrEqualTo(String value) {
            addCriterion("PanoramicCamera <=", value, "panoramiccamera");
            return (Criteria) this;
        }

        public Criteria andPanoramiccameraLike(String value) {
            addCriterion("PanoramicCamera like", value, "panoramiccamera");
            return (Criteria) this;
        }

        public Criteria andPanoramiccameraNotLike(String value) {
            addCriterion("PanoramicCamera not like", value, "panoramiccamera");
            return (Criteria) this;
        }

        public Criteria andPanoramiccameraIn(List<String> values) {
            addCriterion("PanoramicCamera in", values, "panoramiccamera");
            return (Criteria) this;
        }

        public Criteria andPanoramiccameraNotIn(List<String> values) {
            addCriterion("PanoramicCamera not in", values, "panoramiccamera");
            return (Criteria) this;
        }

        public Criteria andPanoramiccameraBetween(String value1, String value2) {
            addCriterion("PanoramicCamera between", value1, value2, "panoramiccamera");
            return (Criteria) this;
        }

        public Criteria andPanoramiccameraNotBetween(String value1, String value2) {
            addCriterion("PanoramicCamera not between", value1, value2, "panoramiccamera");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table high_tech_configuration
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table high_tech_configuration
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}