package com.car.pojo;

import java.util.ArrayList;
import java.util.List;

public class Internal_configurationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table internal_configuration
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table internal_configuration
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table internal_configuration
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_configuration
     *
     * @mbg.generated
     */
    public Internal_configurationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_configuration
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_configuration
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_configuration
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_configuration
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_configuration
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_configuration
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_configuration
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_configuration
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_configuration
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internal_configuration
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table internal_configuration
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNumIsNull() {
            addCriterion("Num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("Num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("Num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("Num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("Num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("Num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("Num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("Num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("Num like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("Num not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("Num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("Num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("Num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("Num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andLeathersteeringwheelIsNull() {
            addCriterion("LeatherSteeringWheel is null");
            return (Criteria) this;
        }

        public Criteria andLeathersteeringwheelIsNotNull() {
            addCriterion("LeatherSteeringWheel is not null");
            return (Criteria) this;
        }

        public Criteria andLeathersteeringwheelEqualTo(String value) {
            addCriterion("LeatherSteeringWheel =", value, "leathersteeringwheel");
            return (Criteria) this;
        }

        public Criteria andLeathersteeringwheelNotEqualTo(String value) {
            addCriterion("LeatherSteeringWheel <>", value, "leathersteeringwheel");
            return (Criteria) this;
        }

        public Criteria andLeathersteeringwheelGreaterThan(String value) {
            addCriterion("LeatherSteeringWheel >", value, "leathersteeringwheel");
            return (Criteria) this;
        }

        public Criteria andLeathersteeringwheelGreaterThanOrEqualTo(String value) {
            addCriterion("LeatherSteeringWheel >=", value, "leathersteeringwheel");
            return (Criteria) this;
        }

        public Criteria andLeathersteeringwheelLessThan(String value) {
            addCriterion("LeatherSteeringWheel <", value, "leathersteeringwheel");
            return (Criteria) this;
        }

        public Criteria andLeathersteeringwheelLessThanOrEqualTo(String value) {
            addCriterion("LeatherSteeringWheel <=", value, "leathersteeringwheel");
            return (Criteria) this;
        }

        public Criteria andLeathersteeringwheelLike(String value) {
            addCriterion("LeatherSteeringWheel like", value, "leathersteeringwheel");
            return (Criteria) this;
        }

        public Criteria andLeathersteeringwheelNotLike(String value) {
            addCriterion("LeatherSteeringWheel not like", value, "leathersteeringwheel");
            return (Criteria) this;
        }

        public Criteria andLeathersteeringwheelIn(List<String> values) {
            addCriterion("LeatherSteeringWheel in", values, "leathersteeringwheel");
            return (Criteria) this;
        }

        public Criteria andLeathersteeringwheelNotIn(List<String> values) {
            addCriterion("LeatherSteeringWheel not in", values, "leathersteeringwheel");
            return (Criteria) this;
        }

        public Criteria andLeathersteeringwheelBetween(String value1, String value2) {
            addCriterion("LeatherSteeringWheel between", value1, value2, "leathersteeringwheel");
            return (Criteria) this;
        }

        public Criteria andLeathersteeringwheelNotBetween(String value1, String value2) {
            addCriterion("LeatherSteeringWheel not between", value1, value2, "leathersteeringwheel");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelcontrolIsNull() {
            addCriterion("SteeringWheelControl is null");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelcontrolIsNotNull() {
            addCriterion("SteeringWheelControl is not null");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelcontrolEqualTo(String value) {
            addCriterion("SteeringWheelControl =", value, "steeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelcontrolNotEqualTo(String value) {
            addCriterion("SteeringWheelControl <>", value, "steeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelcontrolGreaterThan(String value) {
            addCriterion("SteeringWheelControl >", value, "steeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelcontrolGreaterThanOrEqualTo(String value) {
            addCriterion("SteeringWheelControl >=", value, "steeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelcontrolLessThan(String value) {
            addCriterion("SteeringWheelControl <", value, "steeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelcontrolLessThanOrEqualTo(String value) {
            addCriterion("SteeringWheelControl <=", value, "steeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelcontrolLike(String value) {
            addCriterion("SteeringWheelControl like", value, "steeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelcontrolNotLike(String value) {
            addCriterion("SteeringWheelControl not like", value, "steeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelcontrolIn(List<String> values) {
            addCriterion("SteeringWheelControl in", values, "steeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelcontrolNotIn(List<String> values) {
            addCriterion("SteeringWheelControl not in", values, "steeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelcontrolBetween(String value1, String value2) {
            addCriterion("SteeringWheelControl between", value1, value2, "steeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelcontrolNotBetween(String value1, String value2) {
            addCriterion("SteeringWheelControl not between", value1, value2, "steeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andElectricsteeringwheelcontrolIsNull() {
            addCriterion("ElectricSteeringWheelControl is null");
            return (Criteria) this;
        }

        public Criteria andElectricsteeringwheelcontrolIsNotNull() {
            addCriterion("ElectricSteeringWheelControl is not null");
            return (Criteria) this;
        }

        public Criteria andElectricsteeringwheelcontrolEqualTo(String value) {
            addCriterion("ElectricSteeringWheelControl =", value, "electricsteeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andElectricsteeringwheelcontrolNotEqualTo(String value) {
            addCriterion("ElectricSteeringWheelControl <>", value, "electricsteeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andElectricsteeringwheelcontrolGreaterThan(String value) {
            addCriterion("ElectricSteeringWheelControl >", value, "electricsteeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andElectricsteeringwheelcontrolGreaterThanOrEqualTo(String value) {
            addCriterion("ElectricSteeringWheelControl >=", value, "electricsteeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andElectricsteeringwheelcontrolLessThan(String value) {
            addCriterion("ElectricSteeringWheelControl <", value, "electricsteeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andElectricsteeringwheelcontrolLessThanOrEqualTo(String value) {
            addCriterion("ElectricSteeringWheelControl <=", value, "electricsteeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andElectricsteeringwheelcontrolLike(String value) {
            addCriterion("ElectricSteeringWheelControl like", value, "electricsteeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andElectricsteeringwheelcontrolNotLike(String value) {
            addCriterion("ElectricSteeringWheelControl not like", value, "electricsteeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andElectricsteeringwheelcontrolIn(List<String> values) {
            addCriterion("ElectricSteeringWheelControl in", values, "electricsteeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andElectricsteeringwheelcontrolNotIn(List<String> values) {
            addCriterion("ElectricSteeringWheelControl not in", values, "electricsteeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andElectricsteeringwheelcontrolBetween(String value1, String value2) {
            addCriterion("ElectricSteeringWheelControl between", value1, value2, "electricsteeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andElectricsteeringwheelcontrolNotBetween(String value1, String value2) {
            addCriterion("ElectricSteeringWheelControl not between", value1, value2, "electricsteeringwheelcontrol");
            return (Criteria) this;
        }

        public Criteria andMflIsNull() {
            addCriterion("MFL is null");
            return (Criteria) this;
        }

        public Criteria andMflIsNotNull() {
            addCriterion("MFL is not null");
            return (Criteria) this;
        }

        public Criteria andMflEqualTo(String value) {
            addCriterion("MFL =", value, "mfl");
            return (Criteria) this;
        }

        public Criteria andMflNotEqualTo(String value) {
            addCriterion("MFL <>", value, "mfl");
            return (Criteria) this;
        }

        public Criteria andMflGreaterThan(String value) {
            addCriterion("MFL >", value, "mfl");
            return (Criteria) this;
        }

        public Criteria andMflGreaterThanOrEqualTo(String value) {
            addCriterion("MFL >=", value, "mfl");
            return (Criteria) this;
        }

        public Criteria andMflLessThan(String value) {
            addCriterion("MFL <", value, "mfl");
            return (Criteria) this;
        }

        public Criteria andMflLessThanOrEqualTo(String value) {
            addCriterion("MFL <=", value, "mfl");
            return (Criteria) this;
        }

        public Criteria andMflLike(String value) {
            addCriterion("MFL like", value, "mfl");
            return (Criteria) this;
        }

        public Criteria andMflNotLike(String value) {
            addCriterion("MFL not like", value, "mfl");
            return (Criteria) this;
        }

        public Criteria andMflIn(List<String> values) {
            addCriterion("MFL in", values, "mfl");
            return (Criteria) this;
        }

        public Criteria andMflNotIn(List<String> values) {
            addCriterion("MFL not in", values, "mfl");
            return (Criteria) this;
        }

        public Criteria andMflBetween(String value1, String value2) {
            addCriterion("MFL between", value1, value2, "mfl");
            return (Criteria) this;
        }

        public Criteria andMflNotBetween(String value1, String value2) {
            addCriterion("MFL not between", value1, value2, "mfl");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelshiftIsNull() {
            addCriterion("SteeringWheelShift is null");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelshiftIsNotNull() {
            addCriterion("SteeringWheelShift is not null");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelshiftEqualTo(String value) {
            addCriterion("SteeringWheelShift =", value, "steeringwheelshift");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelshiftNotEqualTo(String value) {
            addCriterion("SteeringWheelShift <>", value, "steeringwheelshift");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelshiftGreaterThan(String value) {
            addCriterion("SteeringWheelShift >", value, "steeringwheelshift");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelshiftGreaterThanOrEqualTo(String value) {
            addCriterion("SteeringWheelShift >=", value, "steeringwheelshift");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelshiftLessThan(String value) {
            addCriterion("SteeringWheelShift <", value, "steeringwheelshift");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelshiftLessThanOrEqualTo(String value) {
            addCriterion("SteeringWheelShift <=", value, "steeringwheelshift");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelshiftLike(String value) {
            addCriterion("SteeringWheelShift like", value, "steeringwheelshift");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelshiftNotLike(String value) {
            addCriterion("SteeringWheelShift not like", value, "steeringwheelshift");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelshiftIn(List<String> values) {
            addCriterion("SteeringWheelShift in", values, "steeringwheelshift");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelshiftNotIn(List<String> values) {
            addCriterion("SteeringWheelShift not in", values, "steeringwheelshift");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelshiftBetween(String value1, String value2) {
            addCriterion("SteeringWheelShift between", value1, value2, "steeringwheelshift");
            return (Criteria) this;
        }

        public Criteria andSteeringwheelshiftNotBetween(String value1, String value2) {
            addCriterion("SteeringWheelShift not between", value1, value2, "steeringwheelshift");
            return (Criteria) this;
        }

        public Criteria andHeatedsteeringwheelIsNull() {
            addCriterion("HeatedSteeringWheel is null");
            return (Criteria) this;
        }

        public Criteria andHeatedsteeringwheelIsNotNull() {
            addCriterion("HeatedSteeringWheel is not null");
            return (Criteria) this;
        }

        public Criteria andHeatedsteeringwheelEqualTo(String value) {
            addCriterion("HeatedSteeringWheel =", value, "heatedsteeringwheel");
            return (Criteria) this;
        }

        public Criteria andHeatedsteeringwheelNotEqualTo(String value) {
            addCriterion("HeatedSteeringWheel <>", value, "heatedsteeringwheel");
            return (Criteria) this;
        }

        public Criteria andHeatedsteeringwheelGreaterThan(String value) {
            addCriterion("HeatedSteeringWheel >", value, "heatedsteeringwheel");
            return (Criteria) this;
        }

        public Criteria andHeatedsteeringwheelGreaterThanOrEqualTo(String value) {
            addCriterion("HeatedSteeringWheel >=", value, "heatedsteeringwheel");
            return (Criteria) this;
        }

        public Criteria andHeatedsteeringwheelLessThan(String value) {
            addCriterion("HeatedSteeringWheel <", value, "heatedsteeringwheel");
            return (Criteria) this;
        }

        public Criteria andHeatedsteeringwheelLessThanOrEqualTo(String value) {
            addCriterion("HeatedSteeringWheel <=", value, "heatedsteeringwheel");
            return (Criteria) this;
        }

        public Criteria andHeatedsteeringwheelLike(String value) {
            addCriterion("HeatedSteeringWheel like", value, "heatedsteeringwheel");
            return (Criteria) this;
        }

        public Criteria andHeatedsteeringwheelNotLike(String value) {
            addCriterion("HeatedSteeringWheel not like", value, "heatedsteeringwheel");
            return (Criteria) this;
        }

        public Criteria andHeatedsteeringwheelIn(List<String> values) {
            addCriterion("HeatedSteeringWheel in", values, "heatedsteeringwheel");
            return (Criteria) this;
        }

        public Criteria andHeatedsteeringwheelNotIn(List<String> values) {
            addCriterion("HeatedSteeringWheel not in", values, "heatedsteeringwheel");
            return (Criteria) this;
        }

        public Criteria andHeatedsteeringwheelBetween(String value1, String value2) {
            addCriterion("HeatedSteeringWheel between", value1, value2, "heatedsteeringwheel");
            return (Criteria) this;
        }

        public Criteria andHeatedsteeringwheelNotBetween(String value1, String value2) {
            addCriterion("HeatedSteeringWheel not between", value1, value2, "heatedsteeringwheel");
            return (Criteria) this;
        }

        public Criteria andSteeringmemoryIsNull() {
            addCriterion("SteeringMemory is null");
            return (Criteria) this;
        }

        public Criteria andSteeringmemoryIsNotNull() {
            addCriterion("SteeringMemory is not null");
            return (Criteria) this;
        }

        public Criteria andSteeringmemoryEqualTo(String value) {
            addCriterion("SteeringMemory =", value, "steeringmemory");
            return (Criteria) this;
        }

        public Criteria andSteeringmemoryNotEqualTo(String value) {
            addCriterion("SteeringMemory <>", value, "steeringmemory");
            return (Criteria) this;
        }

        public Criteria andSteeringmemoryGreaterThan(String value) {
            addCriterion("SteeringMemory >", value, "steeringmemory");
            return (Criteria) this;
        }

        public Criteria andSteeringmemoryGreaterThanOrEqualTo(String value) {
            addCriterion("SteeringMemory >=", value, "steeringmemory");
            return (Criteria) this;
        }

        public Criteria andSteeringmemoryLessThan(String value) {
            addCriterion("SteeringMemory <", value, "steeringmemory");
            return (Criteria) this;
        }

        public Criteria andSteeringmemoryLessThanOrEqualTo(String value) {
            addCriterion("SteeringMemory <=", value, "steeringmemory");
            return (Criteria) this;
        }

        public Criteria andSteeringmemoryLike(String value) {
            addCriterion("SteeringMemory like", value, "steeringmemory");
            return (Criteria) this;
        }

        public Criteria andSteeringmemoryNotLike(String value) {
            addCriterion("SteeringMemory not like", value, "steeringmemory");
            return (Criteria) this;
        }

        public Criteria andSteeringmemoryIn(List<String> values) {
            addCriterion("SteeringMemory in", values, "steeringmemory");
            return (Criteria) this;
        }

        public Criteria andSteeringmemoryNotIn(List<String> values) {
            addCriterion("SteeringMemory not in", values, "steeringmemory");
            return (Criteria) this;
        }

        public Criteria andSteeringmemoryBetween(String value1, String value2) {
            addCriterion("SteeringMemory between", value1, value2, "steeringmemory");
            return (Criteria) this;
        }

        public Criteria andSteeringmemoryNotBetween(String value1, String value2) {
            addCriterion("SteeringMemory not between", value1, value2, "steeringmemory");
            return (Criteria) this;
        }

        public Criteria andCruiseIsNull() {
            addCriterion("Cruise is null");
            return (Criteria) this;
        }

        public Criteria andCruiseIsNotNull() {
            addCriterion("Cruise is not null");
            return (Criteria) this;
        }

        public Criteria andCruiseEqualTo(String value) {
            addCriterion("Cruise =", value, "cruise");
            return (Criteria) this;
        }

        public Criteria andCruiseNotEqualTo(String value) {
            addCriterion("Cruise <>", value, "cruise");
            return (Criteria) this;
        }

        public Criteria andCruiseGreaterThan(String value) {
            addCriterion("Cruise >", value, "cruise");
            return (Criteria) this;
        }

        public Criteria andCruiseGreaterThanOrEqualTo(String value) {
            addCriterion("Cruise >=", value, "cruise");
            return (Criteria) this;
        }

        public Criteria andCruiseLessThan(String value) {
            addCriterion("Cruise <", value, "cruise");
            return (Criteria) this;
        }

        public Criteria andCruiseLessThanOrEqualTo(String value) {
            addCriterion("Cruise <=", value, "cruise");
            return (Criteria) this;
        }

        public Criteria andCruiseLike(String value) {
            addCriterion("Cruise like", value, "cruise");
            return (Criteria) this;
        }

        public Criteria andCruiseNotLike(String value) {
            addCriterion("Cruise not like", value, "cruise");
            return (Criteria) this;
        }

        public Criteria andCruiseIn(List<String> values) {
            addCriterion("Cruise in", values, "cruise");
            return (Criteria) this;
        }

        public Criteria andCruiseNotIn(List<String> values) {
            addCriterion("Cruise not in", values, "cruise");
            return (Criteria) this;
        }

        public Criteria andCruiseBetween(String value1, String value2) {
            addCriterion("Cruise between", value1, value2, "cruise");
            return (Criteria) this;
        }

        public Criteria andCruiseNotBetween(String value1, String value2) {
            addCriterion("Cruise not between", value1, value2, "cruise");
            return (Criteria) this;
        }

        public Criteria andFrontRearparkingradarIsNull() {
            addCriterion("Front_rearParkingRadar is null");
            return (Criteria) this;
        }

        public Criteria andFrontRearparkingradarIsNotNull() {
            addCriterion("Front_rearParkingRadar is not null");
            return (Criteria) this;
        }

        public Criteria andFrontRearparkingradarEqualTo(String value) {
            addCriterion("Front_rearParkingRadar =", value, "frontRearparkingradar");
            return (Criteria) this;
        }

        public Criteria andFrontRearparkingradarNotEqualTo(String value) {
            addCriterion("Front_rearParkingRadar <>", value, "frontRearparkingradar");
            return (Criteria) this;
        }

        public Criteria andFrontRearparkingradarGreaterThan(String value) {
            addCriterion("Front_rearParkingRadar >", value, "frontRearparkingradar");
            return (Criteria) this;
        }

        public Criteria andFrontRearparkingradarGreaterThanOrEqualTo(String value) {
            addCriterion("Front_rearParkingRadar >=", value, "frontRearparkingradar");
            return (Criteria) this;
        }

        public Criteria andFrontRearparkingradarLessThan(String value) {
            addCriterion("Front_rearParkingRadar <", value, "frontRearparkingradar");
            return (Criteria) this;
        }

        public Criteria andFrontRearparkingradarLessThanOrEqualTo(String value) {
            addCriterion("Front_rearParkingRadar <=", value, "frontRearparkingradar");
            return (Criteria) this;
        }

        public Criteria andFrontRearparkingradarLike(String value) {
            addCriterion("Front_rearParkingRadar like", value, "frontRearparkingradar");
            return (Criteria) this;
        }

        public Criteria andFrontRearparkingradarNotLike(String value) {
            addCriterion("Front_rearParkingRadar not like", value, "frontRearparkingradar");
            return (Criteria) this;
        }

        public Criteria andFrontRearparkingradarIn(List<String> values) {
            addCriterion("Front_rearParkingRadar in", values, "frontRearparkingradar");
            return (Criteria) this;
        }

        public Criteria andFrontRearparkingradarNotIn(List<String> values) {
            addCriterion("Front_rearParkingRadar not in", values, "frontRearparkingradar");
            return (Criteria) this;
        }

        public Criteria andFrontRearparkingradarBetween(String value1, String value2) {
            addCriterion("Front_rearParkingRadar between", value1, value2, "frontRearparkingradar");
            return (Criteria) this;
        }

        public Criteria andFrontRearparkingradarNotBetween(String value1, String value2) {
            addCriterion("Front_rearParkingRadar not between", value1, value2, "frontRearparkingradar");
            return (Criteria) this;
        }

        public Criteria andRearvideoIsNull() {
            addCriterion("RearVideo is null");
            return (Criteria) this;
        }

        public Criteria andRearvideoIsNotNull() {
            addCriterion("RearVideo is not null");
            return (Criteria) this;
        }

        public Criteria andRearvideoEqualTo(String value) {
            addCriterion("RearVideo =", value, "rearvideo");
            return (Criteria) this;
        }

        public Criteria andRearvideoNotEqualTo(String value) {
            addCriterion("RearVideo <>", value, "rearvideo");
            return (Criteria) this;
        }

        public Criteria andRearvideoGreaterThan(String value) {
            addCriterion("RearVideo >", value, "rearvideo");
            return (Criteria) this;
        }

        public Criteria andRearvideoGreaterThanOrEqualTo(String value) {
            addCriterion("RearVideo >=", value, "rearvideo");
            return (Criteria) this;
        }

        public Criteria andRearvideoLessThan(String value) {
            addCriterion("RearVideo <", value, "rearvideo");
            return (Criteria) this;
        }

        public Criteria andRearvideoLessThanOrEqualTo(String value) {
            addCriterion("RearVideo <=", value, "rearvideo");
            return (Criteria) this;
        }

        public Criteria andRearvideoLike(String value) {
            addCriterion("RearVideo like", value, "rearvideo");
            return (Criteria) this;
        }

        public Criteria andRearvideoNotLike(String value) {
            addCriterion("RearVideo not like", value, "rearvideo");
            return (Criteria) this;
        }

        public Criteria andRearvideoIn(List<String> values) {
            addCriterion("RearVideo in", values, "rearvideo");
            return (Criteria) this;
        }

        public Criteria andRearvideoNotIn(List<String> values) {
            addCriterion("RearVideo not in", values, "rearvideo");
            return (Criteria) this;
        }

        public Criteria andRearvideoBetween(String value1, String value2) {
            addCriterion("RearVideo between", value1, value2, "rearvideo");
            return (Criteria) this;
        }

        public Criteria andRearvideoNotBetween(String value1, String value2) {
            addCriterion("RearVideo not between", value1, value2, "rearvideo");
            return (Criteria) this;
        }

        public Criteria andDrivingcomputerdisplayscreenIsNull() {
            addCriterion("DrivingComputerDisplayScreen is null");
            return (Criteria) this;
        }

        public Criteria andDrivingcomputerdisplayscreenIsNotNull() {
            addCriterion("DrivingComputerDisplayScreen is not null");
            return (Criteria) this;
        }

        public Criteria andDrivingcomputerdisplayscreenEqualTo(String value) {
            addCriterion("DrivingComputerDisplayScreen =", value, "drivingcomputerdisplayscreen");
            return (Criteria) this;
        }

        public Criteria andDrivingcomputerdisplayscreenNotEqualTo(String value) {
            addCriterion("DrivingComputerDisplayScreen <>", value, "drivingcomputerdisplayscreen");
            return (Criteria) this;
        }

        public Criteria andDrivingcomputerdisplayscreenGreaterThan(String value) {
            addCriterion("DrivingComputerDisplayScreen >", value, "drivingcomputerdisplayscreen");
            return (Criteria) this;
        }

        public Criteria andDrivingcomputerdisplayscreenGreaterThanOrEqualTo(String value) {
            addCriterion("DrivingComputerDisplayScreen >=", value, "drivingcomputerdisplayscreen");
            return (Criteria) this;
        }

        public Criteria andDrivingcomputerdisplayscreenLessThan(String value) {
            addCriterion("DrivingComputerDisplayScreen <", value, "drivingcomputerdisplayscreen");
            return (Criteria) this;
        }

        public Criteria andDrivingcomputerdisplayscreenLessThanOrEqualTo(String value) {
            addCriterion("DrivingComputerDisplayScreen <=", value, "drivingcomputerdisplayscreen");
            return (Criteria) this;
        }

        public Criteria andDrivingcomputerdisplayscreenLike(String value) {
            addCriterion("DrivingComputerDisplayScreen like", value, "drivingcomputerdisplayscreen");
            return (Criteria) this;
        }

        public Criteria andDrivingcomputerdisplayscreenNotLike(String value) {
            addCriterion("DrivingComputerDisplayScreen not like", value, "drivingcomputerdisplayscreen");
            return (Criteria) this;
        }

        public Criteria andDrivingcomputerdisplayscreenIn(List<String> values) {
            addCriterion("DrivingComputerDisplayScreen in", values, "drivingcomputerdisplayscreen");
            return (Criteria) this;
        }

        public Criteria andDrivingcomputerdisplayscreenNotIn(List<String> values) {
            addCriterion("DrivingComputerDisplayScreen not in", values, "drivingcomputerdisplayscreen");
            return (Criteria) this;
        }

        public Criteria andDrivingcomputerdisplayscreenBetween(String value1, String value2) {
            addCriterion("DrivingComputerDisplayScreen between", value1, value2, "drivingcomputerdisplayscreen");
            return (Criteria) this;
        }

        public Criteria andDrivingcomputerdisplayscreenNotBetween(String value1, String value2) {
            addCriterion("DrivingComputerDisplayScreen not between", value1, value2, "drivingcomputerdisplayscreen");
            return (Criteria) this;
        }

        public Criteria andFulllcdpanelIsNull() {
            addCriterion("FullLCDPanel is null");
            return (Criteria) this;
        }

        public Criteria andFulllcdpanelIsNotNull() {
            addCriterion("FullLCDPanel is not null");
            return (Criteria) this;
        }

        public Criteria andFulllcdpanelEqualTo(String value) {
            addCriterion("FullLCDPanel =", value, "fulllcdpanel");
            return (Criteria) this;
        }

        public Criteria andFulllcdpanelNotEqualTo(String value) {
            addCriterion("FullLCDPanel <>", value, "fulllcdpanel");
            return (Criteria) this;
        }

        public Criteria andFulllcdpanelGreaterThan(String value) {
            addCriterion("FullLCDPanel >", value, "fulllcdpanel");
            return (Criteria) this;
        }

        public Criteria andFulllcdpanelGreaterThanOrEqualTo(String value) {
            addCriterion("FullLCDPanel >=", value, "fulllcdpanel");
            return (Criteria) this;
        }

        public Criteria andFulllcdpanelLessThan(String value) {
            addCriterion("FullLCDPanel <", value, "fulllcdpanel");
            return (Criteria) this;
        }

        public Criteria andFulllcdpanelLessThanOrEqualTo(String value) {
            addCriterion("FullLCDPanel <=", value, "fulllcdpanel");
            return (Criteria) this;
        }

        public Criteria andFulllcdpanelLike(String value) {
            addCriterion("FullLCDPanel like", value, "fulllcdpanel");
            return (Criteria) this;
        }

        public Criteria andFulllcdpanelNotLike(String value) {
            addCriterion("FullLCDPanel not like", value, "fulllcdpanel");
            return (Criteria) this;
        }

        public Criteria andFulllcdpanelIn(List<String> values) {
            addCriterion("FullLCDPanel in", values, "fulllcdpanel");
            return (Criteria) this;
        }

        public Criteria andFulllcdpanelNotIn(List<String> values) {
            addCriterion("FullLCDPanel not in", values, "fulllcdpanel");
            return (Criteria) this;
        }

        public Criteria andFulllcdpanelBetween(String value1, String value2) {
            addCriterion("FullLCDPanel between", value1, value2, "fulllcdpanel");
            return (Criteria) this;
        }

        public Criteria andFulllcdpanelNotBetween(String value1, String value2) {
            addCriterion("FullLCDPanel not between", value1, value2, "fulllcdpanel");
            return (Criteria) this;
        }

        public Criteria andHudIsNull() {
            addCriterion("HUD is null");
            return (Criteria) this;
        }

        public Criteria andHudIsNotNull() {
            addCriterion("HUD is not null");
            return (Criteria) this;
        }

        public Criteria andHudEqualTo(String value) {
            addCriterion("HUD =", value, "hud");
            return (Criteria) this;
        }

        public Criteria andHudNotEqualTo(String value) {
            addCriterion("HUD <>", value, "hud");
            return (Criteria) this;
        }

        public Criteria andHudGreaterThan(String value) {
            addCriterion("HUD >", value, "hud");
            return (Criteria) this;
        }

        public Criteria andHudGreaterThanOrEqualTo(String value) {
            addCriterion("HUD >=", value, "hud");
            return (Criteria) this;
        }

        public Criteria andHudLessThan(String value) {
            addCriterion("HUD <", value, "hud");
            return (Criteria) this;
        }

        public Criteria andHudLessThanOrEqualTo(String value) {
            addCriterion("HUD <=", value, "hud");
            return (Criteria) this;
        }

        public Criteria andHudLike(String value) {
            addCriterion("HUD like", value, "hud");
            return (Criteria) this;
        }

        public Criteria andHudNotLike(String value) {
            addCriterion("HUD not like", value, "hud");
            return (Criteria) this;
        }

        public Criteria andHudIn(List<String> values) {
            addCriterion("HUD in", values, "hud");
            return (Criteria) this;
        }

        public Criteria andHudNotIn(List<String> values) {
            addCriterion("HUD not in", values, "hud");
            return (Criteria) this;
        }

        public Criteria andHudBetween(String value1, String value2) {
            addCriterion("HUD between", value1, value2, "hud");
            return (Criteria) this;
        }

        public Criteria andHudNotBetween(String value1, String value2) {
            addCriterion("HUD not between", value1, value2, "hud");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table internal_configuration
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table internal_configuration
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}