package com.car.pojo;

import java.util.ArrayList;
import java.util.List;

public class Light_configurationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table light_configuration
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table light_configuration
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table light_configuration
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_configuration
     *
     * @mbg.generated
     */
    public Light_configurationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_configuration
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_configuration
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_configuration
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_configuration
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_configuration
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_configuration
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_configuration
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_configuration
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_configuration
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_configuration
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table light_configuration
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNumIsNull() {
            addCriterion("Num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("Num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("Num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("Num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("Num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("Num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("Num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("Num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("Num like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("Num not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("Num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("Num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("Num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("Num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andDippedheadlightIsNull() {
            addCriterion("DippedHeadlight is null");
            return (Criteria) this;
        }

        public Criteria andDippedheadlightIsNotNull() {
            addCriterion("DippedHeadlight is not null");
            return (Criteria) this;
        }

        public Criteria andDippedheadlightEqualTo(String value) {
            addCriterion("DippedHeadlight =", value, "dippedheadlight");
            return (Criteria) this;
        }

        public Criteria andDippedheadlightNotEqualTo(String value) {
            addCriterion("DippedHeadlight <>", value, "dippedheadlight");
            return (Criteria) this;
        }

        public Criteria andDippedheadlightGreaterThan(String value) {
            addCriterion("DippedHeadlight >", value, "dippedheadlight");
            return (Criteria) this;
        }

        public Criteria andDippedheadlightGreaterThanOrEqualTo(String value) {
            addCriterion("DippedHeadlight >=", value, "dippedheadlight");
            return (Criteria) this;
        }

        public Criteria andDippedheadlightLessThan(String value) {
            addCriterion("DippedHeadlight <", value, "dippedheadlight");
            return (Criteria) this;
        }

        public Criteria andDippedheadlightLessThanOrEqualTo(String value) {
            addCriterion("DippedHeadlight <=", value, "dippedheadlight");
            return (Criteria) this;
        }

        public Criteria andDippedheadlightLike(String value) {
            addCriterion("DippedHeadlight like", value, "dippedheadlight");
            return (Criteria) this;
        }

        public Criteria andDippedheadlightNotLike(String value) {
            addCriterion("DippedHeadlight not like", value, "dippedheadlight");
            return (Criteria) this;
        }

        public Criteria andDippedheadlightIn(List<String> values) {
            addCriterion("DippedHeadlight in", values, "dippedheadlight");
            return (Criteria) this;
        }

        public Criteria andDippedheadlightNotIn(List<String> values) {
            addCriterion("DippedHeadlight not in", values, "dippedheadlight");
            return (Criteria) this;
        }

        public Criteria andDippedheadlightBetween(String value1, String value2) {
            addCriterion("DippedHeadlight between", value1, value2, "dippedheadlight");
            return (Criteria) this;
        }

        public Criteria andDippedheadlightNotBetween(String value1, String value2) {
            addCriterion("DippedHeadlight not between", value1, value2, "dippedheadlight");
            return (Criteria) this;
        }

        public Criteria andHighbeamIsNull() {
            addCriterion("HighBeam is null");
            return (Criteria) this;
        }

        public Criteria andHighbeamIsNotNull() {
            addCriterion("HighBeam is not null");
            return (Criteria) this;
        }

        public Criteria andHighbeamEqualTo(String value) {
            addCriterion("HighBeam =", value, "highbeam");
            return (Criteria) this;
        }

        public Criteria andHighbeamNotEqualTo(String value) {
            addCriterion("HighBeam <>", value, "highbeam");
            return (Criteria) this;
        }

        public Criteria andHighbeamGreaterThan(String value) {
            addCriterion("HighBeam >", value, "highbeam");
            return (Criteria) this;
        }

        public Criteria andHighbeamGreaterThanOrEqualTo(String value) {
            addCriterion("HighBeam >=", value, "highbeam");
            return (Criteria) this;
        }

        public Criteria andHighbeamLessThan(String value) {
            addCriterion("HighBeam <", value, "highbeam");
            return (Criteria) this;
        }

        public Criteria andHighbeamLessThanOrEqualTo(String value) {
            addCriterion("HighBeam <=", value, "highbeam");
            return (Criteria) this;
        }

        public Criteria andHighbeamLike(String value) {
            addCriterion("HighBeam like", value, "highbeam");
            return (Criteria) this;
        }

        public Criteria andHighbeamNotLike(String value) {
            addCriterion("HighBeam not like", value, "highbeam");
            return (Criteria) this;
        }

        public Criteria andHighbeamIn(List<String> values) {
            addCriterion("HighBeam in", values, "highbeam");
            return (Criteria) this;
        }

        public Criteria andHighbeamNotIn(List<String> values) {
            addCriterion("HighBeam not in", values, "highbeam");
            return (Criteria) this;
        }

        public Criteria andHighbeamBetween(String value1, String value2) {
            addCriterion("HighBeam between", value1, value2, "highbeam");
            return (Criteria) this;
        }

        public Criteria andHighbeamNotBetween(String value1, String value2) {
            addCriterion("HighBeam not between", value1, value2, "highbeam");
            return (Criteria) this;
        }

        public Criteria andDaytimerunninglightIsNull() {
            addCriterion("DaytimeRunningLight is null");
            return (Criteria) this;
        }

        public Criteria andDaytimerunninglightIsNotNull() {
            addCriterion("DaytimeRunningLight is not null");
            return (Criteria) this;
        }

        public Criteria andDaytimerunninglightEqualTo(String value) {
            addCriterion("DaytimeRunningLight =", value, "daytimerunninglight");
            return (Criteria) this;
        }

        public Criteria andDaytimerunninglightNotEqualTo(String value) {
            addCriterion("DaytimeRunningLight <>", value, "daytimerunninglight");
            return (Criteria) this;
        }

        public Criteria andDaytimerunninglightGreaterThan(String value) {
            addCriterion("DaytimeRunningLight >", value, "daytimerunninglight");
            return (Criteria) this;
        }

        public Criteria andDaytimerunninglightGreaterThanOrEqualTo(String value) {
            addCriterion("DaytimeRunningLight >=", value, "daytimerunninglight");
            return (Criteria) this;
        }

        public Criteria andDaytimerunninglightLessThan(String value) {
            addCriterion("DaytimeRunningLight <", value, "daytimerunninglight");
            return (Criteria) this;
        }

        public Criteria andDaytimerunninglightLessThanOrEqualTo(String value) {
            addCriterion("DaytimeRunningLight <=", value, "daytimerunninglight");
            return (Criteria) this;
        }

        public Criteria andDaytimerunninglightLike(String value) {
            addCriterion("DaytimeRunningLight like", value, "daytimerunninglight");
            return (Criteria) this;
        }

        public Criteria andDaytimerunninglightNotLike(String value) {
            addCriterion("DaytimeRunningLight not like", value, "daytimerunninglight");
            return (Criteria) this;
        }

        public Criteria andDaytimerunninglightIn(List<String> values) {
            addCriterion("DaytimeRunningLight in", values, "daytimerunninglight");
            return (Criteria) this;
        }

        public Criteria andDaytimerunninglightNotIn(List<String> values) {
            addCriterion("DaytimeRunningLight not in", values, "daytimerunninglight");
            return (Criteria) this;
        }

        public Criteria andDaytimerunninglightBetween(String value1, String value2) {
            addCriterion("DaytimeRunningLight between", value1, value2, "daytimerunninglight");
            return (Criteria) this;
        }

        public Criteria andDaytimerunninglightNotBetween(String value1, String value2) {
            addCriterion("DaytimeRunningLight not between", value1, value2, "daytimerunninglight");
            return (Criteria) this;
        }

        public Criteria andAdaptivetonearandfarlightIsNull() {
            addCriterion("AdaptiveToNearAndFarLight is null");
            return (Criteria) this;
        }

        public Criteria andAdaptivetonearandfarlightIsNotNull() {
            addCriterion("AdaptiveToNearAndFarLight is not null");
            return (Criteria) this;
        }

        public Criteria andAdaptivetonearandfarlightEqualTo(String value) {
            addCriterion("AdaptiveToNearAndFarLight =", value, "adaptivetonearandfarlight");
            return (Criteria) this;
        }

        public Criteria andAdaptivetonearandfarlightNotEqualTo(String value) {
            addCriterion("AdaptiveToNearAndFarLight <>", value, "adaptivetonearandfarlight");
            return (Criteria) this;
        }

        public Criteria andAdaptivetonearandfarlightGreaterThan(String value) {
            addCriterion("AdaptiveToNearAndFarLight >", value, "adaptivetonearandfarlight");
            return (Criteria) this;
        }

        public Criteria andAdaptivetonearandfarlightGreaterThanOrEqualTo(String value) {
            addCriterion("AdaptiveToNearAndFarLight >=", value, "adaptivetonearandfarlight");
            return (Criteria) this;
        }

        public Criteria andAdaptivetonearandfarlightLessThan(String value) {
            addCriterion("AdaptiveToNearAndFarLight <", value, "adaptivetonearandfarlight");
            return (Criteria) this;
        }

        public Criteria andAdaptivetonearandfarlightLessThanOrEqualTo(String value) {
            addCriterion("AdaptiveToNearAndFarLight <=", value, "adaptivetonearandfarlight");
            return (Criteria) this;
        }

        public Criteria andAdaptivetonearandfarlightLike(String value) {
            addCriterion("AdaptiveToNearAndFarLight like", value, "adaptivetonearandfarlight");
            return (Criteria) this;
        }

        public Criteria andAdaptivetonearandfarlightNotLike(String value) {
            addCriterion("AdaptiveToNearAndFarLight not like", value, "adaptivetonearandfarlight");
            return (Criteria) this;
        }

        public Criteria andAdaptivetonearandfarlightIn(List<String> values) {
            addCriterion("AdaptiveToNearAndFarLight in", values, "adaptivetonearandfarlight");
            return (Criteria) this;
        }

        public Criteria andAdaptivetonearandfarlightNotIn(List<String> values) {
            addCriterion("AdaptiveToNearAndFarLight not in", values, "adaptivetonearandfarlight");
            return (Criteria) this;
        }

        public Criteria andAdaptivetonearandfarlightBetween(String value1, String value2) {
            addCriterion("AdaptiveToNearAndFarLight between", value1, value2, "adaptivetonearandfarlight");
            return (Criteria) this;
        }

        public Criteria andAdaptivetonearandfarlightNotBetween(String value1, String value2) {
            addCriterion("AdaptiveToNearAndFarLight not between", value1, value2, "adaptivetonearandfarlight");
            return (Criteria) this;
        }

        public Criteria andAutolightIsNull() {
            addCriterion("AutoLight is null");
            return (Criteria) this;
        }

        public Criteria andAutolightIsNotNull() {
            addCriterion("AutoLight is not null");
            return (Criteria) this;
        }

        public Criteria andAutolightEqualTo(String value) {
            addCriterion("AutoLight =", value, "autolight");
            return (Criteria) this;
        }

        public Criteria andAutolightNotEqualTo(String value) {
            addCriterion("AutoLight <>", value, "autolight");
            return (Criteria) this;
        }

        public Criteria andAutolightGreaterThan(String value) {
            addCriterion("AutoLight >", value, "autolight");
            return (Criteria) this;
        }

        public Criteria andAutolightGreaterThanOrEqualTo(String value) {
            addCriterion("AutoLight >=", value, "autolight");
            return (Criteria) this;
        }

        public Criteria andAutolightLessThan(String value) {
            addCriterion("AutoLight <", value, "autolight");
            return (Criteria) this;
        }

        public Criteria andAutolightLessThanOrEqualTo(String value) {
            addCriterion("AutoLight <=", value, "autolight");
            return (Criteria) this;
        }

        public Criteria andAutolightLike(String value) {
            addCriterion("AutoLight like", value, "autolight");
            return (Criteria) this;
        }

        public Criteria andAutolightNotLike(String value) {
            addCriterion("AutoLight not like", value, "autolight");
            return (Criteria) this;
        }

        public Criteria andAutolightIn(List<String> values) {
            addCriterion("AutoLight in", values, "autolight");
            return (Criteria) this;
        }

        public Criteria andAutolightNotIn(List<String> values) {
            addCriterion("AutoLight not in", values, "autolight");
            return (Criteria) this;
        }

        public Criteria andAutolightBetween(String value1, String value2) {
            addCriterion("AutoLight between", value1, value2, "autolight");
            return (Criteria) this;
        }

        public Criteria andAutolightNotBetween(String value1, String value2) {
            addCriterion("AutoLight not between", value1, value2, "autolight");
            return (Criteria) this;
        }

        public Criteria andCorneringlampIsNull() {
            addCriterion("CorneringLamp is null");
            return (Criteria) this;
        }

        public Criteria andCorneringlampIsNotNull() {
            addCriterion("CorneringLamp is not null");
            return (Criteria) this;
        }

        public Criteria andCorneringlampEqualTo(String value) {
            addCriterion("CorneringLamp =", value, "corneringlamp");
            return (Criteria) this;
        }

        public Criteria andCorneringlampNotEqualTo(String value) {
            addCriterion("CorneringLamp <>", value, "corneringlamp");
            return (Criteria) this;
        }

        public Criteria andCorneringlampGreaterThan(String value) {
            addCriterion("CorneringLamp >", value, "corneringlamp");
            return (Criteria) this;
        }

        public Criteria andCorneringlampGreaterThanOrEqualTo(String value) {
            addCriterion("CorneringLamp >=", value, "corneringlamp");
            return (Criteria) this;
        }

        public Criteria andCorneringlampLessThan(String value) {
            addCriterion("CorneringLamp <", value, "corneringlamp");
            return (Criteria) this;
        }

        public Criteria andCorneringlampLessThanOrEqualTo(String value) {
            addCriterion("CorneringLamp <=", value, "corneringlamp");
            return (Criteria) this;
        }

        public Criteria andCorneringlampLike(String value) {
            addCriterion("CorneringLamp like", value, "corneringlamp");
            return (Criteria) this;
        }

        public Criteria andCorneringlampNotLike(String value) {
            addCriterion("CorneringLamp not like", value, "corneringlamp");
            return (Criteria) this;
        }

        public Criteria andCorneringlampIn(List<String> values) {
            addCriterion("CorneringLamp in", values, "corneringlamp");
            return (Criteria) this;
        }

        public Criteria andCorneringlampNotIn(List<String> values) {
            addCriterion("CorneringLamp not in", values, "corneringlamp");
            return (Criteria) this;
        }

        public Criteria andCorneringlampBetween(String value1, String value2) {
            addCriterion("CorneringLamp between", value1, value2, "corneringlamp");
            return (Criteria) this;
        }

        public Criteria andCorneringlampNotBetween(String value1, String value2) {
            addCriterion("CorneringLamp not between", value1, value2, "corneringlamp");
            return (Criteria) this;
        }

        public Criteria andSteeringheadlampIsNull() {
            addCriterion("SteeringHeadLamp is null");
            return (Criteria) this;
        }

        public Criteria andSteeringheadlampIsNotNull() {
            addCriterion("SteeringHeadLamp is not null");
            return (Criteria) this;
        }

        public Criteria andSteeringheadlampEqualTo(String value) {
            addCriterion("SteeringHeadLamp =", value, "steeringheadlamp");
            return (Criteria) this;
        }

        public Criteria andSteeringheadlampNotEqualTo(String value) {
            addCriterion("SteeringHeadLamp <>", value, "steeringheadlamp");
            return (Criteria) this;
        }

        public Criteria andSteeringheadlampGreaterThan(String value) {
            addCriterion("SteeringHeadLamp >", value, "steeringheadlamp");
            return (Criteria) this;
        }

        public Criteria andSteeringheadlampGreaterThanOrEqualTo(String value) {
            addCriterion("SteeringHeadLamp >=", value, "steeringheadlamp");
            return (Criteria) this;
        }

        public Criteria andSteeringheadlampLessThan(String value) {
            addCriterion("SteeringHeadLamp <", value, "steeringheadlamp");
            return (Criteria) this;
        }

        public Criteria andSteeringheadlampLessThanOrEqualTo(String value) {
            addCriterion("SteeringHeadLamp <=", value, "steeringheadlamp");
            return (Criteria) this;
        }

        public Criteria andSteeringheadlampLike(String value) {
            addCriterion("SteeringHeadLamp like", value, "steeringheadlamp");
            return (Criteria) this;
        }

        public Criteria andSteeringheadlampNotLike(String value) {
            addCriterion("SteeringHeadLamp not like", value, "steeringheadlamp");
            return (Criteria) this;
        }

        public Criteria andSteeringheadlampIn(List<String> values) {
            addCriterion("SteeringHeadLamp in", values, "steeringheadlamp");
            return (Criteria) this;
        }

        public Criteria andSteeringheadlampNotIn(List<String> values) {
            addCriterion("SteeringHeadLamp not in", values, "steeringheadlamp");
            return (Criteria) this;
        }

        public Criteria andSteeringheadlampBetween(String value1, String value2) {
            addCriterion("SteeringHeadLamp between", value1, value2, "steeringheadlamp");
            return (Criteria) this;
        }

        public Criteria andSteeringheadlampNotBetween(String value1, String value2) {
            addCriterion("SteeringHeadLamp not between", value1, value2, "steeringheadlamp");
            return (Criteria) this;
        }

        public Criteria andFrontfoglampIsNull() {
            addCriterion("FrontFogLamp is null");
            return (Criteria) this;
        }

        public Criteria andFrontfoglampIsNotNull() {
            addCriterion("FrontFogLamp is not null");
            return (Criteria) this;
        }

        public Criteria andFrontfoglampEqualTo(String value) {
            addCriterion("FrontFogLamp =", value, "frontfoglamp");
            return (Criteria) this;
        }

        public Criteria andFrontfoglampNotEqualTo(String value) {
            addCriterion("FrontFogLamp <>", value, "frontfoglamp");
            return (Criteria) this;
        }

        public Criteria andFrontfoglampGreaterThan(String value) {
            addCriterion("FrontFogLamp >", value, "frontfoglamp");
            return (Criteria) this;
        }

        public Criteria andFrontfoglampGreaterThanOrEqualTo(String value) {
            addCriterion("FrontFogLamp >=", value, "frontfoglamp");
            return (Criteria) this;
        }

        public Criteria andFrontfoglampLessThan(String value) {
            addCriterion("FrontFogLamp <", value, "frontfoglamp");
            return (Criteria) this;
        }

        public Criteria andFrontfoglampLessThanOrEqualTo(String value) {
            addCriterion("FrontFogLamp <=", value, "frontfoglamp");
            return (Criteria) this;
        }

        public Criteria andFrontfoglampLike(String value) {
            addCriterion("FrontFogLamp like", value, "frontfoglamp");
            return (Criteria) this;
        }

        public Criteria andFrontfoglampNotLike(String value) {
            addCriterion("FrontFogLamp not like", value, "frontfoglamp");
            return (Criteria) this;
        }

        public Criteria andFrontfoglampIn(List<String> values) {
            addCriterion("FrontFogLamp in", values, "frontfoglamp");
            return (Criteria) this;
        }

        public Criteria andFrontfoglampNotIn(List<String> values) {
            addCriterion("FrontFogLamp not in", values, "frontfoglamp");
            return (Criteria) this;
        }

        public Criteria andFrontfoglampBetween(String value1, String value2) {
            addCriterion("FrontFogLamp between", value1, value2, "frontfoglamp");
            return (Criteria) this;
        }

        public Criteria andFrontfoglampNotBetween(String value1, String value2) {
            addCriterion("FrontFogLamp not between", value1, value2, "frontfoglamp");
            return (Criteria) this;
        }

        public Criteria andTheheadlampheightisadjustableIsNull() {
            addCriterion("TheHeadlampHeightIsAdjustable is null");
            return (Criteria) this;
        }

        public Criteria andTheheadlampheightisadjustableIsNotNull() {
            addCriterion("TheHeadlampHeightIsAdjustable is not null");
            return (Criteria) this;
        }

        public Criteria andTheheadlampheightisadjustableEqualTo(String value) {
            addCriterion("TheHeadlampHeightIsAdjustable =", value, "theheadlampheightisadjustable");
            return (Criteria) this;
        }

        public Criteria andTheheadlampheightisadjustableNotEqualTo(String value) {
            addCriterion("TheHeadlampHeightIsAdjustable <>", value, "theheadlampheightisadjustable");
            return (Criteria) this;
        }

        public Criteria andTheheadlampheightisadjustableGreaterThan(String value) {
            addCriterion("TheHeadlampHeightIsAdjustable >", value, "theheadlampheightisadjustable");
            return (Criteria) this;
        }

        public Criteria andTheheadlampheightisadjustableGreaterThanOrEqualTo(String value) {
            addCriterion("TheHeadlampHeightIsAdjustable >=", value, "theheadlampheightisadjustable");
            return (Criteria) this;
        }

        public Criteria andTheheadlampheightisadjustableLessThan(String value) {
            addCriterion("TheHeadlampHeightIsAdjustable <", value, "theheadlampheightisadjustable");
            return (Criteria) this;
        }

        public Criteria andTheheadlampheightisadjustableLessThanOrEqualTo(String value) {
            addCriterion("TheHeadlampHeightIsAdjustable <=", value, "theheadlampheightisadjustable");
            return (Criteria) this;
        }

        public Criteria andTheheadlampheightisadjustableLike(String value) {
            addCriterion("TheHeadlampHeightIsAdjustable like", value, "theheadlampheightisadjustable");
            return (Criteria) this;
        }

        public Criteria andTheheadlampheightisadjustableNotLike(String value) {
            addCriterion("TheHeadlampHeightIsAdjustable not like", value, "theheadlampheightisadjustable");
            return (Criteria) this;
        }

        public Criteria andTheheadlampheightisadjustableIn(List<String> values) {
            addCriterion("TheHeadlampHeightIsAdjustable in", values, "theheadlampheightisadjustable");
            return (Criteria) this;
        }

        public Criteria andTheheadlampheightisadjustableNotIn(List<String> values) {
            addCriterion("TheHeadlampHeightIsAdjustable not in", values, "theheadlampheightisadjustable");
            return (Criteria) this;
        }

        public Criteria andTheheadlampheightisadjustableBetween(String value1, String value2) {
            addCriterion("TheHeadlampHeightIsAdjustable between", value1, value2, "theheadlampheightisadjustable");
            return (Criteria) this;
        }

        public Criteria andTheheadlampheightisadjustableNotBetween(String value1, String value2) {
            addCriterion("TheHeadlampHeightIsAdjustable not between", value1, value2, "theheadlampheightisadjustable");
            return (Criteria) this;
        }

        public Criteria andHeadlampcleaningdeviceIsNull() {
            addCriterion("HeadlampCleaningDevice is null");
            return (Criteria) this;
        }

        public Criteria andHeadlampcleaningdeviceIsNotNull() {
            addCriterion("HeadlampCleaningDevice is not null");
            return (Criteria) this;
        }

        public Criteria andHeadlampcleaningdeviceEqualTo(String value) {
            addCriterion("HeadlampCleaningDevice =", value, "headlampcleaningdevice");
            return (Criteria) this;
        }

        public Criteria andHeadlampcleaningdeviceNotEqualTo(String value) {
            addCriterion("HeadlampCleaningDevice <>", value, "headlampcleaningdevice");
            return (Criteria) this;
        }

        public Criteria andHeadlampcleaningdeviceGreaterThan(String value) {
            addCriterion("HeadlampCleaningDevice >", value, "headlampcleaningdevice");
            return (Criteria) this;
        }

        public Criteria andHeadlampcleaningdeviceGreaterThanOrEqualTo(String value) {
            addCriterion("HeadlampCleaningDevice >=", value, "headlampcleaningdevice");
            return (Criteria) this;
        }

        public Criteria andHeadlampcleaningdeviceLessThan(String value) {
            addCriterion("HeadlampCleaningDevice <", value, "headlampcleaningdevice");
            return (Criteria) this;
        }

        public Criteria andHeadlampcleaningdeviceLessThanOrEqualTo(String value) {
            addCriterion("HeadlampCleaningDevice <=", value, "headlampcleaningdevice");
            return (Criteria) this;
        }

        public Criteria andHeadlampcleaningdeviceLike(String value) {
            addCriterion("HeadlampCleaningDevice like", value, "headlampcleaningdevice");
            return (Criteria) this;
        }

        public Criteria andHeadlampcleaningdeviceNotLike(String value) {
            addCriterion("HeadlampCleaningDevice not like", value, "headlampcleaningdevice");
            return (Criteria) this;
        }

        public Criteria andHeadlampcleaningdeviceIn(List<String> values) {
            addCriterion("HeadlampCleaningDevice in", values, "headlampcleaningdevice");
            return (Criteria) this;
        }

        public Criteria andHeadlampcleaningdeviceNotIn(List<String> values) {
            addCriterion("HeadlampCleaningDevice not in", values, "headlampcleaningdevice");
            return (Criteria) this;
        }

        public Criteria andHeadlampcleaningdeviceBetween(String value1, String value2) {
            addCriterion("HeadlampCleaningDevice between", value1, value2, "headlampcleaningdevice");
            return (Criteria) this;
        }

        public Criteria andHeadlampcleaningdeviceNotBetween(String value1, String value2) {
            addCriterion("HeadlampCleaningDevice not between", value1, value2, "headlampcleaningdevice");
            return (Criteria) this;
        }

        public Criteria andInterioratmospherelampIsNull() {
            addCriterion("InteriorAtmosphereLamp is null");
            return (Criteria) this;
        }

        public Criteria andInterioratmospherelampIsNotNull() {
            addCriterion("InteriorAtmosphereLamp is not null");
            return (Criteria) this;
        }

        public Criteria andInterioratmospherelampEqualTo(String value) {
            addCriterion("InteriorAtmosphereLamp =", value, "interioratmospherelamp");
            return (Criteria) this;
        }

        public Criteria andInterioratmospherelampNotEqualTo(String value) {
            addCriterion("InteriorAtmosphereLamp <>", value, "interioratmospherelamp");
            return (Criteria) this;
        }

        public Criteria andInterioratmospherelampGreaterThan(String value) {
            addCriterion("InteriorAtmosphereLamp >", value, "interioratmospherelamp");
            return (Criteria) this;
        }

        public Criteria andInterioratmospherelampGreaterThanOrEqualTo(String value) {
            addCriterion("InteriorAtmosphereLamp >=", value, "interioratmospherelamp");
            return (Criteria) this;
        }

        public Criteria andInterioratmospherelampLessThan(String value) {
            addCriterion("InteriorAtmosphereLamp <", value, "interioratmospherelamp");
            return (Criteria) this;
        }

        public Criteria andInterioratmospherelampLessThanOrEqualTo(String value) {
            addCriterion("InteriorAtmosphereLamp <=", value, "interioratmospherelamp");
            return (Criteria) this;
        }

        public Criteria andInterioratmospherelampLike(String value) {
            addCriterion("InteriorAtmosphereLamp like", value, "interioratmospherelamp");
            return (Criteria) this;
        }

        public Criteria andInterioratmospherelampNotLike(String value) {
            addCriterion("InteriorAtmosphereLamp not like", value, "interioratmospherelamp");
            return (Criteria) this;
        }

        public Criteria andInterioratmospherelampIn(List<String> values) {
            addCriterion("InteriorAtmosphereLamp in", values, "interioratmospherelamp");
            return (Criteria) this;
        }

        public Criteria andInterioratmospherelampNotIn(List<String> values) {
            addCriterion("InteriorAtmosphereLamp not in", values, "interioratmospherelamp");
            return (Criteria) this;
        }

        public Criteria andInterioratmospherelampBetween(String value1, String value2) {
            addCriterion("InteriorAtmosphereLamp between", value1, value2, "interioratmospherelamp");
            return (Criteria) this;
        }

        public Criteria andInterioratmospherelampNotBetween(String value1, String value2) {
            addCriterion("InteriorAtmosphereLamp not between", value1, value2, "interioratmospherelamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table light_configuration
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table light_configuration
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}