package com.car.pojo;

import java.util.ArrayList;
import java.util.List;

public class Media_configurationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table media_configuration
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table media_configuration
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table media_configuration
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_configuration
     *
     * @mbg.generated
     */
    public Media_configurationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_configuration
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_configuration
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_configuration
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_configuration
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_configuration
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_configuration
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_configuration
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_configuration
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_configuration
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table media_configuration
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table media_configuration
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNumIsNull() {
            addCriterion("Num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("Num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("Num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("Num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("Num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("Num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("Num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("Num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("Num like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("Num not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("Num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("Num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("Num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("Num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andGpsIsNull() {
            addCriterion("GPS is null");
            return (Criteria) this;
        }

        public Criteria andGpsIsNotNull() {
            addCriterion("GPS is not null");
            return (Criteria) this;
        }

        public Criteria andGpsEqualTo(String value) {
            addCriterion("GPS =", value, "gps");
            return (Criteria) this;
        }

        public Criteria andGpsNotEqualTo(String value) {
            addCriterion("GPS <>", value, "gps");
            return (Criteria) this;
        }

        public Criteria andGpsGreaterThan(String value) {
            addCriterion("GPS >", value, "gps");
            return (Criteria) this;
        }

        public Criteria andGpsGreaterThanOrEqualTo(String value) {
            addCriterion("GPS >=", value, "gps");
            return (Criteria) this;
        }

        public Criteria andGpsLessThan(String value) {
            addCriterion("GPS <", value, "gps");
            return (Criteria) this;
        }

        public Criteria andGpsLessThanOrEqualTo(String value) {
            addCriterion("GPS <=", value, "gps");
            return (Criteria) this;
        }

        public Criteria andGpsLike(String value) {
            addCriterion("GPS like", value, "gps");
            return (Criteria) this;
        }

        public Criteria andGpsNotLike(String value) {
            addCriterion("GPS not like", value, "gps");
            return (Criteria) this;
        }

        public Criteria andGpsIn(List<String> values) {
            addCriterion("GPS in", values, "gps");
            return (Criteria) this;
        }

        public Criteria andGpsNotIn(List<String> values) {
            addCriterion("GPS not in", values, "gps");
            return (Criteria) this;
        }

        public Criteria andGpsBetween(String value1, String value2) {
            addCriterion("GPS between", value1, value2, "gps");
            return (Criteria) this;
        }

        public Criteria andGpsNotBetween(String value1, String value2) {
            addCriterion("GPS not between", value1, value2, "gps");
            return (Criteria) this;
        }

        public Criteria andLocationinteractiveserviceIsNull() {
            addCriterion("LocationInteractiveService is null");
            return (Criteria) this;
        }

        public Criteria andLocationinteractiveserviceIsNotNull() {
            addCriterion("LocationInteractiveService is not null");
            return (Criteria) this;
        }

        public Criteria andLocationinteractiveserviceEqualTo(String value) {
            addCriterion("LocationInteractiveService =", value, "locationinteractiveservice");
            return (Criteria) this;
        }

        public Criteria andLocationinteractiveserviceNotEqualTo(String value) {
            addCriterion("LocationInteractiveService <>", value, "locationinteractiveservice");
            return (Criteria) this;
        }

        public Criteria andLocationinteractiveserviceGreaterThan(String value) {
            addCriterion("LocationInteractiveService >", value, "locationinteractiveservice");
            return (Criteria) this;
        }

        public Criteria andLocationinteractiveserviceGreaterThanOrEqualTo(String value) {
            addCriterion("LocationInteractiveService >=", value, "locationinteractiveservice");
            return (Criteria) this;
        }

        public Criteria andLocationinteractiveserviceLessThan(String value) {
            addCriterion("LocationInteractiveService <", value, "locationinteractiveservice");
            return (Criteria) this;
        }

        public Criteria andLocationinteractiveserviceLessThanOrEqualTo(String value) {
            addCriterion("LocationInteractiveService <=", value, "locationinteractiveservice");
            return (Criteria) this;
        }

        public Criteria andLocationinteractiveserviceLike(String value) {
            addCriterion("LocationInteractiveService like", value, "locationinteractiveservice");
            return (Criteria) this;
        }

        public Criteria andLocationinteractiveserviceNotLike(String value) {
            addCriterion("LocationInteractiveService not like", value, "locationinteractiveservice");
            return (Criteria) this;
        }

        public Criteria andLocationinteractiveserviceIn(List<String> values) {
            addCriterion("LocationInteractiveService in", values, "locationinteractiveservice");
            return (Criteria) this;
        }

        public Criteria andLocationinteractiveserviceNotIn(List<String> values) {
            addCriterion("LocationInteractiveService not in", values, "locationinteractiveservice");
            return (Criteria) this;
        }

        public Criteria andLocationinteractiveserviceBetween(String value1, String value2) {
            addCriterion("LocationInteractiveService between", value1, value2, "locationinteractiveservice");
            return (Criteria) this;
        }

        public Criteria andLocationinteractiveserviceNotBetween(String value1, String value2) {
            addCriterion("LocationInteractiveService not between", value1, value2, "locationinteractiveservice");
            return (Criteria) this;
        }

        public Criteria andCenterconsolelargecolorscreenIsNull() {
            addCriterion("CenterConsoleLargeColorScreen is null");
            return (Criteria) this;
        }

        public Criteria andCenterconsolelargecolorscreenIsNotNull() {
            addCriterion("CenterConsoleLargeColorScreen is not null");
            return (Criteria) this;
        }

        public Criteria andCenterconsolelargecolorscreenEqualTo(String value) {
            addCriterion("CenterConsoleLargeColorScreen =", value, "centerconsolelargecolorscreen");
            return (Criteria) this;
        }

        public Criteria andCenterconsolelargecolorscreenNotEqualTo(String value) {
            addCriterion("CenterConsoleLargeColorScreen <>", value, "centerconsolelargecolorscreen");
            return (Criteria) this;
        }

        public Criteria andCenterconsolelargecolorscreenGreaterThan(String value) {
            addCriterion("CenterConsoleLargeColorScreen >", value, "centerconsolelargecolorscreen");
            return (Criteria) this;
        }

        public Criteria andCenterconsolelargecolorscreenGreaterThanOrEqualTo(String value) {
            addCriterion("CenterConsoleLargeColorScreen >=", value, "centerconsolelargecolorscreen");
            return (Criteria) this;
        }

        public Criteria andCenterconsolelargecolorscreenLessThan(String value) {
            addCriterion("CenterConsoleLargeColorScreen <", value, "centerconsolelargecolorscreen");
            return (Criteria) this;
        }

        public Criteria andCenterconsolelargecolorscreenLessThanOrEqualTo(String value) {
            addCriterion("CenterConsoleLargeColorScreen <=", value, "centerconsolelargecolorscreen");
            return (Criteria) this;
        }

        public Criteria andCenterconsolelargecolorscreenLike(String value) {
            addCriterion("CenterConsoleLargeColorScreen like", value, "centerconsolelargecolorscreen");
            return (Criteria) this;
        }

        public Criteria andCenterconsolelargecolorscreenNotLike(String value) {
            addCriterion("CenterConsoleLargeColorScreen not like", value, "centerconsolelargecolorscreen");
            return (Criteria) this;
        }

        public Criteria andCenterconsolelargecolorscreenIn(List<String> values) {
            addCriterion("CenterConsoleLargeColorScreen in", values, "centerconsolelargecolorscreen");
            return (Criteria) this;
        }

        public Criteria andCenterconsolelargecolorscreenNotIn(List<String> values) {
            addCriterion("CenterConsoleLargeColorScreen not in", values, "centerconsolelargecolorscreen");
            return (Criteria) this;
        }

        public Criteria andCenterconsolelargecolorscreenBetween(String value1, String value2) {
            addCriterion("CenterConsoleLargeColorScreen between", value1, value2, "centerconsolelargecolorscreen");
            return (Criteria) this;
        }

        public Criteria andCenterconsolelargecolorscreenNotBetween(String value1, String value2) {
            addCriterion("CenterConsoleLargeColorScreen not between", value1, value2, "centerconsolelargecolorscreen");
            return (Criteria) this;
        }

        public Criteria andBluetoothCarphoneIsNull() {
            addCriterion("Bluetooth_carPhone is null");
            return (Criteria) this;
        }

        public Criteria andBluetoothCarphoneIsNotNull() {
            addCriterion("Bluetooth_carPhone is not null");
            return (Criteria) this;
        }

        public Criteria andBluetoothCarphoneEqualTo(String value) {
            addCriterion("Bluetooth_carPhone =", value, "bluetoothCarphone");
            return (Criteria) this;
        }

        public Criteria andBluetoothCarphoneNotEqualTo(String value) {
            addCriterion("Bluetooth_carPhone <>", value, "bluetoothCarphone");
            return (Criteria) this;
        }

        public Criteria andBluetoothCarphoneGreaterThan(String value) {
            addCriterion("Bluetooth_carPhone >", value, "bluetoothCarphone");
            return (Criteria) this;
        }

        public Criteria andBluetoothCarphoneGreaterThanOrEqualTo(String value) {
            addCriterion("Bluetooth_carPhone >=", value, "bluetoothCarphone");
            return (Criteria) this;
        }

        public Criteria andBluetoothCarphoneLessThan(String value) {
            addCriterion("Bluetooth_carPhone <", value, "bluetoothCarphone");
            return (Criteria) this;
        }

        public Criteria andBluetoothCarphoneLessThanOrEqualTo(String value) {
            addCriterion("Bluetooth_carPhone <=", value, "bluetoothCarphone");
            return (Criteria) this;
        }

        public Criteria andBluetoothCarphoneLike(String value) {
            addCriterion("Bluetooth_carPhone like", value, "bluetoothCarphone");
            return (Criteria) this;
        }

        public Criteria andBluetoothCarphoneNotLike(String value) {
            addCriterion("Bluetooth_carPhone not like", value, "bluetoothCarphone");
            return (Criteria) this;
        }

        public Criteria andBluetoothCarphoneIn(List<String> values) {
            addCriterion("Bluetooth_carPhone in", values, "bluetoothCarphone");
            return (Criteria) this;
        }

        public Criteria andBluetoothCarphoneNotIn(List<String> values) {
            addCriterion("Bluetooth_carPhone not in", values, "bluetoothCarphone");
            return (Criteria) this;
        }

        public Criteria andBluetoothCarphoneBetween(String value1, String value2) {
            addCriterion("Bluetooth_carPhone between", value1, value2, "bluetoothCarphone");
            return (Criteria) this;
        }

        public Criteria andBluetoothCarphoneNotBetween(String value1, String value2) {
            addCriterion("Bluetooth_carPhone not between", value1, value2, "bluetoothCarphone");
            return (Criteria) this;
        }

        public Criteria andTvIsNull() {
            addCriterion("TV is null");
            return (Criteria) this;
        }

        public Criteria andTvIsNotNull() {
            addCriterion("TV is not null");
            return (Criteria) this;
        }

        public Criteria andTvEqualTo(String value) {
            addCriterion("TV =", value, "tv");
            return (Criteria) this;
        }

        public Criteria andTvNotEqualTo(String value) {
            addCriterion("TV <>", value, "tv");
            return (Criteria) this;
        }

        public Criteria andTvGreaterThan(String value) {
            addCriterion("TV >", value, "tv");
            return (Criteria) this;
        }

        public Criteria andTvGreaterThanOrEqualTo(String value) {
            addCriterion("TV >=", value, "tv");
            return (Criteria) this;
        }

        public Criteria andTvLessThan(String value) {
            addCriterion("TV <", value, "tv");
            return (Criteria) this;
        }

        public Criteria andTvLessThanOrEqualTo(String value) {
            addCriterion("TV <=", value, "tv");
            return (Criteria) this;
        }

        public Criteria andTvLike(String value) {
            addCriterion("TV like", value, "tv");
            return (Criteria) this;
        }

        public Criteria andTvNotLike(String value) {
            addCriterion("TV not like", value, "tv");
            return (Criteria) this;
        }

        public Criteria andTvIn(List<String> values) {
            addCriterion("TV in", values, "tv");
            return (Criteria) this;
        }

        public Criteria andTvNotIn(List<String> values) {
            addCriterion("TV not in", values, "tv");
            return (Criteria) this;
        }

        public Criteria andTvBetween(String value1, String value2) {
            addCriterion("TV between", value1, value2, "tv");
            return (Criteria) this;
        }

        public Criteria andTvNotBetween(String value1, String value2) {
            addCriterion("TV not between", value1, value2, "tv");
            return (Criteria) this;
        }

        public Criteria andRearlcdIsNull() {
            addCriterion("RearLCD is null");
            return (Criteria) this;
        }

        public Criteria andRearlcdIsNotNull() {
            addCriterion("RearLCD is not null");
            return (Criteria) this;
        }

        public Criteria andRearlcdEqualTo(String value) {
            addCriterion("RearLCD =", value, "rearlcd");
            return (Criteria) this;
        }

        public Criteria andRearlcdNotEqualTo(String value) {
            addCriterion("RearLCD <>", value, "rearlcd");
            return (Criteria) this;
        }

        public Criteria andRearlcdGreaterThan(String value) {
            addCriterion("RearLCD >", value, "rearlcd");
            return (Criteria) this;
        }

        public Criteria andRearlcdGreaterThanOrEqualTo(String value) {
            addCriterion("RearLCD >=", value, "rearlcd");
            return (Criteria) this;
        }

        public Criteria andRearlcdLessThan(String value) {
            addCriterion("RearLCD <", value, "rearlcd");
            return (Criteria) this;
        }

        public Criteria andRearlcdLessThanOrEqualTo(String value) {
            addCriterion("RearLCD <=", value, "rearlcd");
            return (Criteria) this;
        }

        public Criteria andRearlcdLike(String value) {
            addCriterion("RearLCD like", value, "rearlcd");
            return (Criteria) this;
        }

        public Criteria andRearlcdNotLike(String value) {
            addCriterion("RearLCD not like", value, "rearlcd");
            return (Criteria) this;
        }

        public Criteria andRearlcdIn(List<String> values) {
            addCriterion("RearLCD in", values, "rearlcd");
            return (Criteria) this;
        }

        public Criteria andRearlcdNotIn(List<String> values) {
            addCriterion("RearLCD not in", values, "rearlcd");
            return (Criteria) this;
        }

        public Criteria andRearlcdBetween(String value1, String value2) {
            addCriterion("RearLCD between", value1, value2, "rearlcd");
            return (Criteria) this;
        }

        public Criteria andRearlcdNotBetween(String value1, String value2) {
            addCriterion("RearLCD not between", value1, value2, "rearlcd");
            return (Criteria) this;
        }

        public Criteria andPowersupply220v230vIsNull() {
            addCriterion("powersupply220v230v is null");
            return (Criteria) this;
        }

        public Criteria andPowersupply220v230vIsNotNull() {
            addCriterion("powersupply220v230v is not null");
            return (Criteria) this;
        }

        public Criteria andPowersupply220v230vEqualTo(String value) {
            addCriterion("powersupply220v230v =", value, "powersupply220v230v");
            return (Criteria) this;
        }

        public Criteria andPowersupply220v230vNotEqualTo(String value) {
            addCriterion("powersupply220v230v <>", value, "powersupply220v230v");
            return (Criteria) this;
        }

        public Criteria andPowersupply220v230vGreaterThan(String value) {
            addCriterion("powersupply220v230v >", value, "powersupply220v230v");
            return (Criteria) this;
        }

        public Criteria andPowersupply220v230vGreaterThanOrEqualTo(String value) {
            addCriterion("powersupply220v230v >=", value, "powersupply220v230v");
            return (Criteria) this;
        }

        public Criteria andPowersupply220v230vLessThan(String value) {
            addCriterion("powersupply220v230v <", value, "powersupply220v230v");
            return (Criteria) this;
        }

        public Criteria andPowersupply220v230vLessThanOrEqualTo(String value) {
            addCriterion("powersupply220v230v <=", value, "powersupply220v230v");
            return (Criteria) this;
        }

        public Criteria andPowersupply220v230vLike(String value) {
            addCriterion("powersupply220v230v like", value, "powersupply220v230v");
            return (Criteria) this;
        }

        public Criteria andPowersupply220v230vNotLike(String value) {
            addCriterion("powersupply220v230v not like", value, "powersupply220v230v");
            return (Criteria) this;
        }

        public Criteria andPowersupply220v230vIn(List<String> values) {
            addCriterion("powersupply220v230v in", values, "powersupply220v230v");
            return (Criteria) this;
        }

        public Criteria andPowersupply220v230vNotIn(List<String> values) {
            addCriterion("powersupply220v230v not in", values, "powersupply220v230v");
            return (Criteria) this;
        }

        public Criteria andPowersupply220v230vBetween(String value1, String value2) {
            addCriterion("powersupply220v230v between", value1, value2, "powersupply220v230v");
            return (Criteria) this;
        }

        public Criteria andPowersupply220v230vNotBetween(String value1, String value2) {
            addCriterion("powersupply220v230v not between", value1, value2, "powersupply220v230v");
            return (Criteria) this;
        }

        public Criteria andExternalaudiosourceinterfaceIsNull() {
            addCriterion("ExternalAudioSourceInterface is null");
            return (Criteria) this;
        }

        public Criteria andExternalaudiosourceinterfaceIsNotNull() {
            addCriterion("ExternalAudioSourceInterface is not null");
            return (Criteria) this;
        }

        public Criteria andExternalaudiosourceinterfaceEqualTo(String value) {
            addCriterion("ExternalAudioSourceInterface =", value, "externalaudiosourceinterface");
            return (Criteria) this;
        }

        public Criteria andExternalaudiosourceinterfaceNotEqualTo(String value) {
            addCriterion("ExternalAudioSourceInterface <>", value, "externalaudiosourceinterface");
            return (Criteria) this;
        }

        public Criteria andExternalaudiosourceinterfaceGreaterThan(String value) {
            addCriterion("ExternalAudioSourceInterface >", value, "externalaudiosourceinterface");
            return (Criteria) this;
        }

        public Criteria andExternalaudiosourceinterfaceGreaterThanOrEqualTo(String value) {
            addCriterion("ExternalAudioSourceInterface >=", value, "externalaudiosourceinterface");
            return (Criteria) this;
        }

        public Criteria andExternalaudiosourceinterfaceLessThan(String value) {
            addCriterion("ExternalAudioSourceInterface <", value, "externalaudiosourceinterface");
            return (Criteria) this;
        }

        public Criteria andExternalaudiosourceinterfaceLessThanOrEqualTo(String value) {
            addCriterion("ExternalAudioSourceInterface <=", value, "externalaudiosourceinterface");
            return (Criteria) this;
        }

        public Criteria andExternalaudiosourceinterfaceLike(String value) {
            addCriterion("ExternalAudioSourceInterface like", value, "externalaudiosourceinterface");
            return (Criteria) this;
        }

        public Criteria andExternalaudiosourceinterfaceNotLike(String value) {
            addCriterion("ExternalAudioSourceInterface not like", value, "externalaudiosourceinterface");
            return (Criteria) this;
        }

        public Criteria andExternalaudiosourceinterfaceIn(List<String> values) {
            addCriterion("ExternalAudioSourceInterface in", values, "externalaudiosourceinterface");
            return (Criteria) this;
        }

        public Criteria andExternalaudiosourceinterfaceNotIn(List<String> values) {
            addCriterion("ExternalAudioSourceInterface not in", values, "externalaudiosourceinterface");
            return (Criteria) this;
        }

        public Criteria andExternalaudiosourceinterfaceBetween(String value1, String value2) {
            addCriterion("ExternalAudioSourceInterface between", value1, value2, "externalaudiosourceinterface");
            return (Criteria) this;
        }

        public Criteria andExternalaudiosourceinterfaceNotBetween(String value1, String value2) {
            addCriterion("ExternalAudioSourceInterface not between", value1, value2, "externalaudiosourceinterface");
            return (Criteria) this;
        }

        public Criteria andCdIsNull() {
            addCriterion("CD is null");
            return (Criteria) this;
        }

        public Criteria andCdIsNotNull() {
            addCriterion("CD is not null");
            return (Criteria) this;
        }

        public Criteria andCdEqualTo(String value) {
            addCriterion("CD =", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotEqualTo(String value) {
            addCriterion("CD <>", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdGreaterThan(String value) {
            addCriterion("CD >", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdGreaterThanOrEqualTo(String value) {
            addCriterion("CD >=", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdLessThan(String value) {
            addCriterion("CD <", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdLessThanOrEqualTo(String value) {
            addCriterion("CD <=", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdLike(String value) {
            addCriterion("CD like", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotLike(String value) {
            addCriterion("CD not like", value, "cd");
            return (Criteria) this;
        }

        public Criteria andCdIn(List<String> values) {
            addCriterion("CD in", values, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotIn(List<String> values) {
            addCriterion("CD not in", values, "cd");
            return (Criteria) this;
        }

        public Criteria andCdBetween(String value1, String value2) {
            addCriterion("CD between", value1, value2, "cd");
            return (Criteria) this;
        }

        public Criteria andCdNotBetween(String value1, String value2) {
            addCriterion("CD not between", value1, value2, "cd");
            return (Criteria) this;
        }

        public Criteria andMediasystemIsNull() {
            addCriterion("MediaSystem is null");
            return (Criteria) this;
        }

        public Criteria andMediasystemIsNotNull() {
            addCriterion("MediaSystem is not null");
            return (Criteria) this;
        }

        public Criteria andMediasystemEqualTo(String value) {
            addCriterion("MediaSystem =", value, "mediasystem");
            return (Criteria) this;
        }

        public Criteria andMediasystemNotEqualTo(String value) {
            addCriterion("MediaSystem <>", value, "mediasystem");
            return (Criteria) this;
        }

        public Criteria andMediasystemGreaterThan(String value) {
            addCriterion("MediaSystem >", value, "mediasystem");
            return (Criteria) this;
        }

        public Criteria andMediasystemGreaterThanOrEqualTo(String value) {
            addCriterion("MediaSystem >=", value, "mediasystem");
            return (Criteria) this;
        }

        public Criteria andMediasystemLessThan(String value) {
            addCriterion("MediaSystem <", value, "mediasystem");
            return (Criteria) this;
        }

        public Criteria andMediasystemLessThanOrEqualTo(String value) {
            addCriterion("MediaSystem <=", value, "mediasystem");
            return (Criteria) this;
        }

        public Criteria andMediasystemLike(String value) {
            addCriterion("MediaSystem like", value, "mediasystem");
            return (Criteria) this;
        }

        public Criteria andMediasystemNotLike(String value) {
            addCriterion("MediaSystem not like", value, "mediasystem");
            return (Criteria) this;
        }

        public Criteria andMediasystemIn(List<String> values) {
            addCriterion("MediaSystem in", values, "mediasystem");
            return (Criteria) this;
        }

        public Criteria andMediasystemNotIn(List<String> values) {
            addCriterion("MediaSystem not in", values, "mediasystem");
            return (Criteria) this;
        }

        public Criteria andMediasystemBetween(String value1, String value2) {
            addCriterion("MediaSystem between", value1, value2, "mediasystem");
            return (Criteria) this;
        }

        public Criteria andMediasystemNotBetween(String value1, String value2) {
            addCriterion("MediaSystem not between", value1, value2, "mediasystem");
            return (Criteria) this;
        }

        public Criteria andDynaudioIsNull() {
            addCriterion("Dynaudio is null");
            return (Criteria) this;
        }

        public Criteria andDynaudioIsNotNull() {
            addCriterion("Dynaudio is not null");
            return (Criteria) this;
        }

        public Criteria andDynaudioEqualTo(String value) {
            addCriterion("Dynaudio =", value, "dynaudio");
            return (Criteria) this;
        }

        public Criteria andDynaudioNotEqualTo(String value) {
            addCriterion("Dynaudio <>", value, "dynaudio");
            return (Criteria) this;
        }

        public Criteria andDynaudioGreaterThan(String value) {
            addCriterion("Dynaudio >", value, "dynaudio");
            return (Criteria) this;
        }

        public Criteria andDynaudioGreaterThanOrEqualTo(String value) {
            addCriterion("Dynaudio >=", value, "dynaudio");
            return (Criteria) this;
        }

        public Criteria andDynaudioLessThan(String value) {
            addCriterion("Dynaudio <", value, "dynaudio");
            return (Criteria) this;
        }

        public Criteria andDynaudioLessThanOrEqualTo(String value) {
            addCriterion("Dynaudio <=", value, "dynaudio");
            return (Criteria) this;
        }

        public Criteria andDynaudioLike(String value) {
            addCriterion("Dynaudio like", value, "dynaudio");
            return (Criteria) this;
        }

        public Criteria andDynaudioNotLike(String value) {
            addCriterion("Dynaudio not like", value, "dynaudio");
            return (Criteria) this;
        }

        public Criteria andDynaudioIn(List<String> values) {
            addCriterion("Dynaudio in", values, "dynaudio");
            return (Criteria) this;
        }

        public Criteria andDynaudioNotIn(List<String> values) {
            addCriterion("Dynaudio not in", values, "dynaudio");
            return (Criteria) this;
        }

        public Criteria andDynaudioBetween(String value1, String value2) {
            addCriterion("Dynaudio between", value1, value2, "dynaudio");
            return (Criteria) this;
        }

        public Criteria andDynaudioNotBetween(String value1, String value2) {
            addCriterion("Dynaudio not between", value1, value2, "dynaudio");
            return (Criteria) this;
        }

        public Criteria andNumberofspeakersIsNull() {
            addCriterion("NumberOfSpeakers is null");
            return (Criteria) this;
        }

        public Criteria andNumberofspeakersIsNotNull() {
            addCriterion("NumberOfSpeakers is not null");
            return (Criteria) this;
        }

        public Criteria andNumberofspeakersEqualTo(String value) {
            addCriterion("NumberOfSpeakers =", value, "numberofspeakers");
            return (Criteria) this;
        }

        public Criteria andNumberofspeakersNotEqualTo(String value) {
            addCriterion("NumberOfSpeakers <>", value, "numberofspeakers");
            return (Criteria) this;
        }

        public Criteria andNumberofspeakersGreaterThan(String value) {
            addCriterion("NumberOfSpeakers >", value, "numberofspeakers");
            return (Criteria) this;
        }

        public Criteria andNumberofspeakersGreaterThanOrEqualTo(String value) {
            addCriterion("NumberOfSpeakers >=", value, "numberofspeakers");
            return (Criteria) this;
        }

        public Criteria andNumberofspeakersLessThan(String value) {
            addCriterion("NumberOfSpeakers <", value, "numberofspeakers");
            return (Criteria) this;
        }

        public Criteria andNumberofspeakersLessThanOrEqualTo(String value) {
            addCriterion("NumberOfSpeakers <=", value, "numberofspeakers");
            return (Criteria) this;
        }

        public Criteria andNumberofspeakersLike(String value) {
            addCriterion("NumberOfSpeakers like", value, "numberofspeakers");
            return (Criteria) this;
        }

        public Criteria andNumberofspeakersNotLike(String value) {
            addCriterion("NumberOfSpeakers not like", value, "numberofspeakers");
            return (Criteria) this;
        }

        public Criteria andNumberofspeakersIn(List<String> values) {
            addCriterion("NumberOfSpeakers in", values, "numberofspeakers");
            return (Criteria) this;
        }

        public Criteria andNumberofspeakersNotIn(List<String> values) {
            addCriterion("NumberOfSpeakers not in", values, "numberofspeakers");
            return (Criteria) this;
        }

        public Criteria andNumberofspeakersBetween(String value1, String value2) {
            addCriterion("NumberOfSpeakers between", value1, value2, "numberofspeakers");
            return (Criteria) this;
        }

        public Criteria andNumberofspeakersNotBetween(String value1, String value2) {
            addCriterion("NumberOfSpeakers not between", value1, value2, "numberofspeakers");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table media_configuration
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table media_configuration
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}