package com.car.pojo;

import java.util.ArrayList;
import java.util.List;

public class Safety_equipmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    public Safety_equipmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNumIsNull() {
            addCriterion("Num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("Num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(String value) {
            addCriterion("Num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(String value) {
            addCriterion("Num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(String value) {
            addCriterion("Num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(String value) {
            addCriterion("Num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(String value) {
            addCriterion("Num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(String value) {
            addCriterion("Num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLike(String value) {
            addCriterion("Num like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotLike(String value) {
            addCriterion("Num not like", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<String> values) {
            addCriterion("Num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<String> values) {
            addCriterion("Num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(String value1, String value2) {
            addCriterion("Num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(String value1, String value2) {
            addCriterion("Num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andMainSecondaryairbagIsNull() {
            addCriterion("Main_SecondaryAirbag is null");
            return (Criteria) this;
        }

        public Criteria andMainSecondaryairbagIsNotNull() {
            addCriterion("Main_SecondaryAirbag is not null");
            return (Criteria) this;
        }

        public Criteria andMainSecondaryairbagEqualTo(String value) {
            addCriterion("Main_SecondaryAirbag =", value, "mainSecondaryairbag");
            return (Criteria) this;
        }

        public Criteria andMainSecondaryairbagNotEqualTo(String value) {
            addCriterion("Main_SecondaryAirbag <>", value, "mainSecondaryairbag");
            return (Criteria) this;
        }

        public Criteria andMainSecondaryairbagGreaterThan(String value) {
            addCriterion("Main_SecondaryAirbag >", value, "mainSecondaryairbag");
            return (Criteria) this;
        }

        public Criteria andMainSecondaryairbagGreaterThanOrEqualTo(String value) {
            addCriterion("Main_SecondaryAirbag >=", value, "mainSecondaryairbag");
            return (Criteria) this;
        }

        public Criteria andMainSecondaryairbagLessThan(String value) {
            addCriterion("Main_SecondaryAirbag <", value, "mainSecondaryairbag");
            return (Criteria) this;
        }

        public Criteria andMainSecondaryairbagLessThanOrEqualTo(String value) {
            addCriterion("Main_SecondaryAirbag <=", value, "mainSecondaryairbag");
            return (Criteria) this;
        }

        public Criteria andMainSecondaryairbagLike(String value) {
            addCriterion("Main_SecondaryAirbag like", value, "mainSecondaryairbag");
            return (Criteria) this;
        }

        public Criteria andMainSecondaryairbagNotLike(String value) {
            addCriterion("Main_SecondaryAirbag not like", value, "mainSecondaryairbag");
            return (Criteria) this;
        }

        public Criteria andMainSecondaryairbagIn(List<String> values) {
            addCriterion("Main_SecondaryAirbag in", values, "mainSecondaryairbag");
            return (Criteria) this;
        }

        public Criteria andMainSecondaryairbagNotIn(List<String> values) {
            addCriterion("Main_SecondaryAirbag not in", values, "mainSecondaryairbag");
            return (Criteria) this;
        }

        public Criteria andMainSecondaryairbagBetween(String value1, String value2) {
            addCriterion("Main_SecondaryAirbag between", value1, value2, "mainSecondaryairbag");
            return (Criteria) this;
        }

        public Criteria andMainSecondaryairbagNotBetween(String value1, String value2) {
            addCriterion("Main_SecondaryAirbag not between", value1, value2, "mainSecondaryairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBacksideairbagIsNull() {
            addCriterion("Front_BackSideAirbag is null");
            return (Criteria) this;
        }

        public Criteria andFrontBacksideairbagIsNotNull() {
            addCriterion("Front_BackSideAirbag is not null");
            return (Criteria) this;
        }

        public Criteria andFrontBacksideairbagEqualTo(String value) {
            addCriterion("Front_BackSideAirbag =", value, "frontBacksideairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBacksideairbagNotEqualTo(String value) {
            addCriterion("Front_BackSideAirbag <>", value, "frontBacksideairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBacksideairbagGreaterThan(String value) {
            addCriterion("Front_BackSideAirbag >", value, "frontBacksideairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBacksideairbagGreaterThanOrEqualTo(String value) {
            addCriterion("Front_BackSideAirbag >=", value, "frontBacksideairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBacksideairbagLessThan(String value) {
            addCriterion("Front_BackSideAirbag <", value, "frontBacksideairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBacksideairbagLessThanOrEqualTo(String value) {
            addCriterion("Front_BackSideAirbag <=", value, "frontBacksideairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBacksideairbagLike(String value) {
            addCriterion("Front_BackSideAirbag like", value, "frontBacksideairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBacksideairbagNotLike(String value) {
            addCriterion("Front_BackSideAirbag not like", value, "frontBacksideairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBacksideairbagIn(List<String> values) {
            addCriterion("Front_BackSideAirbag in", values, "frontBacksideairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBacksideairbagNotIn(List<String> values) {
            addCriterion("Front_BackSideAirbag not in", values, "frontBacksideairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBacksideairbagBetween(String value1, String value2) {
            addCriterion("Front_BackSideAirbag between", value1, value2, "frontBacksideairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBacksideairbagNotBetween(String value1, String value2) {
            addCriterion("Front_BackSideAirbag not between", value1, value2, "frontBacksideairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBackheadairbagIsNull() {
            addCriterion("Front_BackHeadAirbag is null");
            return (Criteria) this;
        }

        public Criteria andFrontBackheadairbagIsNotNull() {
            addCriterion("Front_BackHeadAirbag is not null");
            return (Criteria) this;
        }

        public Criteria andFrontBackheadairbagEqualTo(String value) {
            addCriterion("Front_BackHeadAirbag =", value, "frontBackheadairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBackheadairbagNotEqualTo(String value) {
            addCriterion("Front_BackHeadAirbag <>", value, "frontBackheadairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBackheadairbagGreaterThan(String value) {
            addCriterion("Front_BackHeadAirbag >", value, "frontBackheadairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBackheadairbagGreaterThanOrEqualTo(String value) {
            addCriterion("Front_BackHeadAirbag >=", value, "frontBackheadairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBackheadairbagLessThan(String value) {
            addCriterion("Front_BackHeadAirbag <", value, "frontBackheadairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBackheadairbagLessThanOrEqualTo(String value) {
            addCriterion("Front_BackHeadAirbag <=", value, "frontBackheadairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBackheadairbagLike(String value) {
            addCriterion("Front_BackHeadAirbag like", value, "frontBackheadairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBackheadairbagNotLike(String value) {
            addCriterion("Front_BackHeadAirbag not like", value, "frontBackheadairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBackheadairbagIn(List<String> values) {
            addCriterion("Front_BackHeadAirbag in", values, "frontBackheadairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBackheadairbagNotIn(List<String> values) {
            addCriterion("Front_BackHeadAirbag not in", values, "frontBackheadairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBackheadairbagBetween(String value1, String value2) {
            addCriterion("Front_BackHeadAirbag between", value1, value2, "frontBackheadairbag");
            return (Criteria) this;
        }

        public Criteria andFrontBackheadairbagNotBetween(String value1, String value2) {
            addCriterion("Front_BackHeadAirbag not between", value1, value2, "frontBackheadairbag");
            return (Criteria) this;
        }

        public Criteria andKneeairbagIsNull() {
            addCriterion("KneeAirbag is null");
            return (Criteria) this;
        }

        public Criteria andKneeairbagIsNotNull() {
            addCriterion("KneeAirbag is not null");
            return (Criteria) this;
        }

        public Criteria andKneeairbagEqualTo(String value) {
            addCriterion("KneeAirbag =", value, "kneeairbag");
            return (Criteria) this;
        }

        public Criteria andKneeairbagNotEqualTo(String value) {
            addCriterion("KneeAirbag <>", value, "kneeairbag");
            return (Criteria) this;
        }

        public Criteria andKneeairbagGreaterThan(String value) {
            addCriterion("KneeAirbag >", value, "kneeairbag");
            return (Criteria) this;
        }

        public Criteria andKneeairbagGreaterThanOrEqualTo(String value) {
            addCriterion("KneeAirbag >=", value, "kneeairbag");
            return (Criteria) this;
        }

        public Criteria andKneeairbagLessThan(String value) {
            addCriterion("KneeAirbag <", value, "kneeairbag");
            return (Criteria) this;
        }

        public Criteria andKneeairbagLessThanOrEqualTo(String value) {
            addCriterion("KneeAirbag <=", value, "kneeairbag");
            return (Criteria) this;
        }

        public Criteria andKneeairbagLike(String value) {
            addCriterion("KneeAirbag like", value, "kneeairbag");
            return (Criteria) this;
        }

        public Criteria andKneeairbagNotLike(String value) {
            addCriterion("KneeAirbag not like", value, "kneeairbag");
            return (Criteria) this;
        }

        public Criteria andKneeairbagIn(List<String> values) {
            addCriterion("KneeAirbag in", values, "kneeairbag");
            return (Criteria) this;
        }

        public Criteria andKneeairbagNotIn(List<String> values) {
            addCriterion("KneeAirbag not in", values, "kneeairbag");
            return (Criteria) this;
        }

        public Criteria andKneeairbagBetween(String value1, String value2) {
            addCriterion("KneeAirbag between", value1, value2, "kneeairbag");
            return (Criteria) this;
        }

        public Criteria andKneeairbagNotBetween(String value1, String value2) {
            addCriterion("KneeAirbag not between", value1, value2, "kneeairbag");
            return (Criteria) this;
        }

        public Criteria andTirepressuremonitoringdeviceIsNull() {
            addCriterion("TirePressureMonitoringDevice is null");
            return (Criteria) this;
        }

        public Criteria andTirepressuremonitoringdeviceIsNotNull() {
            addCriterion("TirePressureMonitoringDevice is not null");
            return (Criteria) this;
        }

        public Criteria andTirepressuremonitoringdeviceEqualTo(String value) {
            addCriterion("TirePressureMonitoringDevice =", value, "tirepressuremonitoringdevice");
            return (Criteria) this;
        }

        public Criteria andTirepressuremonitoringdeviceNotEqualTo(String value) {
            addCriterion("TirePressureMonitoringDevice <>", value, "tirepressuremonitoringdevice");
            return (Criteria) this;
        }

        public Criteria andTirepressuremonitoringdeviceGreaterThan(String value) {
            addCriterion("TirePressureMonitoringDevice >", value, "tirepressuremonitoringdevice");
            return (Criteria) this;
        }

        public Criteria andTirepressuremonitoringdeviceGreaterThanOrEqualTo(String value) {
            addCriterion("TirePressureMonitoringDevice >=", value, "tirepressuremonitoringdevice");
            return (Criteria) this;
        }

        public Criteria andTirepressuremonitoringdeviceLessThan(String value) {
            addCriterion("TirePressureMonitoringDevice <", value, "tirepressuremonitoringdevice");
            return (Criteria) this;
        }

        public Criteria andTirepressuremonitoringdeviceLessThanOrEqualTo(String value) {
            addCriterion("TirePressureMonitoringDevice <=", value, "tirepressuremonitoringdevice");
            return (Criteria) this;
        }

        public Criteria andTirepressuremonitoringdeviceLike(String value) {
            addCriterion("TirePressureMonitoringDevice like", value, "tirepressuremonitoringdevice");
            return (Criteria) this;
        }

        public Criteria andTirepressuremonitoringdeviceNotLike(String value) {
            addCriterion("TirePressureMonitoringDevice not like", value, "tirepressuremonitoringdevice");
            return (Criteria) this;
        }

        public Criteria andTirepressuremonitoringdeviceIn(List<String> values) {
            addCriterion("TirePressureMonitoringDevice in", values, "tirepressuremonitoringdevice");
            return (Criteria) this;
        }

        public Criteria andTirepressuremonitoringdeviceNotIn(List<String> values) {
            addCriterion("TirePressureMonitoringDevice not in", values, "tirepressuremonitoringdevice");
            return (Criteria) this;
        }

        public Criteria andTirepressuremonitoringdeviceBetween(String value1, String value2) {
            addCriterion("TirePressureMonitoringDevice between", value1, value2, "tirepressuremonitoringdevice");
            return (Criteria) this;
        }

        public Criteria andTirepressuremonitoringdeviceNotBetween(String value1, String value2) {
            addCriterion("TirePressureMonitoringDevice not between", value1, value2, "tirepressuremonitoringdevice");
            return (Criteria) this;
        }

        public Criteria andZerotirepressuretocontinuedrivingIsNull() {
            addCriterion("ZerotirePressureToContinueDriving is null");
            return (Criteria) this;
        }

        public Criteria andZerotirepressuretocontinuedrivingIsNotNull() {
            addCriterion("ZerotirePressureToContinueDriving is not null");
            return (Criteria) this;
        }

        public Criteria andZerotirepressuretocontinuedrivingEqualTo(String value) {
            addCriterion("ZerotirePressureToContinueDriving =", value, "zerotirepressuretocontinuedriving");
            return (Criteria) this;
        }

        public Criteria andZerotirepressuretocontinuedrivingNotEqualTo(String value) {
            addCriterion("ZerotirePressureToContinueDriving <>", value, "zerotirepressuretocontinuedriving");
            return (Criteria) this;
        }

        public Criteria andZerotirepressuretocontinuedrivingGreaterThan(String value) {
            addCriterion("ZerotirePressureToContinueDriving >", value, "zerotirepressuretocontinuedriving");
            return (Criteria) this;
        }

        public Criteria andZerotirepressuretocontinuedrivingGreaterThanOrEqualTo(String value) {
            addCriterion("ZerotirePressureToContinueDriving >=", value, "zerotirepressuretocontinuedriving");
            return (Criteria) this;
        }

        public Criteria andZerotirepressuretocontinuedrivingLessThan(String value) {
            addCriterion("ZerotirePressureToContinueDriving <", value, "zerotirepressuretocontinuedriving");
            return (Criteria) this;
        }

        public Criteria andZerotirepressuretocontinuedrivingLessThanOrEqualTo(String value) {
            addCriterion("ZerotirePressureToContinueDriving <=", value, "zerotirepressuretocontinuedriving");
            return (Criteria) this;
        }

        public Criteria andZerotirepressuretocontinuedrivingLike(String value) {
            addCriterion("ZerotirePressureToContinueDriving like", value, "zerotirepressuretocontinuedriving");
            return (Criteria) this;
        }

        public Criteria andZerotirepressuretocontinuedrivingNotLike(String value) {
            addCriterion("ZerotirePressureToContinueDriving not like", value, "zerotirepressuretocontinuedriving");
            return (Criteria) this;
        }

        public Criteria andZerotirepressuretocontinuedrivingIn(List<String> values) {
            addCriterion("ZerotirePressureToContinueDriving in", values, "zerotirepressuretocontinuedriving");
            return (Criteria) this;
        }

        public Criteria andZerotirepressuretocontinuedrivingNotIn(List<String> values) {
            addCriterion("ZerotirePressureToContinueDriving not in", values, "zerotirepressuretocontinuedriving");
            return (Criteria) this;
        }

        public Criteria andZerotirepressuretocontinuedrivingBetween(String value1, String value2) {
            addCriterion("ZerotirePressureToContinueDriving between", value1, value2, "zerotirepressuretocontinuedriving");
            return (Criteria) this;
        }

        public Criteria andZerotirepressuretocontinuedrivingNotBetween(String value1, String value2) {
            addCriterion("ZerotirePressureToContinueDriving not between", value1, value2, "zerotirepressuretocontinuedriving");
            return (Criteria) this;
        }

        public Criteria andSeatbeltwarningIsNull() {
            addCriterion("SeatBeltWarning is null");
            return (Criteria) this;
        }

        public Criteria andSeatbeltwarningIsNotNull() {
            addCriterion("SeatBeltWarning is not null");
            return (Criteria) this;
        }

        public Criteria andSeatbeltwarningEqualTo(String value) {
            addCriterion("SeatBeltWarning =", value, "seatbeltwarning");
            return (Criteria) this;
        }

        public Criteria andSeatbeltwarningNotEqualTo(String value) {
            addCriterion("SeatBeltWarning <>", value, "seatbeltwarning");
            return (Criteria) this;
        }

        public Criteria andSeatbeltwarningGreaterThan(String value) {
            addCriterion("SeatBeltWarning >", value, "seatbeltwarning");
            return (Criteria) this;
        }

        public Criteria andSeatbeltwarningGreaterThanOrEqualTo(String value) {
            addCriterion("SeatBeltWarning >=", value, "seatbeltwarning");
            return (Criteria) this;
        }

        public Criteria andSeatbeltwarningLessThan(String value) {
            addCriterion("SeatBeltWarning <", value, "seatbeltwarning");
            return (Criteria) this;
        }

        public Criteria andSeatbeltwarningLessThanOrEqualTo(String value) {
            addCriterion("SeatBeltWarning <=", value, "seatbeltwarning");
            return (Criteria) this;
        }

        public Criteria andSeatbeltwarningLike(String value) {
            addCriterion("SeatBeltWarning like", value, "seatbeltwarning");
            return (Criteria) this;
        }

        public Criteria andSeatbeltwarningNotLike(String value) {
            addCriterion("SeatBeltWarning not like", value, "seatbeltwarning");
            return (Criteria) this;
        }

        public Criteria andSeatbeltwarningIn(List<String> values) {
            addCriterion("SeatBeltWarning in", values, "seatbeltwarning");
            return (Criteria) this;
        }

        public Criteria andSeatbeltwarningNotIn(List<String> values) {
            addCriterion("SeatBeltWarning not in", values, "seatbeltwarning");
            return (Criteria) this;
        }

        public Criteria andSeatbeltwarningBetween(String value1, String value2) {
            addCriterion("SeatBeltWarning between", value1, value2, "seatbeltwarning");
            return (Criteria) this;
        }

        public Criteria andSeatbeltwarningNotBetween(String value1, String value2) {
            addCriterion("SeatBeltWarning not between", value1, value2, "seatbeltwarning");
            return (Criteria) this;
        }

        public Criteria andIsofixIsNull() {
            addCriterion("ISOFIX is null");
            return (Criteria) this;
        }

        public Criteria andIsofixIsNotNull() {
            addCriterion("ISOFIX is not null");
            return (Criteria) this;
        }

        public Criteria andIsofixEqualTo(String value) {
            addCriterion("ISOFIX =", value, "isofix");
            return (Criteria) this;
        }

        public Criteria andIsofixNotEqualTo(String value) {
            addCriterion("ISOFIX <>", value, "isofix");
            return (Criteria) this;
        }

        public Criteria andIsofixGreaterThan(String value) {
            addCriterion("ISOFIX >", value, "isofix");
            return (Criteria) this;
        }

        public Criteria andIsofixGreaterThanOrEqualTo(String value) {
            addCriterion("ISOFIX >=", value, "isofix");
            return (Criteria) this;
        }

        public Criteria andIsofixLessThan(String value) {
            addCriterion("ISOFIX <", value, "isofix");
            return (Criteria) this;
        }

        public Criteria andIsofixLessThanOrEqualTo(String value) {
            addCriterion("ISOFIX <=", value, "isofix");
            return (Criteria) this;
        }

        public Criteria andIsofixLike(String value) {
            addCriterion("ISOFIX like", value, "isofix");
            return (Criteria) this;
        }

        public Criteria andIsofixNotLike(String value) {
            addCriterion("ISOFIX not like", value, "isofix");
            return (Criteria) this;
        }

        public Criteria andIsofixIn(List<String> values) {
            addCriterion("ISOFIX in", values, "isofix");
            return (Criteria) this;
        }

        public Criteria andIsofixNotIn(List<String> values) {
            addCriterion("ISOFIX not in", values, "isofix");
            return (Criteria) this;
        }

        public Criteria andIsofixBetween(String value1, String value2) {
            addCriterion("ISOFIX between", value1, value2, "isofix");
            return (Criteria) this;
        }

        public Criteria andIsofixNotBetween(String value1, String value2) {
            addCriterion("ISOFIX not between", value1, value2, "isofix");
            return (Criteria) this;
        }

        public Criteria andEmmoIsNull() {
            addCriterion("EMMO is null");
            return (Criteria) this;
        }

        public Criteria andEmmoIsNotNull() {
            addCriterion("EMMO is not null");
            return (Criteria) this;
        }

        public Criteria andEmmoEqualTo(String value) {
            addCriterion("EMMO =", value, "emmo");
            return (Criteria) this;
        }

        public Criteria andEmmoNotEqualTo(String value) {
            addCriterion("EMMO <>", value, "emmo");
            return (Criteria) this;
        }

        public Criteria andEmmoGreaterThan(String value) {
            addCriterion("EMMO >", value, "emmo");
            return (Criteria) this;
        }

        public Criteria andEmmoGreaterThanOrEqualTo(String value) {
            addCriterion("EMMO >=", value, "emmo");
            return (Criteria) this;
        }

        public Criteria andEmmoLessThan(String value) {
            addCriterion("EMMO <", value, "emmo");
            return (Criteria) this;
        }

        public Criteria andEmmoLessThanOrEqualTo(String value) {
            addCriterion("EMMO <=", value, "emmo");
            return (Criteria) this;
        }

        public Criteria andEmmoLike(String value) {
            addCriterion("EMMO like", value, "emmo");
            return (Criteria) this;
        }

        public Criteria andEmmoNotLike(String value) {
            addCriterion("EMMO not like", value, "emmo");
            return (Criteria) this;
        }

        public Criteria andEmmoIn(List<String> values) {
            addCriterion("EMMO in", values, "emmo");
            return (Criteria) this;
        }

        public Criteria andEmmoNotIn(List<String> values) {
            addCriterion("EMMO not in", values, "emmo");
            return (Criteria) this;
        }

        public Criteria andEmmoBetween(String value1, String value2) {
            addCriterion("EMMO between", value1, value2, "emmo");
            return (Criteria) this;
        }

        public Criteria andEmmoNotBetween(String value1, String value2) {
            addCriterion("EMMO not between", value1, value2, "emmo");
            return (Criteria) this;
        }

        public Criteria andCentrallockIsNull() {
            addCriterion("CentralLock is null");
            return (Criteria) this;
        }

        public Criteria andCentrallockIsNotNull() {
            addCriterion("CentralLock is not null");
            return (Criteria) this;
        }

        public Criteria andCentrallockEqualTo(String value) {
            addCriterion("CentralLock =", value, "centrallock");
            return (Criteria) this;
        }

        public Criteria andCentrallockNotEqualTo(String value) {
            addCriterion("CentralLock <>", value, "centrallock");
            return (Criteria) this;
        }

        public Criteria andCentrallockGreaterThan(String value) {
            addCriterion("CentralLock >", value, "centrallock");
            return (Criteria) this;
        }

        public Criteria andCentrallockGreaterThanOrEqualTo(String value) {
            addCriterion("CentralLock >=", value, "centrallock");
            return (Criteria) this;
        }

        public Criteria andCentrallockLessThan(String value) {
            addCriterion("CentralLock <", value, "centrallock");
            return (Criteria) this;
        }

        public Criteria andCentrallockLessThanOrEqualTo(String value) {
            addCriterion("CentralLock <=", value, "centrallock");
            return (Criteria) this;
        }

        public Criteria andCentrallockLike(String value) {
            addCriterion("CentralLock like", value, "centrallock");
            return (Criteria) this;
        }

        public Criteria andCentrallockNotLike(String value) {
            addCriterion("CentralLock not like", value, "centrallock");
            return (Criteria) this;
        }

        public Criteria andCentrallockIn(List<String> values) {
            addCriterion("CentralLock in", values, "centrallock");
            return (Criteria) this;
        }

        public Criteria andCentrallockNotIn(List<String> values) {
            addCriterion("CentralLock not in", values, "centrallock");
            return (Criteria) this;
        }

        public Criteria andCentrallockBetween(String value1, String value2) {
            addCriterion("CentralLock between", value1, value2, "centrallock");
            return (Criteria) this;
        }

        public Criteria andCentrallockNotBetween(String value1, String value2) {
            addCriterion("CentralLock not between", value1, value2, "centrallock");
            return (Criteria) this;
        }

        public Criteria andRemotekeyIsNull() {
            addCriterion("RemoteKey is null");
            return (Criteria) this;
        }

        public Criteria andRemotekeyIsNotNull() {
            addCriterion("RemoteKey is not null");
            return (Criteria) this;
        }

        public Criteria andRemotekeyEqualTo(String value) {
            addCriterion("RemoteKey =", value, "remotekey");
            return (Criteria) this;
        }

        public Criteria andRemotekeyNotEqualTo(String value) {
            addCriterion("RemoteKey <>", value, "remotekey");
            return (Criteria) this;
        }

        public Criteria andRemotekeyGreaterThan(String value) {
            addCriterion("RemoteKey >", value, "remotekey");
            return (Criteria) this;
        }

        public Criteria andRemotekeyGreaterThanOrEqualTo(String value) {
            addCriterion("RemoteKey >=", value, "remotekey");
            return (Criteria) this;
        }

        public Criteria andRemotekeyLessThan(String value) {
            addCriterion("RemoteKey <", value, "remotekey");
            return (Criteria) this;
        }

        public Criteria andRemotekeyLessThanOrEqualTo(String value) {
            addCriterion("RemoteKey <=", value, "remotekey");
            return (Criteria) this;
        }

        public Criteria andRemotekeyLike(String value) {
            addCriterion("RemoteKey like", value, "remotekey");
            return (Criteria) this;
        }

        public Criteria andRemotekeyNotLike(String value) {
            addCriterion("RemoteKey not like", value, "remotekey");
            return (Criteria) this;
        }

        public Criteria andRemotekeyIn(List<String> values) {
            addCriterion("RemoteKey in", values, "remotekey");
            return (Criteria) this;
        }

        public Criteria andRemotekeyNotIn(List<String> values) {
            addCriterion("RemoteKey not in", values, "remotekey");
            return (Criteria) this;
        }

        public Criteria andRemotekeyBetween(String value1, String value2) {
            addCriterion("RemoteKey between", value1, value2, "remotekey");
            return (Criteria) this;
        }

        public Criteria andRemotekeyNotBetween(String value1, String value2) {
            addCriterion("RemoteKey not between", value1, value2, "remotekey");
            return (Criteria) this;
        }

        public Criteria andPepsIsNull() {
            addCriterion("PEPS is null");
            return (Criteria) this;
        }

        public Criteria andPepsIsNotNull() {
            addCriterion("PEPS is not null");
            return (Criteria) this;
        }

        public Criteria andPepsEqualTo(String value) {
            addCriterion("PEPS =", value, "peps");
            return (Criteria) this;
        }

        public Criteria andPepsNotEqualTo(String value) {
            addCriterion("PEPS <>", value, "peps");
            return (Criteria) this;
        }

        public Criteria andPepsGreaterThan(String value) {
            addCriterion("PEPS >", value, "peps");
            return (Criteria) this;
        }

        public Criteria andPepsGreaterThanOrEqualTo(String value) {
            addCriterion("PEPS >=", value, "peps");
            return (Criteria) this;
        }

        public Criteria andPepsLessThan(String value) {
            addCriterion("PEPS <", value, "peps");
            return (Criteria) this;
        }

        public Criteria andPepsLessThanOrEqualTo(String value) {
            addCriterion("PEPS <=", value, "peps");
            return (Criteria) this;
        }

        public Criteria andPepsLike(String value) {
            addCriterion("PEPS like", value, "peps");
            return (Criteria) this;
        }

        public Criteria andPepsNotLike(String value) {
            addCriterion("PEPS not like", value, "peps");
            return (Criteria) this;
        }

        public Criteria andPepsIn(List<String> values) {
            addCriterion("PEPS in", values, "peps");
            return (Criteria) this;
        }

        public Criteria andPepsNotIn(List<String> values) {
            addCriterion("PEPS not in", values, "peps");
            return (Criteria) this;
        }

        public Criteria andPepsBetween(String value1, String value2) {
            addCriterion("PEPS between", value1, value2, "peps");
            return (Criteria) this;
        }

        public Criteria andPepsNotBetween(String value1, String value2) {
            addCriterion("PEPS not between", value1, value2, "peps");
            return (Criteria) this;
        }

        public Criteria andPkeIsNull() {
            addCriterion("PKE is null");
            return (Criteria) this;
        }

        public Criteria andPkeIsNotNull() {
            addCriterion("PKE is not null");
            return (Criteria) this;
        }

        public Criteria andPkeEqualTo(String value) {
            addCriterion("PKE =", value, "pke");
            return (Criteria) this;
        }

        public Criteria andPkeNotEqualTo(String value) {
            addCriterion("PKE <>", value, "pke");
            return (Criteria) this;
        }

        public Criteria andPkeGreaterThan(String value) {
            addCriterion("PKE >", value, "pke");
            return (Criteria) this;
        }

        public Criteria andPkeGreaterThanOrEqualTo(String value) {
            addCriterion("PKE >=", value, "pke");
            return (Criteria) this;
        }

        public Criteria andPkeLessThan(String value) {
            addCriterion("PKE <", value, "pke");
            return (Criteria) this;
        }

        public Criteria andPkeLessThanOrEqualTo(String value) {
            addCriterion("PKE <=", value, "pke");
            return (Criteria) this;
        }

        public Criteria andPkeLike(String value) {
            addCriterion("PKE like", value, "pke");
            return (Criteria) this;
        }

        public Criteria andPkeNotLike(String value) {
            addCriterion("PKE not like", value, "pke");
            return (Criteria) this;
        }

        public Criteria andPkeIn(List<String> values) {
            addCriterion("PKE in", values, "pke");
            return (Criteria) this;
        }

        public Criteria andPkeNotIn(List<String> values) {
            addCriterion("PKE not in", values, "pke");
            return (Criteria) this;
        }

        public Criteria andPkeBetween(String value1, String value2) {
            addCriterion("PKE between", value1, value2, "pke");
            return (Criteria) this;
        }

        public Criteria andPkeNotBetween(String value1, String value2) {
            addCriterion("PKE not between", value1, value2, "pke");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table safety_equipment
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table safety_equipment
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}